1단계 - 구간 추가 기능 변경
next-step/atdd-subway-path pull request #134
Opened 2021-03-17 17:45 UTC by DongHwani

안녕하세요 리뷰어님 
두번째 첫번째 미션 리뷰요청드립니다. 

첫번째 미션부터 생각보다 시간을 많이 소비했네요.
이번 미션 진행하면서 자연스럽게 ATDD -> TDD로 자연스럽게 한 사이클을 경험할 수 있어서 좋았습니다.(도메인 로직을 어렵게 만드셔서 이 사이클을 유도하신듯한 ㅠㅠ... )
 
미션 진행하면서 몇 가지 문의사항 남깁니다 

1. 도메인에서 예외테스트를 하였는데 서비스 영역에서도 동일한 테스트가 필요할까요? 간단한 기능같은 경우에는 서비스와 도메인 영역의 테스트가 중첩되는 부분이 있더라구요. 의견부탁드립니다.
2. Mock은 개발시 언제 사용하는게 좋을까요? 가짜객체를 쓰기 때문에 뭔가 불안해서 실무에서도 평소에 잘 안쓰긴 하는데 어떤 용도 혹은 필요성에 의해 사용해야 좋을지 아직 감을 잘 못잡겠습니다. 

미흡한 부분이 많지만, 리뷰요청드립니다. 이번 단계 미션 잘부탁드리겠습니다 :)

2021-03-18 12:28 UTC, ivvve requested changes
안녕하세요 동환님!
2주차 미션 같이 진행하게된 손영철이라고 합니다 :)

이번 미션을 통해 TDD cycle을 제대로 경험하시는 것 같습니다 😎
전체적으로 작은 단위의 클래스에 대해서도 테스트를 잘 작성해주셨어요 👍

다만 핵심 비지니스 로직 구현 방식에 대해 몇가지 코멘트를 남겼는데 해당 부분 확인해주시면 좋을 것 같습니다!
이해가 잘 되지 않거나 문의 사항있으시면 편하게 질문주시면 좋겠습니다 :)

---

> 1. 도메인에서 예외테스트를 하였는데 서비스 영역에서도 동일한 테스트가 필요할까요? 간단한 기능같은 경우에는 서비스와 도메인 영역의 테스트가 중첩되는 부분이 있더라구요. 의견부탁드립니다.

테스트가 중첩된다면 굳이 중복되는 테스트를 할 필요는 없다고 생각합니다.
저 같은 경우는 도메인 영역에서 예외 케이스를 포함하여 꼼꼼하게 테스트를 작성하는 편인데요.
일단 서비스보다 테스트가 가볍고 빠르기도 하고 파라미터를 직접 넣을 수 있어 예외 케이스를 구성하기가 편리하기 때문입니다!

그리고 서비스 테스트 같은 경우 component 연결과 관련된(정상 케이스에서 리턴이 기대하는 것과 일치하는지, repository에서 조회한 객체가 없는 경우 Exception handling 방법, 등) 것들에 대해서만 간단하게 테스트를 구성하는 편입니다 :)


> 2. Mock은 개발시 언제 사용하는게 좋을까요? 가짜객체를 쓰기 때문에 뭔가 불안해서 실무에서도 평소에 잘 안쓰긴 하는데 어떤 용도 혹은 필요성에 의해 사용해야 좋을지 아직 감을 잘 못잡겠습니다.

어떤 점이 크게 불안하실까요?
주로 repository나 외부 API를 호출하는 것과 같이 외부와 연동되는 부분을 원하는 방식대로 설정하기위해 사용될 수 있습니다.
또는 여러 component들을 조합해서 사용하는 경우도 포함이 되겠죠 :)

불안해하실 필요는 없지 않을까 싶구요 ㅎㅎ
하지만 저는 개인적으로 fake object를 사용하는 것을 선호합니다!
관련해서도 알아보시면 좋지 않을까 싶습니다 :)

2021-03-18 17:12 UTC, DongHwani commented
안녕하세요 리뷰어님, 
피드백 주신 내용 반영해서 리뷰요청드립니다.

- [x] Sections 클래스에서의 Line 직접적인 관여된 코드 리팩토링 필요
- [x] 구간의 길이를 줄이는 메서드명 변경 
- [x] Section 테스트 케이스 추가 
- [x] 시각화된 내용은 주석으로 처리
- [x] 중간 역추가에 대한 길이 확인 테스트 검증변경 

이번에도 좋은 리뷰부탁드립니다. 감사합니다 :)

2021-03-19 09:33 UTC, ivvve approved these changes
동환님 수고하셨습니다! 

리뷰 코멘트를 잘 반영해주신 것 같습니다 👍 
바로 다음 단계로 넘어가시죠 🚀

2021-03-19 09:33 UTC, ivvve commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private void swapStation(Section section) {
`swap`은 교대, 교체의 의미가 강한데요!
해당 워딩이 `구간을 추가`하는 것에 어울릴지 한 번 생각해보시면 좋을 것 같습니다 :)

2021-03-19 09:33 UTC, ivvve commented on src/test/java/nextstep/subway/line/acceptance/LineSectionAcceptanceTest.java
> +    }
앗... 😂

2021-03-19 09:33 UTC, merged