[단위테스트] 3단계 - 경로 조회
next-step/atdd-subway-path pull request #143
Opened 2021-03-19 02:23 UTC by perelandrax

2021-03-20 01:35 UTC, boorownie approved these changes
3단계 미션까지 잘 수행해주셨습니다!
커밋 로그를 보니  ATDD + TDD 사이클을 잘 지켜가면서 진행하신 것 같아요 💯 
테스트를 통한 검증 및 코드 구현 모두 좋네요 👍 

몇가지 추가적인 코멘트를 남겨보았는데요~
한번 고민해보시고 리팩터링 해보시면 좋을 것 같아요!

2021-03-20 01:35 UTC, boorownie commented on src/test/java/nextstep/subway/path/acceptance/PathAcceptanceTest.java
> +    public void setUp() {
오.. 상황 설정을 위한 픽스쳐 코드 👍

2021-03-20 01:35 UTC, boorownie commented on src/test/java/nextstep/subway/path/application/PathServiceMockTest.java
> +        ReflectionTestUtils.setField(강남역, "id", 1L);
id가 필요하다면 createStation과 같은 메서드로 분리해보면 어떨까요?

2021-03-20 01:35 UTC, boorownie commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +    }
경로 조회 결과를 PathFinder의 상태로 가지고 있게 하기 보다는 return 하도록 하면 어떨까요?

2021-03-20 01:35 UTC, boorownie commented on src/test/java/nextstep/subway/path/domain/PathFinderTest.java
> +    @DisplayName("출발역과 도착역이 연결이 되어 있지 않은 경우 실패")
경로 조회 라이브러리의 어댑터 역할을 하는 객체의 테스트를 잘 작성해주셨네요 👍

2021-03-20 01:35 UTC, boorownie commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +    private GraphPath graphPath;
PathFinder의 상태로 가지 않고 메서드 호출 시 생성하면 어떨까요?

GraphPath를 만드는게 큰 비용이 드는데 매번 호출을 할 때 마다 생성을 해야해서 부담일 수 있을 것 같아요
캐시 적용을 고려하여 GraphPath를 만들어 유지하는 부분과 Path를 find하는 부분을 분리하면 어떨까요?

2021-03-20 01:36 UTC, boorownie requested changes
3단계 미션까지 잘 수행해주셨습니다!
커밋 로그를 보니  ATDD + TDD 사이클을 잘 지켜가면서 진행하신 것 같아요 💯 
테스트를 통한 검증 및 코드 구현 모두 좋네요 👍 

몇가지 추가적인 코멘트를 남겨보았는데요~
한번 고민해보시고 리팩터링 해보시면 좋을 것 같아요!

2021-03-20 13:10 UTC, perelandrax commented on src/test/java/nextstep/subway/path/application/PathServiceMockTest.java
> +        ReflectionTestUtils.setField(강남역, "id", 1L);
넵! 수정하도록 하겠습니다!

2021-03-20 13:11 UTC, perelandrax commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +    private GraphPath graphPath;
위의 PathFinder 코멘트와 함께 수정하기는 했는데 원하시는 형태대로 된건지 살짝 감이 안오네요.
한번더 확인 부탁드리겠습니다. ㅎㅎ

2021-03-21 01:36 UTC, boorownie requested changes
질문 주신 부분에 대한 설명을 추가해서 코멘트 남겼습니다 :)
TDD 기반 리팩터링을 연습하실 겸 해서 추가 리팩터링 해보시면 좋을 것 같아요!

2021-03-21 01:36 UTC, boorownie commented on src/test/java/nextstep/subway/path/domain/PathFinderTest.java
> +    }
강남역만 메서드 분리를 해 주셨네요??

2021-03-21 01:36 UTC, boorownie commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        List<StationResponse> stationReponses = stations.stream()
```suggestion
        List<StationResponse> stationResponses = stations.stream()
```

오타 발견!

2021-03-21 01:36 UTC, boorownie commented on src/main/java/nextstep/subway/path/application/PathService.java
> +    }
```suggestion
    public PathResponse findShortestPath(Long sourceId, Long targetId) {
        Station source = stationService.findById(sourceId);
        Station target = stationService.findById(targetId);

        SubwayGraph subwayGraph = graphService.findGraph();

        return createPathResponse(subwayGraph, source, target);
    }
```

이런 느낌으로 Graph를 재사용(캐싱)할 수 있도록 분리한 뒤
source와 target에 따라서 경로를 다르게 응답할 수 있게 하면 어떨까 해서 드린 피드백이었습니다 :)
이 리팩터링을 할 때 TDD를 통한 점진적인 리팩터링을 연습해볼 수 있을 것 같아요!

2021-03-21 01:36 UTC, boorownie commented on src/test/java/nextstep/subway/path/application/PathServiceMockTest.java
> +        양재역 = createStation(2L, "양재역");
피드백 반영 👍

2021-03-21 01:42 UTC, perelandrax commented on src/test/java/nextstep/subway/path/domain/PathFinderTest.java
> +    }
오잉;;;

2021-03-21 01:54 UTC, perelandrax commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        List<StationResponse> stationReponses = stations.stream()
감사합니다! ㅎ

2021-03-21 01:54 UTC, perelandrax commented on src/main/java/nextstep/subway/path/application/PathService.java
> +    }
넵 올려주신 부분 다시 고민해보도록 하겠습니다!

2021-03-22 01:14 UTC, lane4-dev commented on src/main/java/nextstep/subway/path/application/PathService.java
> +    }
의도 해주신 방향으로 구현했는지 잘 모르겠습니다만...
레거시 TDD연습은 열심히 한것 같네요. ㅎ -0-;

2021-03-22 02:40 UTC, perelandrax commented on src/main/java/nextstep/subway/path/application/PathService.java
> +    }
의도 해주신 방향으로 구현했는지 잘 모르겠습니다만...
레거시 TDD연습은 열심히 한것 같네요. ㅎ -0-;

2021-03-22 05:12 UTC, boorownie requested changes
저의 의사가 제대로 전달이 되지않은 것 같아서 이대로 끝내기 조금 아쉬운 느낌이 드네요ㅠㅠ
PathService에서 Graph생성하는 역학만 GraphService에 위임하는 리팩터링을 해보면 어떨까요?ㅎㅎ
마지막까지 조금만 더 파이팅 입니다!

2021-03-22 05:12 UTC, boorownie commented on src/main/java/nextstep/subway/path/application/GraphService.java
> +    private SubwayGraph subwayGraph;
사실 저의 의도는 SubwayGraph를 생성하는 부분과 생성 시 필요한 List<Line> 조회(LineService를 통한) 역할도 GraphService이 가져가는게 의도이긴 했습니다 ^^;;

2021-03-22 05:12 UTC, boorownie commented on src/main/java/nextstep/subway/path/application/PathService.java
> +
Line 목록을 조회해서 SubwayGraph를 만드는 부분을 GraphService에 위임하게 되면 PathService는 LineService에 대한 의존을 제거할 수 있겠네요 :)

2021-03-22 05:12 UTC, boorownie commented on src/main/java/nextstep/subway/path/domain/SubwayGraph.java
> +    private final WeightedMultigraph<Station, DefaultWeightedEdge> graph;
그래프 객체 랩핑 및 로직 분리 👍

2021-03-22 05:12 UTC, boorownie commented on src/main/java/nextstep/subway/path/application/GraphService.java
> +        return subwayGraph;
```suggestion
        return new SubwayGraph(findSections());
```

이 부분에서  SubwayGraph를 초기화 해주면 어떨까요?

2021-03-22 05:19 UTC, perelandrax commented on src/main/java/nextstep/subway/path/application/GraphService.java
> +    private SubwayGraph subwayGraph;
아하! 그렇군요!

2021-03-22 06:48 UTC, perelandrax commented on src/main/java/nextstep/subway/path/application/GraphService.java
> +    private SubwayGraph subwayGraph;
이제서야... 그 깊은 뜻을 ㅎㅎ;;

2021-03-22 06:48 UTC, perelandrax commented on src/main/java/nextstep/subway/path/application/PathService.java
> +
네네~

2021-03-22 06:48 UTC, perelandrax commented on src/main/java/nextstep/subway/path/application/GraphService.java
> +        return subwayGraph;
넵!

2021-03-22 14:38 UTC, boorownie approved these changes
집요하게 리뷰해서 많이 힘드셨죠ㅠㅠ
뭔가 찝찝하게 넘어가는 것 보다는 한번 해보시는게 더 도움이 될 것 같아서 요청드렸던거니 
힘들었다고 너무 마음에 담아두진 마세요ㅠㅠㅎㅎ

3단계 미션을 포함하여 2주차 미션을 잘 마무리 해주셨습니다!
단위 테스트를 제대로 경험해볼 수 있는 미션이었길 바라봅니다 🙏

3주차 미션도 빠이팅입니다 !!

2021-03-22 14:38 UTC, boorownie commented on src/main/java/nextstep/subway/path/application/GraphService.java
> +    }
네! 맞습니다 💯

2021-03-22 14:38 UTC, boorownie commented on src/main/java/nextstep/subway/path/application/PathService.java
> +public class PathService {
Graph 관련 로직을 GraphService로 위임하니 간결해 보니네요 :)

2021-03-22 14:38 UTC, merged