2단계 - 구간 제거 기능 변경
next-step/atdd-subway-path pull request #155
Opened 2021-03-24 13:26 UTC by BlueCitron

안녕하세요 리뷰어님
이번에도 리뷰 잘부탁드립니다 😄  🙏

2021-03-25 08:36 UTC, youngcheol-son requested changes
안녕하세요 동성님! 
이번 미션도 깔끔하게 잘 해주셨습니다! :+1:

다만 단위 테스트를 몇 가지 추가해주시면 보다 안정적인 서버 애플리케이션이 될 것 같아요 :) 
또 `Line`의 `List<Section>` field를 일급 컬렉션으로 만들어 보시는건 어떨까요?
참고: https://jojoldu.tistory.com/412

코멘트 몇 개 남기니 확인해주시고 이해가 잘 안가거나 하는 부분이 있다면 알려주세요!

2021-03-25 08:36 UTC, youngcheol-son commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        boolean existStation = getStations().stream().anyMatch(it -> it == station);
`==`는 참조를 비교하기 때문에 `equals`를 써야할 것 같은데요
다른 부분도 `==`를 쓰고있는데 수정이 필요할 것 같습니다 :)

2021-03-25 08:36 UTC, youngcheol-son commented on src/test/java/nextstep/subway/line/domain/LineTest.java
> +        지하철_노선에_지하철역_순서_정렬됨(신분당선.getStations(), Arrays.asList(강남역, 판교역));
수정된 구간의 거리를 확인하는 테스트도 추가하면 좋을 것 같습니다 :)

2021-03-25 08:36 UTC, youngcheol-son commented on src/test/java/nextstep/subway/line/domain/LineTest.java
> +    @DisplayName("구간 중간에 위치한 지하철 역을 삭제한다.")
노선의 첫역을 삭제하는 테스트도 있으면 더 안정적인 테스트가 될 것 같습니다 :)

2021-03-28 13:21 UTC, ivvve approved these changes
안녕하세요 동성님!
2단계도 진행하시느라 수고하셨습니다! 💪 

차근차근 진행하시는 모습이 대단하십니다 👍 
2단계도 잘 진행하셨는데요 다만 일급 컬렉션 사용에 관련해서 조금 아쉬운 부분이 있어 이 부분은 아래에 좀 더 설명하도록 하겠습니다 :)

마지막 단계로 넘어가시죠! 🚀 

---

일급 컬렉션은 단순히 List를 wrapping하는 역할이 아닌 관련 로직을 일급 컬렉션으로 옮겨야 의미가 있습니다 :)
외부에서 리스트 값을 꺼낸후 하나하나 값을 비교하는 방식을 한다면 일급 컬렉션은 사실상 data holder 역할만 할 뿐이고,
관련 비지니스 로직은 다른 클래스들로 파편화되기 마련입니다. (이를 응집도라고 하죠)

다음 미션을 진행하면서 노선의 구간 추가 제거 관련 로직을 모두 `Sections`로 옮겨보시는건 어떨까요? :)

2021-03-28 13:21 UTC, merged