Step3 : 경로조회
next-step/atdd-subway-path pull request #157
Opened 2021-03-27 16:23 UTC by boraming9

* 지하철 최단 경로조회 구현 

Q1) Inside Out으로 먼저 구현했는데 아래 예시로 주신 2,3이 제대로 이해가 안된 것 같아 풀어서 설명한번 부탁드립니다.
ex) 경로 조회를 수행하는 도메인 구현 예시
  - 1. PathFinder 라는 클래스 작성 후 경로 조회를 위한 테스트를 작성
  - 2. 경로 조회 메서드에서 Line을 인자로 받고 그 결과로 원하는 응답을 리턴하도록 테스트 완성
  - 3. 테스트를 성공시키기 위해 JGraph의 실제 객체를 활용(테스트에서는 알 필요가 없음)

2021-03-28 03:00 UTC, boorownie requested changes
3단계 미션 수행 잘 해주셨습니다 👍 
인수 테스트 작성을 통해 TDD로 기능 구현하는 ATDD 싸이클 경험을 제대로 하고 계시군요 👍 

질문 주신 내용은 관련 코드에 코멘트로 남겨놓았으니 확인 부탁드려요!
그리고 혹시 빠뜨린 부분이 있거나 추가로 궁금하신 사항이 있으면 추가 코멘트를 작성해주시거나 DM을 보내주셔도 좋습니다 :)

2021-03-28 06:31 UTC, boraming9 commented on src/main/java/nextstep/subway/line/domain/Sections.java
>          List<Station> downStationList = getDownStationList();
습관이 무섭군요!ㅎㅎ(반영완료)

2021-03-28 07:33 UTC, boraming9 commented on src/test/java/nextstep/subway/path/application/PathServiceTest.java
> +public class PathServiceTest {
그러면 이 경우 테스트 대상을 검증하기 위한 getShortedPath()에서 
pathFinder.getShortestPath를 호출함으로써 PathFinder에서 실제 협력 객체가 자연스럽게 사용되어 
"3. 테스트를 성공시키기 위해 JGraph의 실제 객체를 활용(테스트에서는 알 필요가 없음) "
을 만족하게 됐다고 이해하면 될까요?

2021-03-29 11:12 UTC, boraming9 commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        );
Line(Station목록)조회와 Graph 생성 로직을 GraphService로 분리했는데, 추후에 캐시를 도입하면 어떤 형태로 활용되는 것인지요?!

2021-03-29 11:50 UTC, boraming9 commented
Step3 피드백 반영했습니다~!

질문은 이전 PR 피드백 대댓글로도 달아놓았는데 (눈표시해놓음) 아래 2가지입니다.
1. Line(Station목록)조회와 Graph 생성 로직을 GraphService로 분리했는데, 추후에 캐시를 도입하면 어떤 형태로 활용되는 것인지요?!
2. 테스트 대상을 검증하기 위한 getShortedPath()에서
pathFinder.getShortestPath를 호출함으로써 PathFinder에서 실제 협력 객체가 자연스럽게 사용되어
"테스트를 성공시키기 위해 JGraph의 실제 객체를 활용(테스트에서는 알 필요가 없음) " 을 만족하게 됐다고 이해하면 될까요?

2021-03-30 00:22 UTC, boorownie commented on src/main/java/nextstep/subway/path/application/PathFinder.java
> +    public StationGraphPath getShortestPath(List<Section> sections, Station source, Station target){
그래프 관련 로직 분리 👍

2021-03-30 00:22 UTC, boorownie commented on src/main/java/nextstep/subway/path/application/PathFinder.java
> +        return StationGraphPath.of(new DijkstraShortestPath<>(graph.getSubwayGraph()).getPath(source, target));
최단 경로를 찾는 책임을 SubwayGraph에 위임하면 어떨까요?

2021-03-30 00:22 UTC, boorownie commented on src/test/java/nextstep/subway/path/application/PathServiceTest.java
> +public class PathServiceTest {
네 제가 전달하고 싶은 메시지 그대로 입니다 👍

2021-03-30 00:26 UTC, boorownie commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        );
GraphService의 findGraph나 makeStations 메서드에 아래와 같이 활용할 수 있겠네요

```java
class GraphService {
    ...
    @Cacheable("graph")
    public SubwayGraph findGrpah() {
        ...
    }
}
```
아래 링크를 통해 스프링에서 제공하는 추상화된 캐시 기능 활용 방법을 확인해보세요 :)
https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-caching

2021-03-30 02:33 UTC, boorownie approved these changes
피드백 반영 잘 해주셨습니다 👍 
질문 주신 내용은 코멘트에 대댓글로 남겨놓았으니 참고해주세요!

경로 조회 미션 마무리 하시느라 고생 많으셨습니다!
인수 테스트 + TDD 싸이클을 경험해보는 미션으로 익숙하지 않다면 힘들 수 있는 미션인데 잘 해주셨네요
다음 미션들도 파이팅하셔서 많은 경험과 인사이트를 얻으실 수 있길 바라봅니다!
머지할게요~

2021-03-30 02:33 UTC, merged