Mission1
next-step/atdd-subway-path pull request #169
Opened 2022-01-29 19:20 UTC by MrPPak

안녕하세요 리뷰어님 2주차 미션 잘 부탁드립니다!

부족한 부분에 대해 리뷰해주시면 제게 성장이 많이 될거 같습니다.
리뷰 잘 부탁드립니다~

2022-01-30 05:02 UTC, dbeod2 requested changes
안녕하세요! 종혁님 ☺️

2번째 미션 리뷰를 맡게 된 원유라입니다. 
인수테스트 테스트가 실패한다고 말해주셔서 확인해보았는데 실패없이 정상적으로 테스트 되고있습니다 :-)

추가로 코멘트 남겨두었는데요 확인 부탁드립니다! 🙏 
리뷰 재요청 주세요 ☺️

2022-01-30 08:11 UTC, MrPPak commented on src/main/java/nextstep/subway/line/domain/Line.java
> +
네넵! 2차미션에 구현하려고 지웠는데.. 생각해보니 의도에 맞지 않은 것이었네요...

2022-01-30 08:12 UTC, MrPPak commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    }
> addSectionBasedOnDownStation과 중복 로직이네요!
어떻게 하면 공통화시킬 수 있을까요? 🤔

리뷰주신 것을 보고 곰곰히 생각하여 공통적인 부분을 꺼내는 로직을 생각해봤습니다.
개인적으로 걸리는 것은 isBasedUpStation 부분인데요 경우에따라 로직이 달라지므로 저렇게 짜봤습니다.

리뷰어님의 의견이 궁금합니다 :)

2022-01-30 08:18 UTC, MrPPak commented on src/test/java/nextstep/subway/line/service/LineServiceTest.java
> +
넵 리뷰 주신대로  service 테스트 부분을 짜봤습니다!

개인적으로 궁금한 점은 LineService의 findAllLines()이나 findLine() 같은 부분은
비즈니스 로직이 없고 그냥 Repository의 기능을 이용한 부분이라 이런 부분은 테스트가 필요한지 의문입니다.

제 생각은 이정도는 인수테스트에서 커버할 수 있다고 여겨지는데요 나머지 메소드들은 Repository 기능 외 비즈니스 로직이 있으니 테스트가 필요한데 저 두 메소드는 필요가 있을까...? 하는 생각이 듭니다.

리뷰어님의 의견이 궁금합니다 :)

2022-01-30 08:19 UTC, MrPPak commented on src/test/java/nextstep/subway/line/utils/LineUtils.java
> +        assertThat(response.jsonPath().getList("stations").size()).isEqualTo(2);
좋은 기능 알려주셔서 감사합니다 👍

2022-01-30 08:43 UTC, MrPPak commented on src/test/java/nextstep/subway/line/service/LineServiceTest.java
> +
아 그리고 고민이 많이 되는 부분이 있습니다.
Mock 테스트의 경우 프로덕션 코드에 의존한다는 단점이 있는데요~

https://galid1.tistory.com/772
여기의 글을 보면 실제 객체를 사용하는 테스트보다 Mock테스트의 사용을 추천하고 있습니다.
그런데 다른 것을 제쳐두고 테스트의 스피드에 대해서 강조를 하고 있는데요

제 생각도 크게 다르지 않은 것이 테스트할 때 프로젝트가 커진다면 속도가 많이 차이날 것 같기 때문입니다.

리뷰어님의 의견이 궁금합니다 :)

2022-01-30 13:36 UTC, dbeod2 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    }
넵! 중복로직을 가지고 있는 메서드 보다는 upStation인 경우 ealry return을 해주는 방식이 좋은 것 같아요! 👍🏻

2022-01-30 23:28 UTC, dbeod2 commented on src/test/java/nextstep/subway/line/service/LineServiceTest.java
> +
네! 조회기능은 인수테스트로도 충분히 테스트가 가능한 부분이라서 비즈니스로직 테스트에 집중해주시면 될 것 같아요👍🏻👍🏻

2022-01-31 00:21 UTC, dbeod2 approved these changes
안녕하세요! 종혁님 ☺️

피드백 반영 빠르게 잘해주셨네요! 
소소하게 코멘트 남겨둔 것 있으니 확인 부탁드리며,
다음단계에서 반영해도 될 것 같아서 이번미션은 바로 머지하겠습니다💯💯

그럼 다음미션을 진행해주세요! 👍🏻

2022-01-31 00:21 UTC, dbeod2 commented on src/main/java/nextstep/subway/exceptions/ControllerExceptionHandler.java
> +        e.printStackTrace();
logging하기위해서 찍어주신 걸까요?

2022-01-31 00:21 UTC, merged