🚀 1단계 - 구간 추가 기능 변경
next-step/atdd-subway-path pull request #204
Opened 2022-02-03 16:43 UTC by skid901

# 요구사항
- [x] 변경된 스펙에 대한 인수 조건 도출 및 인수 테스트 작성
- [x] 구간 추가 기능 요구사항 변경 대응
- [x] 비즈니스 로직 TDD로 기능 구현
---
안녕하세요, 리뷰어 님.
늦었지만 2 주차 미션 리뷰 잘 부탁드립니다!!
감사합니다. ^^7

2022-02-04 05:06 UTC, parkeeseul requested changes
안녕하세요 경덕님! ATDD + TDD 미션을 함께 하게 된 박이슬 입니다 😄 
1단계 미션 잘 진행해 주셨네요! 👍 
몇 가지 코멘트 남겨두었으니 확인 부탁드립니다
함께 이번 미션 잘 풀어나가 보아요! 화이팅 입니다 🔥

2022-02-05 08:24 UTC, skid901 commented on src/main/java/nextstep/subway/domain/Sections.java
> +                .filter(_section -> _section.getDownStation().equals(station))
section 이라는 네이밍이 같은 스코프 내에서 중복되어서, 람다 내에서만 사용한다는 의미로 언더바를 붙여 사용했습니다.
다만, 말씀해주신 부분을 다시 보니 보편적인 자바 네이밍 컨벤션하고 맞지 않다고 생각되어 변경했습니다.

2022-02-05 08:42 UTC, skid901 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +    }
`LineSectionAcceptanceTest` 를 아얘 못 보고 미션을 진행하고 있었네요...;;
구간 추가에 관련된 테스트를 해당 클래스에서 진행하도록 수정 및 실패 케이스 테스트를 추가했습니다.

2022-02-05 18:49 UTC, skid901 commented on src/test/java/nextstep/subway/domain/SectionsTest.java
> +
각 테스트 케이스 별로 별도의 셋업 환경을 설정해 주고 싶었는데,

`@BeforeEach` 어노테이션으로는 동일한 셋업 환경 밖에 설정할 수 없다고 생각했습니다.

테스트 케이스 별로 필요한 셋업 환경을 위해 각각의 `@MethodSource` 를 설정해 주는 방법을 활용했습니다.

2022-02-05 18:51 UTC, skid901 commented on src/test/java/nextstep/subway/domain/SectionsTest.java
> +    }
동일한 셋업 환경을 사용하는 다른 테스트 케이스에서는 활용되는 파라미터라서,

해당 케이스에서는 사용하지 않아도 필요한 파라미터라고 생각했습니다.

2022-02-05 18:51 UTC, skid901 commented on src/test/java/nextstep/subway/domain/SectionsTest.java
> +    }
여러 구간을 연속적으로 추가하는 테스트 케이스를 추가했습니다.

2022-02-05 18:56 UTC, skid901 commented on src/main/java/nextstep/subway/application/dto/LineResponse.java
> +public class LineResponse {
안내해 주신 시나리오를 저의 개발환경에서 재현했을 때, 하단 이미지와 같은 결과를 얻게 되었습니다.

관련 도메인 로직을 직접적으로 건드리지는 않았지만,

도메인 로직 외 서비스 로직을 변경하는 과정에서 오류가 수정되었을 수도 있을 것 같다고 생각됩니다.

해당 케이스에 대해서 혹시 다시 한번 확인 부탁드려도 될까요?? 🙏

<img width="511" alt="스크린샷 2022-02-06 오전 3 05 51" src="https://user-images.githubusercontent.com/34153657/152654950-8d3196af-e4c2-4728-9561-fb51a8469255.png">

2022-02-05 18:59 UTC, skid901 commented
안녕하세요, 이슬 님.

상세하게 피드백 주셔서 감사합니다.

이슬 님께서 주신 피드백 덕분에 테스트 코드를 보다 효율적으로 작성할 수 있도록 연습을 할 수 있었던 것 같아요. ^^7

피드백 주셨던 내용에 대해 코드로 반영 및 댓글로 제 생각을 기재해 보았습니다.

확인 부탁드립니다.

감사합니다.

2022-02-06 00:01 UTC, parkeeseul commented on src/test/java/nextstep/subway/domain/SectionsTest.java
> +
그러셨군요  👍 
개인적으로는 @ParameterizedTest 는 여러 argument를 이용하여 반복적으로 테스트를 수행할 수 있는데요,
테스트 케이스 별로 필요한 셋업 환경을 위해 @MethodSource 를 활용하는게 @MethodSource의 목적에 맞을까 하는 생각도 드네요,
또한 이로인해 테스트에 [필요하지 않은 데이터들도 함께 전달](https://github.com/next-step/atdd-subway-path/pull/204#discussion_r799114515) 받게되어 테스트의 가독성도 떨어질 수 있겠다는 생각도 듭니다.

각 테스트 케이스 별로 필요한 데이터들이 다르다면
LineSteps 처럼 Line, Station 등의 필요한 부분을 테스트 픽스처로 관리해도 좋을 것 같은데 이 부분에 대해서는 어떻게 생각하시나요? 😄

2022-02-06 07:06 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨네요! 👍 
의견 주신 사항에 저의 의견 남겨두었으니 확인 부탁드리고
다음 미션 진행해주세요! 😄 
화이팅 입니다 🔥

2022-02-06 07:06 UTC, merged