2단계 - 지하철 구간 추가 리팩터링
next-step/atdd-subway-path pull request #299
Opened 2022-07-19 00:06 UTC by zbqmgldjfh

## 안녕하세요 리뷰어님!!
우선 저의 리뷰를 담당해주셔서 감사하다는 말 먼저 전합니다!!

이전 리뷰에서 말씀해주신 점을 반영하여 sections 를 반환하는 메서드 자체를 지워버렸습니다.

## 질문 2가지
### 질문 1
지난번 대화를 통해 sections을 방어적 복사를 해도, sections에 담긴 원소인 section은 변경의 위험이 있음을 인지하게 되었습니다.
따라서 리뷰어님의 의견을 수용하여 Sections.getSections() 메서드는 제거 하였지만, "순서대로 역을 조회하는 기능" 때문에 **어차피 역들은 변경의 위험에 있을 수 밖에 없지 않나?** 란 생각이 들었습니다.

변경 위험의 노출 정도를 줄였다 생각하면 될까요? 이에 대한 의견이 궁금합니다!!

### 질문2 (구간 길이 검증의 불가능)
미션의 요구사항 중 다음과 같은 사항이 있습니다.
"구간을 중간에 추가할 때, 새로운 길이를 뺀 나머지를 새롭게 추가된 역과의 길이로 설정"
위 요구사항을 위해 sections를 반환받을 수 없다면, 추가된 구간 만이라도 가져오는 메서드를 만들어 변경된 거리를 확인해야 할까요?
근대 또 이게 Test 검증을 위한 메서드가 될것 같아서요 ㅎㅎ
변경된 길이를 어떻게 검증할지 고민이 됩니다 ㅎㅎ

2022-07-19 15:37 UTC, pch8388 requested changes
안녕하세요 🙇 
2단계 미션 잘 수행해주셨지만, 구현 요구 사항이 충족하지 않는 것 같아요 😢 
코멘트 참고하셔서 코드 수정 및 테스트 보강하셔서 다시 리뷰 요청해주세요 🔥

2022-07-19 15:37 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        return Collections.unmodifiableList(stations);
이렇게 구현하신 이유가 있을까요? 🤔 

1. List 를 외부에서 생성하여 `addStationByOrder` 의 인자로 넘겨서 해당 메서드에서 List 를 조작하는 형태를 사용할 이유가 없을 것 같습니다.
2. `getFirstUpStation()` 을 `addStationByOrder` 에서 호출하면 안돼나요? 해당 메서드내에서 처리해도 되는 것 아닐까요?
3. `addStationByOrder` 라는 네이밍으로 괜찮을까요? 🤔  메서드 시그니처를 보고 첫번째 인자에 들어가는 List 에 정렬된 역을 넣는 함수인지 판단이 가능할까요?

2022-07-19 15:37 UTC, pch8388 commented on src/test/java/nextstep/subway/unit/SectionTest.java
> +    public void create_section_with_invalid_distance(int distance) {
`@DisplayName` 👀

2022-07-19 15:37 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/Section.java
> +    public Section divideSectionByMiddle(Section section) {
이 메서드는 테스트 코드가 없는 것 같아요 👀

2022-07-20 06:17 UTC, zbqmgldjfh commented on src/main/java/nextstep/subway/domain/Sections.java
> +        return Collections.unmodifiableList(stations);
1, 2번은 말씀해주신 것 처럼 해당 메서드 내부에서 생성하고 추가하도록 변경하였습니다 ㅎㅎ
TDD의 일단 막 구현하기 단계에서 막 구현만하고.... 리팩터링을 안해버린 것 같습니다...

메서드 이름은 getOrderedStations로 변경하였습니다!!

2022-07-20 06:17 UTC, zbqmgldjfh commented on src/main/java/nextstep/subway/domain/Sections.java
> +        sections.add(section);
Section 도메인의 divideSectionByMiddle 메서드를 검증하는 단위테스트 부분에서 distance를 검증하도록 변경하였습니다.

2022-07-20 06:18 UTC, zbqmgldjfh commented on src/main/java/nextstep/subway/domain/Sections.java
> +        Section halfSection = findSection.divideSectionByMiddle(section);
좋은 리뷰인것 같습니다!! 수정하였습니다. 감사합니다!!
distance상태를 가지고 있는 객체가 이를 처리하도록 변경하였습니다!!

2022-07-20 06:18 UTC, zbqmgldjfh commented on src/test/java/nextstep/subway/unit/SectionsTest.java
> +        assertThat(sections.getStations()).containsExactly(newStation, upStation, downStation);
아 List<Section> 에서 0번 index로 가져온다고 해서 첫 구간이 아닐 수 있는데, 구현할 때 이점을 생각하지 못했던것 같습니다.
지적해주셔서 감사합니다!!

2022-07-20 06:18 UTC, zbqmgldjfh commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
추가된 Section의 2역중 어느 역도 포함하지 않으면 예외를 던지도록 하려 했는데,
hasUpStation, hasDownStation **변수를 생성하는 곳과 멀리 떨어진 곳에서 이를 사용하고 있었던것 같습니다.**

해당 부분 다른 메서드를 통해 검증하도록 수정하였습니다!

2022-07-20 06:18 UTC, zbqmgldjfh commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
앗... 합치는것이 더 가독성이 좋을것 같습니다 ㅎㅎ, 수정하였습니다!

2022-07-20 06:21 UTC, zbqmgldjfh commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +     */
음 이게 말씀하신 것 처럼 "단순 주석"에 해당되면 위 의견에 부합하다 생각하는데,
위 주석은 "인수조건"에 해당되기 때문에 일반적인 주석과는 다르다 생각합니다? 

이게 코드의 설명을 위한 주석이라기 보단, 유저 스토리를 정리한 인수 조건을 단순히 표현 도구로 "주석"을 사용한거라 생각되서요 ㅎㅎ

꼭 지워야만 하는것 일까요?
인수조건 주석이 있다고 해서 시나리오 분석에 가독성이 떨어지지는 않는다고 생각 되서요 ㅎㅎ

2022-07-20 06:29 UTC, zbqmgldjfh commented on src/main/java/nextstep/subway/exception/sections/SectionsException.java
> +public class SectionsException extends BusinessException {
Sections 관련 예외 -> SectionsException
Station 관련 예외 -> StationException 과 같이 처리하고,
세부적인 내용들은 errorMessage를 통해 사용하려 하였는데 이러한 방식보다는 세분화하는 것 이 더 좋을까요?

사실 기존의 만들어진 Java의 Exception을 잘 활용하는 편이 좋다고는 생각하는데,
CustomException을 잘 사용해보지 않아 적용시켜 봤습니다.

- 장점
우선 ErrorCode와 같은 부분을 한곳에서 관리가 가능하기에 장점이 된다 생각합니다.
또한 우리가 만든 Exception이기 때문에 도메인 별로 만들어 두면, 도메인과 관련된 내용 또한 해당 Exception안에 모아둘 수 있다 생각하였습니다.

- 단점
단점으로는 직접 만들다 보니... 은근 귀찮은 작업인것 같습니다??
또한 신규로 프로젝트에 투입된 사람일 경우, 해당 팀읜 Custom 예외 사용방식에 적응기간이 필요하다는 단점이 있을 것 같습니다?

2022-07-20 06:33 UTC, zbqmgldjfh commented on src/main/java/nextstep/subway/domain/Sections.java
>      private Section getLastSection() {
해당 메서드는 언급해주신 firstSection을 가져오는 메서드와 마찬가지로 index기반이기 때문에 마지막 Section을 정확하게 가져오지 못할것 같습니다. 

해당 메서드를 사용하는 곳은 지금 deleteLastSection 메서드가 유일한데, 이는 "3단계 - 지하철 구간 제거 리팩터링" 에서 수정해보록 하겠습니다!

2022-07-20 11:29 UTC, zbqmgldjfh commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (hasUpStation && hasDownStation) {
if (hasUpStation && hasDownStation) 의 조건문 안에도 메서드로 추출하여 리팩터링 할 수 있음을 느끼는데, 지금의 31, 32, 33 행을 봤을때 사실 저는 가독성이 떨어진다고 느껴지지는 않아서요 ㅎㅎ 리뷰어님의 의견이 궁금합니다!!

2022-07-20 15:37 UTC, pch8388 approved these changes
리팩토링 하시느라 수고많으셨습니다 👏 
전체적으로 꼼꼼히 잘 구현해주셨습니다. 👍 
코멘트 남겨드린 부분은 다음 단계에서 수정해보시는 걸 추천드려요 😄 
이번 단계는 여기서 머지하겠습니다. 🚀

2022-07-20 15:37 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +     */
꼭 지워야만 한다고 생각하지는 않습니다. 😅 
다만 인수 테스트의 조건이 메서드 내부와 `Displayname` 등으로 충분히 설명이 가능하다고 생각하여 말씀드렸습니다. 
개인적으로는 소스 코드 중에 가장 유지보수가 힘든게 주석이라고 생각합니다. 😭 
컴파일/런타임 오류도 발생시키지 않으며, 오래되었거나 잘못된 정보를 전달할 가능성이 크기 때문입니다.

2022-07-20 15:40 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (hasUpStation && hasDownStation) {
클린코드에서 다음과 같이 이야기합니다.
> 함수를 만드는 첫째 규칙은 '작게!'다. 함수를 만드는 둘째 규칙은 '더 작게!'다. ...(중략)... 함수는 100줄을 넘어서는 안 된다. 아니 20줄도 길다.

참고로 TDD 수업에서는 각 함수의 크기를 10줄 이하로 제한하여 연습하는 것을 추천하였던 것으로 기억합니다. 😄 
학습의 목적이기 때문에, 다소 복잡해 보일 수 있어도 리팩토링을 통해 함수를 더 작게 구현해보시는 것을 추천드립니다

2022-07-20 15:41 UTC, merged

2022-07-20 16:02 UTC, pch8388 reviewed
빠뜨린 추가로 코멘트 드립니다  🙇

2022-07-20 16:02 UTC, pch8388 commented on src/test/java/nextstep/subway/unit/SectionsTest.java
> +public class SectionsTest {
예시를 달아드릴 곳이 마땅하지 않아 여기에 넣었습니다.
아래와 같이 테스트 해보면 기존의 구간의 거리가 제대로 나누어지지 않고 있습니다 😢 

```java
// newStation -(5) upStation -(10) downStation
Section newSection = new Section(line, newStation, upStation, 5);
sections.add(newSection);

// newStation -(5) upStation -(9) newStation2 -(1) downStation
Station newStation2 = new Station(4L, "신규역2");
Section newSection2 = new Section(line, upStation, newStation2, 9);
sections.add(newSection2);

// newStation -(5) upStation -(9) newStation2 -(3) newStation3 -(??) downStation
Station newStation3 = new Station(5L, "신규역3");
Section newSection3 = new Section(line, newStation2, newStation3, 3);
sections.add(newSection3);
```

2022-07-21 02:30 UTC, zbqmgldjfh commented on src/main/java/nextstep/subway/domain/Sections.java
> +                .map(this::getFirstUpStation)
악의 근원지를 찾았습니다.
<img width="860" alt="스크린샷 2022-07-21 오전 10 53 38" src="https://user-images.githubusercontent.com/60593969/180116987-c4af445e-d0e5-47e8-b393-b21c1a4d0737.png">

위 부분을 수정한 후, 예시로 주신 테스트 코드를 작성해보니 StackOverFlow가 발생하지 않게 되었습니다 ㅎㅎ

2022-07-21 05:33 UTC, zbqmgldjfh commented on src/test/java/nextstep/subway/unit/SectionsTest.java
> +public class SectionsTest {
이또한 위 악의 근원지를 해결하니... 테스트가 정상적으로 실행되었습니다.

2022-07-22 10:39 UTC, pch8388 commented on src/test/java/nextstep/subway/unit/SectionsTest.java
> +        assertThat(sections.getStations()).containsExactly(newStation, upStation, downStation);
네 문제를 파악해보시라고 일부러 정답을 말씀드리지 않았습니다 😅