🚀 2단계 - 지하철 구간 추가 리팩터링
next-step/atdd-subway-path pull request #377
Opened 2022-07-27 05:29 UTC by sangnyyy

안녕하세요 리뷰어님! 
이번 리뷰도 잘 부탁드립니다 :)

2022-07-27 10:46 UTC, junwoochoi requested changes
안녕하세요! 2단계 진행해주신 부분 잘 확인했습니다 👍 
간단히 확인하고 넘어가면 좋을 부분 몇가지 코멘트 드렸으니
수정 후 재요청 부탁드립니다 :)
궁금하거나 이해안가는 부분이 있으시면 편하게 연락주세요 감사합니다!

2022-07-27 10:46 UTC, junwoochoi commented on src/main/java/nextstep/subway/exception/ControllerAdvice.java
> +public class ControllerAdvice {
Global Exception 핸들링 💯

2022-07-27 10:46 UTC, junwoochoi commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +
예외 케이스 꼼꼼히 체크 👍

2022-07-27 10:46 UTC, junwoochoi commented on src/test/java/nextstep/subway/domain/SectionTest.java
> +class SectionTest {
단위테스트도 꼼꼼히 작성하셨네요 👍

2022-07-27 10:46 UTC, junwoochoi commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        assertThat(response.jsonPath().getList("stations.id", Long.class)).containsExactly(강남역, 중간역, 양재역);
`then`부분에 중복이 많은데 함수추출이 가능하겠네요 :)

2022-07-27 10:46 UTC, junwoochoi commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +    @ValueSource(ints = {10, 11})
👍 👍

2022-07-27 23:20 UTC, sangnyyy commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private ToBeAddedSection toBeAddedSection(Section newlySection) {
저는 엘레강트 오브젝트라는 책에 나와있는 내용처럼 빌더(뭔가를 항상 반환하는) 메서드의 경우, 명사형으로 짓는 편인데요!

저자가 명사형으로 짓는 것을 권장하는 이유는 동사형으로 네이밍하는 것은 메서드의 행동을 외부로 노출시키기 때문에 그 행동이
예측가능하여 캡슐화에 저해되고, 객체의 자율성을 해치기 때문이라고 합니다. 
따라서, 객체지향적인 접근법 보다는 절차지향적인 접근법에 가깝다고 하네요.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/24868642/181388836-1ee5dfe0-278a-49da-b8ab-1467bdadb5bb.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/24868642/181388862-df433b2c-4b9c-4982-894e-dc7d2c04c58c.png">


이 부분은 일단 넘어가도 괜찮을까요?

참고 부탁드립니다.
- https://jessyt.tistory.com/141

2022-07-27 23:29 UTC, sangnyyy commented on src/main/java/nextstep/subway/domain/Sections.java
> +    boolean hasStation(Station station) {
테스트 코드 검증을 위해서요! ㅎㅎ

좀 더 용이한 단위테스트를 위해 private 메서드 사용 메서드를 새로운 객체의  public 메서드로 만들어 조합(Composition) 후
테스트 코드를 짤 수도 있었겠군요  (예를 들어, HasStation 객체를 만듬) 

다만, 오버 엔지니어링 스러운 느낌이 들 수도 있고 내부 사용처 밖에 없는 메서드이기에 테스트 하기 위해 접근제어자 지정을 안해주셨다고 보시면 됩니다. 


참고로, 디폴트 메서드는 protected 보다 좀 더 강력한 접근 제어를 합니다. 
(Subclass outside the same package 여부 디폴트, protected 각각 접근 불가능, 가능)

![image](https://user-images.githubusercontent.com/24868642/181389474-97331ddb-a1e5-4bc5-b218-5320138694e5.png)

2022-07-27 23:51 UTC, sangnyyy commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
말씀 주신 덕에 한번 더 리팩토링 하며 깔끔한 코드를 얻어낼 수 있었습니다. 감사합니다 🙇‍♂️
다음과 같이 처리해보았어요 https://github.com/next-step/atdd-subway-path/pull/377/commits/a0fb479358eb4f26eca96547ac9ceaf9550c01b1

2022-07-27 23:57 UTC, sangnyyy commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        assertThat(response.jsonPath().getList("stations.id", Long.class)).containsExactly(강남역, 중간역, 양재역);
이렇게 처리해보았습니다 https://github.com/next-step/atdd-subway-path/pull/377/commits/953703ac47ecb59ce2c99b2a67ce6fbb00732a62

2022-07-28 00:06 UTC, junwoochoi commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private ToBeAddedSection toBeAddedSection(Section newlySection) {
@sangnyyy 넵 의도적으로 작성하신 것이라면 넘어가셔도 됩니다~

2022-07-28 00:16 UTC, junwoochoi commented on src/main/java/nextstep/subway/domain/Sections.java
> +    boolean hasStation(Station station) {
@sangnyyy private 메소드를 테스트해야하는가?에 대해 고민이 필요할 것 같습니다. 물론 정답은 없습니다 ㅎㅎ..
저 같은 경우는 기능 혹은 private 메소드를 사용하는 상위 public 메소드들을 테스트하는 과정에서 private메소드가 자연스럽게 테스트된다고 생각하는 편입니다. 
테스트 때문에 실제 객체의 접근제어자를 수정하여 의도치 않게 외부에서의 사용이 생기는 것도 원치 않아서요(물론 default로 했을 때 제한된 곳에서만 접근이 가능하지만) 물론 가끔 테스트가 꼭 필요할 것 같은 private 메소드들도 생기는데요 요런 경우 저는 reflection을 활용해서 테스트하고 있습니다. 스프링에서 제공하는 ReflectionTestUtils를 활용하면 조금 더 편하더라구요 :)

여러가지 의견이 있으니 한번 고민해보시면 좋을 것 같고 현재 코드에서는 고민을 해보시고 수정을 하신 것으로 보여서 이번에 같이 머지하겠습니다! 
https://justinchronicles.net/ko/2014/07/14/dont-do-testing-private-methods/
https://ui.toast.com/weekly-pick/ko_20200708

2022-07-28 02:50 UTC, junwoochoi approved these changes
피드백 적용 잘해주셔서 감사합니다!
적극적으로 의견 주셔서 저도 미션 리뷰가 즐겁네요 :)

3단계 미션 이어서 진행해주세요~ 💪

2022-07-28 02:50 UTC, merged