Step4: 경로 조회
next-step/atdd-subway-path pull request #391
Opened 2022-07-29 07:23 UTC by imcool2551

안녕하세요! 4단계 리뷰 잘 부탁드립니다!

2022-07-29 16:34 UTC, pch8388 requested changes
안녕하세요 🙇 
어려운 미션인데 전체적으로 잘수행해주셨네요 👏 
고민해보실만한 부분을 코멘트로 남겨드렸습니다.
코멘트 참고하셔서 리팩토링 후 리뷰요청 부탁드립니다 🔥

2022-07-29 16:34 UTC, pch8388 commented on src/main/java/nextstep/subway/path/application/PathService.java
> +                .collect(Collectors.toList());
정점을 `Station` 으로 설정하면 이런 과정을 거칠 필요가 없을 것 같아요 😄

2022-07-29 16:34 UTC, pch8388 commented on src/main/java/nextstep/subway/path/application/PathService.java
> +@Transactional(readOnly = true)
💯

2022-07-29 16:34 UTC, pch8388 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        Section secondRemovedSection = findByUpStationId(stationId);
처음부터 삭제할 구간들을 찾는 방법은 없을까요? 🤔

2022-07-30 13:53 UTC, imcool2551 commented on src/test/java/nextstep/subway/line/acceptance/SectionAcceptanceTest.java
> +    @DisplayName("지하철 노선에 첫 구간을 추가한다.")
@DisplayName 애노테이션과 메서드 바디 안에서의 given, when, then 주석만으로 테스트의 의도가 명확히 표현된다고 생각해서 지우고 나서 만족했습니다. :)

2022-07-30 14:11 UTC, imcool2551 commented on src/test/java/nextstep/subway/path/acceptance/PathAcceptanceTest.java
> +        Long 제거역 = createResponse.jsonPath().getLong("id");
앗..위의 코드는 `var`를 사용했는데.. 혹시 `ExtractableResponse`를 `var` 키워드로 받지 않는 부분에 대해서 리뷰해주신게 맞을까요?? 

일단 가장 처음 의도는 `ExtractableResponse<Response>`를 변수 타입으로 받으면 코드가 가로로 너무 길어져서 가독성이 떨어진다고 판단하여 `var` 키워드를 사용했습니다. 근데 살펴보니 `ExtractableResponse`를 변수 타입으로 사용하는 곳이 남아있어서 일관성+가독성을 위해 모두 `var`로 바꿨습니다.

2022-07-30 14:30 UTC, imcool2551 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        Section secondRemovedSection = findByUpStationId(stationId);
죄송합니다. 제가 질문의 의도를 완벽히 파악하지 못해서.. 혹시 아래 코드와 비슷하게 한 번의 순회로 구간 삭제를 처리하는 것을 추천해주신게 맞나요?

` sections.removeIf(it -> it.matchUpStation(firstId) || it.matchUpStation(secondId));`

2022-07-30 14:50 UTC, imcool2551 commented on src/main/java/nextstep/subway/path/application/PathService.java
> +                .collect(Collectors.toList());
경로를 찾을 수 없는 다른 이유를 각각 처리하기 위해 `역 정보`와 `구간 정보`를 별도로 조회했습니다. 

아예 *존재하지 않는 지하철역*으로 경로를 조회하는 경우와

```
if (!graph.containsVertex(source) || !graph.containsVertex(target)) {
 throw  new CannotFindPathException("시작점이나 종점이 존재하지 않습니다.");
}
```

지하철역들은 존재하지만 *경로가 존재하지 않는* 경우

```java
private void validatePathExistence(GraphPath<Long, DefaultWeightedEdge> shortestPath) {
        if (shortestPath == null) {
            throw new CannotFindPathException("시작점과 종점이 연결되어 있지 않습니다.");
        }
}
```

두 경우를 별도로 예외 처리하기 위해 *구간에 속하지 않은 지하철역* 을 별도로 조회했습니다.

만약 클라이언트 측에서 경로를 찾을 수 없는 상세한 이유를 알 필요가 없다면 승철님이 제안해주신대로 한 번의 조회로 그래프를 만드는 방법이 성능상 낫다고 생각하고 있는데 혹시 추가 의견을 주실 수 있다면 감사하겠습니다!

2022-07-30 15:15 UTC, imcool2551 commented on src/main/java/nextstep/subway/path/application/PathService.java
> +                .collect(Collectors.toList());
앗.. 이 부분은 제가 step2에서 질문드린 도메인간의 의존성과 비슷한 맥락인 것 같네요. 아무래도 요즘 도메인간의 의존을 최대한 느슨하게 가져가는게 좋다는 생각을 하다보니 재 성향이 도메인 설계에도 반영이 된 것 같네요..ㅎㅎ 

경로 조회를 위한 `Graph`를 만들 때 생성자로 `Station`을 넘겨서 정점을 만들고 `Section`을 넘겨서 간선을 만들면 `PathService`의 많은 변환 코드들이 줄어들긴 할 것 같습니다. 그런데 굳이 `Station`에서 `id`만 뽑고 `Section`도 모양이 비슷한 `Edge`라는 간선 객체로 변환한 이유는 경로(path) 도메인에서 역(station) 도메인과 노선(line,section) 도메인으로의 의존하게 하고싶지 않아서 그랬습니다. 경로 도메인의 서비스 계층에서 다른 도메인의 서비스 계층을 의존하는 것은 어쩔 수 없지만, 최소한 `domain` 패키지의 핵심 도메인 객체들만이라도 의존을 가져가지 말자는 의도였는데 추가 의견을 주시면 감사하겠습니다! 

다소 복잡하게 보일 수 있는 서비스 계층의 변환 로직 때문에 사실 개발하면서도 너무 과한 것 아닌가라는 생각을 하기도 했습니다..ㅎㅎ

2022-08-01 01:44 UTC, pch8388 commented on src/test/java/nextstep/subway/path/acceptance/PathAcceptanceTest.java
> +        Long 제거역 = createResponse.jsonPath().getLong("id");
개인적인 의문이었습니다. 😄 
코드를 읽는 사람으로서 `멈칫` 하는 부분이 있으면 수정을 고려해볼만 하다고 여겨서 남겨드렸습니다. 🔥

2022-08-01 01:46 UTC, pch8388 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        Section secondRemovedSection = findByUpStationId(stationId);
사실 위의 `index`를 찾는 부분에 리뷰를 단 것인데, 코멘트가 조금 이상한 부분에 달렸네요 😢

2022-08-01 01:52 UTC, pch8388 commented on src/main/java/nextstep/subway/path/application/PathService.java
> +                .collect(Collectors.toList());
존재하지 않는 지하철역이라는 것은 `StationService` 에 있는 `역ID`를 찾는 메서드로 충분하지 않을까요? 🤔 
사실 현재 도메인에서는 어울리지 않는 비유일 수 있지만, 데이터베이스에 `findAll` 쿼리를 전송하는 것은 지양해야 한다고 생각합니다.(물론 어차피 모든 구간을 조회하긴 하지만...) 
결국엔 특정 저장소의 데이터를 가져오는 것이기 때문에 이런 부분도 고려해볼만 한 것 같아요 😅 
사실 현재 도메인 특성상 지하철역이 부하가 걸릴만큼 늘어나거나 할 가능성은 적기 때문에 구현해주신 방법으로 해도 무관하다고 생각합니다. 👍

2022-08-01 02:03 UTC, pch8388 commented on src/main/java/nextstep/subway/path/application/PathService.java
> +                .collect(Collectors.toList());
사실 이런 부분에 대한 의견을 드리기가 조심스럽긴 합니다만 😅 
그럼에도 불구하고 개인적인 생각을 말씀드리자면, 말씀해주신대로 도메인 간 의존성을 줄이는 방법은 좋습니다.
하지만, 도메인 간 의존성을 줄이는 것이 객체를 사용하지 말자는 것일까요? 🤔 
의존성을 줄이는 방법에는 여러가지가 있습니다. 의존성 역전 같은 방법이나 DDD, 클린 아키텍처 같은 방법론에서 주장하는 것도 (큰 맥락에서는) 의존성을 줄이기 위한 여러가지 시도라고 생각합니다.
에릭에반스가 쓴 DDD 에서는 같은 도메인이라도 컨텍스트마다 형태는 다를 수 있다는 점을 이야기합니다.
예를 들어, `Member` 가 지하철 요금을 계산할 때는 `Customer` 로 표현될 수 있겠죠?
물론, 제가 말씀드린 것처럼 다시 객체를 쓰려고 변환하려는 행위는 구현을 더 복잡하게 만들기만 할 수도 있습니다.
여러가지 측면에서 고민해보실 수 있게 도움을 드리고자 첨언한 것이니 많이 생각해보시고 많은 방법을 사용해보세요 😄 
(조금 더 자세한 토론이 필요하시면 DM 부탁드립니다.)

2022-08-02 03:36 UTC, pch8388 approved these changes
리팩토링 잘해주셨습니다 👏 
구현하신 것을 보니 고민의 흔적이 많이 보이네요 😄 
미션은 여기서 종료되지만 다른 미션 수행중이나 현재 마무리하신 미션에 대해 궁금하신 점이나 토론하고 싶으신 점이 있다면 언제든 연락주세요 🔥 
Merge 하겠습니다. 🚀

2022-08-02 03:36 UTC, pch8388 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private void removeMiddleStation(Long removedStationId) {
리팩토링 잘해주셨네요 💯

2022-08-02 03:36 UTC, pch8388 commented on src/test/java/nextstep/subway/path/acceptance/PathAcceptanceTest.java
> +     *  참고: 점선 하나가 거리 1을 의미합니다.
👍

2022-08-02 03:36 UTC, pch8388 commented on src/test/java/nextstep/subway/path/domain/GraphTest.java
> +                new Section(LINE1, 1L, 2L, 2),
`지하철역ID`를 테스트에서 반복적으로 사용하기 때문에 변수로 두는 것도 테스트를 이해하는 데 도움이 될 것 같아요 😄

2022-08-02 03:36 UTC, pch8388 commented on src/main/java/nextstep/subway/line/domain/Sections.java
>          }
유효성 검증 부분을 메서드 추출하면 가독성 향상에 도움이 될 것 같아요 😄

2022-08-02 03:36 UTC, pch8388 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        removeMiddleStation(removeStationId);
`sections` 에 구간을 삭제하는 `remove` 가 이 메서드에서는 감춰져 있는데요. 물론 메서드 이름으로 추측해볼수는 있지만, 조금 더 이해하기 쉽게하려면 어떻게 할 것인가? 를 고민해볼 수 있을 것 같구요
`isFirstStation` `isLastStation` 부분도 끝에 있는 역이라는 조건으로 하나로 합치도록 할 수 있을 것 같아요 😄 
실제로 구현해보면서 어떤 방법을 사용하는 것이 가장 읽기 좋은 지 고민해보면 좋을 것 같습니다. 🔥 

이 코멘트는 참고용으로 생각만 한번 해주시면 될 것 같아요 😄

2022-08-02 03:36 UTC, pch8388 commented on src/test/java/nextstep/subway/path/domain/GraphTest.java
> +class GraphTest {
테스트 잘 구현해주셨습니다. 👏 
최단 경로 찾기에 대한 테스트가 조금 더 보충이 된다면 좋을 것 같아요 😄 
환승해야 하는 경우 / 바로 갈 수 있는 경우 / 역 개수는 적지만 거리는 짧은 경우 정도가 생각이 나네요
이미 라이브러리에서 잘 해주는 기능 아니냐? 하고 생각하실 수 있는 데, 라이브러리를 교체하는 경우에는 그것을 보장 하지 못한다는 의미도 됩니다 😅 
따라서 어떤 알고리즘을 쓰는 것과는 무관하게 `Graph` 라는 객체의 역할에 대해 여러가지로 검증해보는 것이 필요한 것 같습니다 🔥

2022-08-02 03:37 UTC, merged