🚀 3단계 - 지하철 구간 제거 리팩터링
next-step/atdd-subway-path pull request #394
Opened 2022-07-29 18:47 UTC by rladowl92

안녕하세요~
지난 리뷰 대댓글까지 확인해서 반영했습니다.
3단계 미션 리뷰도 잘 부탁드립니다~!

### 기능 요구사항
- 위치에 상관 없이 역 삭제가 가능하도록 수정
- 종점이 제거될 경우 다음으로 오던 역이 종점이 됨
- 중간역이 제거될 경우 재배치
- 예외
  - 구간이 하나인 노선에서 마지막 구간을 제거할 수 없음
  - 노선에 등록되어있지 않은 역은 제거할 수 없음

2022-07-30 06:10 UTC, catsbi requested changes
애지님 3단계 지하철 구간 제거 리팩토링도 잘 구현해주셨어요 👏

테스트코드가 풍부하게 잘 작성된 것 같습니다 👍 
열거타입도 잘 활용해주셨어요. 다만 몇 가지 불필요한 주석이나, 열거 타입 사용법 관련해서 코멘트 드린 부분이 있으니확인해주시면 좋겠습니다!.  Request Change 할테니 확인 후 다시 리뷰요청 해주세요!

2022-07-30 06:10 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Sections.java
> +		// this.sections.remove(lastSection);
사용하지 않는 코드는 주석이 아니라 삭제해주세요!

2022-07-30 17:26 UTC, rladowl92 commented on src/main/java/nextstep/subway/applicaion/dto/LineRequest.java
> +public class LineRequest extends SectionRequest{
그러고보니 상속을 받아서 하위 개념이 되버리는군요?!
그런데 위임으로 하게될경우 LineRequest의 멤버변수가 바껴서 기존 Line 컨트롤러의 인터페이스도 변경되는데요ㅠ
중복을 줄이기위해 상속을 해봤는데 차라리 그냥 안하는게 나을까요?

2022-07-30 17:38 UTC, rladowl92 commented on src/main/java/nextstep/subway/domain/SectionAddPosition.java
> +			.filter(i-> sections.get(i).getDownStation().equals(section.getUpStation()))
안그래도 찝찝했는데 이런 방법이 있었군요?ㅎㅎ 👍

2022-07-30 18:56 UTC, rladowl92 commented on src/main/java/nextstep/subway/domain/SectionRemovePosition.java
> +	}
position을 찾는것도 functional interface를 추가해서 개선했습니다.

2022-07-31 03:19 UTC, catsbi commented on src/main/java/nextstep/subway/applicaion/dto/LineRequest.java
> +public class LineRequest extends SectionRequest{
어떤 방식으로 할지는 여러가지가 있다보니 어느걸 해야한다! 라고 말씀드릴순 없지만, 상속보다는 위임을 권장드리고,  DTO 객체가 기존 서비스나 도메인 계층에 영향을 준다는 것은 커플링이 발생했다는 것이기에 이 또한 문제가 됩니다. 
이런 경우 믹스인 인터페이스를 이용하거나, 아예 분리를 하시면 어떨까 생각해봅니다 혹은 DTO는 말 그대로 자료형일 뿐이기에 단순하게 생각해보셔도 좋을 것 같아요!

2022-07-31 03:27 UTC, catsbi approved these changes
애지님 피드백 잘 반영해주셨습니다. 👍 
아직 몇 가지 코멘트 드릴 내용이 남아있지만, 이 부분은 4단계 구현하시면서 충분히 하실 수 있는 부분이기에 머지하도록 하겠습니다. 4단계도 화이팅입니다!

2022-07-31 03:27 UTC, catsbi commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +		if (hasSection(request)) {
메서드 분리를 잘 해주셨네요 👍  다만 이름이 hasSection은 구간 정보가 있냐고 묻는건데, 이건 추가가 가능한지 물어보는 로직으로 보이는데 이름이 적절하진 않은 것 같네요 🤔

이정도로도 충분한데 여기서 한층 더 심화를 해보면, OOP 패러다임은 객체간의 요청/응답의 연속이고 서비스 계층은 이런 요청/응답을 오케스트레이션해주는 역할이죠. 직접적으로 로직을 작성하지 않아도 된다는 것이죠. 

이를 생각하면, 구간 추가가 가능한지에 대한 여부도 좀 더 적절한 객체에게 물어보고 응답받을 수 있습니다.

2022-07-31 03:27 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
👍 모든 객체는 최대한 문을 좁게 유지해야 관리가 편하고 문제로부터 자유로워질 수 있죠

2022-07-31 03:27 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Section.java
>  import javax.persistence.*;
import `*`을 잘 제거하는 방법으로는 푸시하기전에 reformat code작업을 돌려주는 것이죠!

2022-07-31 03:27 UTC, catsbi commented on src/main/java/nextstep/subway/domain/SectionAddPosition.java
> +			.orElse(MIDDLE);
훨씬 간결해졌네요 👍 

여기서 좀 더 복잡한 로직들이 추가된다고 하면, 열거타입이 너무 길어질 수 있습니다. 
이 경우엔 어떤 방법을 고려할 수 있을까요? 고민해볼만한 주제입니다 ㅎㅎ

2022-07-31 03:27 UTC, catsbi commented on src/main/java/nextstep/subway/domain/SectionAddPosition.java
> +	public interface FindPositionFunction {
FunctionalInterface를 이용한 Function의 인터페이스 정의는 정말 필요한 경우에만 하는게 좋습니다. 
이미 표준 함수형 인터페이스가 의미를 충분히 전달하고 있기 때문에, 별도의 함수형 인터페이스를 정의하는 것은, 오히려 의미를 퇴색하거나 다른 개발자의 협업을 어렵게 만들 수 있거든요. 

이펙티브 자바에서도 람다와 스트림 챕터에서 이 내용을 다루고 있는데, 제가 작성했던 포스팅이 있으니 참고해주세요 ㅎㅎ [람다와 스트림](https://catsbi.oopy.io/5861b4b5-60fa-4a6e-aadf-5caeafe68b1e#1c5758bd-11f4-41a6-8441-51c8b7fc92c5)

2022-07-31 03:27 UTC, merged

2022-07-31 17:12 UTC, rladowl92 commented on src/main/java/nextstep/subway/domain/Section.java
>  import javax.persistence.*;
푸시전 reformat code 옵션 꿀팁이네요! 👍 
intellij 설정으로 import *을 추가하지 않는 설정은 찾았는데 reformat으론 *이 제거되지 않네요, 혹시 다른 설정이 있을까요?

2022-08-01 02:09 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Section.java
>  import javax.persistence.*;
인텔리제이 기준으로 자바의 import부분에서 class count to use import with, names count to use static import with 등의 값을 999로 맞춰주시면 됩니다 ㅎㅎ
![image](https://user-images.githubusercontent.com/43158866/182058876-5d58a117-f44a-481a-8308-6640f473f1de.png)

2022-08-01 02:30 UTC, rladowl92 commented on src/main/java/nextstep/subway/domain/Section.java
>  import javax.persistence.*;
앗, 제가 찾았다는 설정이 요거에요 ㅎㅎ