Step1. 단위 테스트 작성
next-step/atdd-subway-path pull request #407
Opened 2022-07-31 07:26 UTC by nara1030

안녕하세요.
리뷰이 엄홍준이라고 합니다.

미션을 이해하기 어려워 다른 분 코드를 많이 참고하여 이해하고자 했습니다.
LineTest는 DB(영속성)와 관계없는 테스트이고, 나머지 2개는 DB(영속성)와 관계있으나 가짜 객체를 사용하는지에 따라 방법이 나뉜다고 이해했는데요. 제대로 이해한건지 궁금합니다.

만약 제가 생각한게 맞다면 LineTest의 addSection 메소드의 경우 DB와 상관 없이 자바 메모리에 구간을 추가하는 것이므로 ID를 포함한 생성자를 추가해주었습니다. 반면 서비스단 테스트(LineServiceTest)의 경우 노선 혹은 역 생성 시 ID를 제외하고 생성해주었고요. 어차피 DB, 즉 엔티티로 관리(save)가 되면 ID값이 자동적으로 추가될 거라는 생각을 했습니다.
확인해보기 위해 LineTest의 addSection 메소드를 다음과 같이 확인해보았는데요.

```java
private final Line 일호선 = new Line(LINE_ONE_NM, LINE_ONE_COLOR);
private final Station 신도림 = new Station(UP_STATION_NM_);
private final Station 가산디지털단지 = new Station(DOWN_STATION_NM);

@Test
void addSection() {
	// given
	System.out.println("신도림1: " + 신도림);
	
	Station _신도림 = stationRepository.save(신도림);
	Station _가산디지털단지 = stationRepository.save(가산디지털단지);
	
	System.out.println("신도림2: " + 신도림);
	System.out.println("신도림3: " + _신도림);

	Line _일호선 = lineRepository.save(일호선);
	
	// when
	SectionRequest sectionRequest = new SectionRequest(_신도림.getId(), _가산디지털단지.getId(), DISTANCE_DEFAULT);
	lineService.addSection(_일호선.getId(), sectionRequest);

	// then
	assertThat(_일호선.getSections()).hasSize(1);
}
```

실행 결과는 다음과 같습니다.

```txt
신도림1: Station{id=null, name='신도림'}
신도림2: Station{id=1, name='신도림'}
신도림3: Station{id=1, name='신도림'}
```

제가 의아한 것은 lineService.addSection 메소드의 첫 번째 인자로 _일호선.getId()를 넣어주었는데요. 이는 영속성 컨텍스트로 관리되는, 즉 ID가 생긴 것은 반환받은 `_신도림`이지 파라미터 `신도림`이 아니라고 생각했기 때문입니다. 하지만 `_신도림`뿐 아니라 `신도림` 또한 ID가 생성된 것을 볼 수 있었는데요. 이 두 인스턴스가 왜 같은건지 혹시 힌트를 주실 수 있으실지요?

감사합니다.

2022-07-31 10:48 UTC, junwoochoi requested changes
안녕하세요! 리뷰어 최준우라고 합니다 😃 

미션 진행해주신 부분 잘 확인했습니다!
몇가지 질문 주셨는데, 답변 드리겠습니다. 
1. LineTest는 도메인에 대한 테스트로 DB와는 관계가 없는 테스트가 맞습니다. 서비스에 대한 테스트의 경우 실제로 데이터베이스를 사용해서 테스트할 때와 가짜 객체를 테스트하는 방법으로 일반적으로 많이 나뉘는게 맞습니다. 잘 이해 하셨다고 생각됩니다.
2. 스프링 JPA의 `영속성 컨텍스트`에 대해 알아보시면 조금 더 도움이 될 것 같습니다ㅎㅎ

--- 
테스트가 깨지는 부분이 있어서 확인 후 수정 부탁드립니다 
추가로 코멘트 몇가지 달아봤는데 같이 확인해주세요 :)
감사합니다!! 
<img width="565" alt="image" src="https://user-images.githubusercontent.com/26688947/182022592-8ece8fa4-7ed2-4195-9ba5-1f7c0089789a.png">

2022-07-31 10:48 UTC, junwoochoi commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        line.addSection(upStation, downStation, sectionRequest.getDistance());
Line에게 구간추가의 책임 넘기신 부분이 좋습니다 :)

2022-07-31 10:48 UTC, junwoochoi commented on src/main/java/nextstep/subway/domain/Line.java
> +        if (sections.get(sections.size() - 1).getDownStation().getId() != stationId) {
Tell Don't Ask 원칙을 지키면서 작업해보면 더 좋을 것 같습니다 :)
https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=sorang226&logNo=221796702354

2022-07-31 10:48 UTC, junwoochoi commented on src/main/java/nextstep/subway/domain/Line.java
> +    public void addSection(Station upStation, Station downStation, int distance) {
https://tecoble.techcourse.co.kr/post/2020-05-08-First-Class-Collection/
일급컬렉션을 활용해보면 어떨까요?

2022-07-31 10:48 UTC, junwoochoi commented on src/test/java/nextstep/subway/unit/LineServiceMockTest.java
> +    @InjectMocks
@InjectMocks 활용 👍

2022-07-31 10:48 UTC, junwoochoi commented on src/test/java/nextstep/subway/unit/LineServiceTest.java
> +        assertThat(_일호선.getSections()).hasSize(1);
실제 객체를 활용한 테스트 👍

2022-07-31 10:48 UTC, junwoochoi commented on src/test/java/nextstep/subway/unit/LineServiceMockTest.java
> +        assertThat(일호선.getSections()).hasSize(1);
Stubbing을 통한 테스트 💯

2022-07-31 10:48 UTC, junwoochoi commented on src/test/java/nextstep/subway/unit/LineTest.java
> +    private final Station 독산 = new Station(THREE_ID, ADDITIONAL_STATION_NM);
Line 객체의 실제 객체를 테스트하기 위해 ID를 함께 추가할 수 있는 생성자를 만들어주셨군요. 
저 같은 경우는 스프링에서 제공하는 ReflectionTestUtils의 setField를 활용해서 ID를 추가하는 방법도 자주 사용하고 있는데, 프로덕션 코드에 테스트코드를 위한  생성자를 안만들어도 되서 좋더라구요 :)

2022-07-31 10:48 UTC, junwoochoi commented on src/test/java/nextstep/subway/unit/LineTest.java
> +        assertThat(일호선.getSections()).hasSize(1);
단위테스트 잘작성해주셨습니다!! 추가적으로 실패하는 경우에 대한 테스트도 작성해보면 더 좋을 것 같네요 👍

2022-08-01 02:22 UTC, nara1030 commented
준우님 안녕하세요.
빠르고 상세한 피드백 감사드립니다.
전부 다 확실하게 이해하진 못했으나, 기억해두고 공부해보겠습니다.
말씀해주신 부분에 대해서 몇 가지 수정/추가하였습니다.

1. 구간 삭제 실패 단위케이스를 추가하였습니다.

Line의 removeSection(Long stationId)에 대한 예외 케이스 테스트가 보완되어 메소드가 좀 더 확실?해진 거 같습니다.
2. Tell Don't Ask

Line의 removeSection(Long stationId) 관련하여서 아래와 같이 코드를 수정하였습니다.

```java
// 기존
if (sections.get(sections.size() - 1).getDownStation().getId() != stationId) {
	throw new IllegalArgumentException();
}

// 변경
if (!getLastStation().compare(stationId)) {
	throw new IllegalArgumentException();
}
```

Station 객체에서 id값을 비교해주는 메소드인 compare를 추가해주었는데요. getter 느낌이 나서 말씀해주신대로 수정한건지 모르겠습니다.

감사합니다.

2022-08-01 11:29 UTC, junwoochoi approved these changes
안녕하세요! 
피드백 적용해주신 부분 잘 확인했습니다 😄 
앞으로 남은 미션도 잘부탁드리겠습니다! 
미션 이어서 진행해주세요~ 🔥

2022-08-01 11:29 UTC, junwoochoi commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +            line.addSection(upStation, downStation, request.getDistance());
👍

2022-08-01 11:29 UTC, junwoochoi commented on src/main/java/nextstep/subway/domain/Line.java
> +        if (!getLastStation().compare(stationId)) {
👍

2022-08-01 11:29 UTC, junwoochoi commented on src/main/java/nextstep/subway/domain/Line.java
> +    private Sections sections = new Sections();
피드백 적용 💯

2022-08-01 11:29 UTC, junwoochoi commented on src/test/java/nextstep/subway/unit/LineTest.java
> +        });
👍 👍

2022-08-01 11:29 UTC, merged