[Step3] 리뷰 요청드립니다~
next-step/atdd-subway-path pull request #415
Opened 2022-08-01 15:20 UTC by exemeedys

2022-08-02 09:10 UTC, starkim06 requested changes
안녕하세요!!

엄청 빠르게 3단계도 완료해주셨네요!!
간단한 코멘트 몇가지 남겨두었으니 확인 부탁드려요 =)

2022-08-02 09:10 UTC, starkim06 commented on src/test/java/nextstep/subway/unit/LineServiceMockTest.java
> +    @DisplayName("지하철 노선의 상행 구간 제거하기")
시나리오 테스트에서는 상행 구간을 `상행 종점 구간`이라고 표현을해주셨던것 같아요! 
용어가 통일되면 어떨까요?

2022-08-02 09:10 UTC, starkim06 commented on src/main/java/nextstep/subway/domain/Sections.java
> +            topSection = nextSection;
이 부분에서는 별도의 변수를 사용해주셔도 좋을것 같아요.
TopSection은 제일 첫 구간을 의미하는 변수명으로 사용되다가 while문에서는 다시 다른 의미로 사용돼서 이해하기가 조금 힘든것 같아요!

2022-08-02 09:10 UTC, starkim06 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        return this.sections.stream().filter(s -> s.upStationMatchFromDownStation(station)).findFirst()
개인에 취향에 가까운 부분이지만 저는 stream() 이후에 체이닝은 줄바꿈을 해주는것도 가독성에 도움이 된다고 생각해요!

2022-08-02 11:56 UTC, exemeedys commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +    @DisplayName("지하철 노선에 상행 종점을 제거")
넵!

2022-08-02 11:56 UTC, exemeedys commented on src/main/java/nextstep/subway/domain/Distance.java
> +        return new Distance(this.value - otherDistance.getValue());
넵!

2022-08-02 11:56 UTC, exemeedys commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +     * When 지하철의 노선에 구간 제거 요청하면
넵!

2022-08-02 11:57 UTC, exemeedys commented on src/test/java/nextstep/subway/unit/LineServiceMockTest.java
> +    @DisplayName("지하철 노선의 상행 구간 제거하기")
넵!

2022-08-02 11:57 UTC, exemeedys commented on src/main/java/nextstep/subway/domain/Sections.java
> +            topSection = nextSection;
넵!

2022-08-02 11:57 UTC, exemeedys commented on src/main/java/nextstep/subway/domain/Sections.java
> +        return this.sections.stream().filter(s -> s.upStationMatchFromDownStation(station)).findFirst()
넵! 저도 그게 가독성이 좋다고 생각됩니다!

2022-08-03 07:50 UTC, starkim06 approved these changes
안녕하세요!! 

리팩토링 엄청 꼼꼼하게 잘 해주셨네요!!!
코멘트 드린 부분뿐만 아니라 관련된 다른 부분들까지 너무 잘해주신것 같아요!!!!

다음 단계 진행 부탁드립니다!!!

2022-08-03 07:50 UTC, merged