Step2
next-step/atdd-subway-path pull request #419
Opened 2022-08-03 02:20 UTC by JangHyeonJun2

안녕하세요! 성현님! 
2단계 요청드립니다! getSection()에서 조금 많이 해맸네요.🥲

2022-08-04 03:54 UTC, boorownie requested changes
2단계 기능 구현 요구사항 잘 수행해주셨습니다 👍 
한가지 아쉬운점이 있다면 단위 테스트가 많이 보이지 않는데
새로 추가된 스펙에 대한 단위 테스트를 추가해보면서 다른 피드백도 반영해보시면 좋을 것 같습니다!

2022-08-04 03:54 UTC, boorownie commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +        });
메서드로 분리하여 메서드 이름으로 스텝의 의도를 조금 더 잘 드러내보면 어떨까요?
다른 인수 테스트에도 위와 같은 기준으로 리팩터링해보세요~

2022-08-04 03:54 UTC, boorownie commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
>  @DisplayName("지하철 구간 관리 기능")
꼼꼼한 인수 테스트 👍

2022-08-04 03:54 UTC, boorownie commented on src/main/java/nextstep/subway/domain/Sections.java
> +            checkExistsNotContainStation(newSection);
Early Return을 통해 코드의 뎁스를 줄여보면 어떨까요?

2022-08-04 03:54 UTC, boorownie commented on src/main/java/nextstep/subway/domain/Sections.java
> +//        sectionsSortList.addAll(sectionsSortList.stream().takeWhile(section -> Objects.nonNull(getNextSection(section))).collect(Collectors.toList()));
사용하지 않는 코드는 주석으로 관리하기 보다는 제거하는 것을 추천드립니다 :)

2022-08-04 03:54 UTC, boorownie commented on src/main/java/nextstep/subway/domain/Sections.java
> +        List<Section> sectionsSortList = new ArrayList<>();
변수 네이밍에 자료형이 포함되는경우 자료형이 변경될 때 마다 리팩터링이 필요하게 됩니다.
물론 변경될 일이 거의 없을 수 있지만 이 경우에도 네이밍에서 자료형을 사용하지 않는것을 추천드립니다 :)

2022-08-04 03:54 UTC, boorownie commented on src/main/java/nextstep/subway/domain/Sections.java
>      public Sections() {
인수 테스트 이후 TDD로 기능구현을 한다면
단위 테스트들도 많이 보여야 하는데 많이 보이질 않네요ㅠㅠ
노선 혹은 구간에 대한 단위 테스트를 작성해보면 어떨까요?

2022-08-04 11:12 UTC, JangHyeonJun2 commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +        });
테스트관련 메서드를 만들어서 사용하라는 말씀일까요?

2022-08-04 11:13 UTC, JangHyeonJun2 commented on src/main/java/nextstep/subway/domain/Sections.java
> +            checkExistsNotContainStation(newSection);
넵! 확인해보겠습니다!

2022-08-04 11:13 UTC, JangHyeonJun2 commented on src/main/java/nextstep/subway/domain/Sections.java
> +//        sectionsSortList.addAll(sectionsSortList.stream().takeWhile(section -> Objects.nonNull(getNextSection(section))).collect(Collectors.toList()));
아 ㅠㅠ 주석을 삭제하는걸 놓쳤네요.

2022-08-04 11:15 UTC, JangHyeonJun2 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        List<Section> sectionsSortList = new ArrayList<>();
그렇다면 sectionsSorts 처럼 작성하는 것으로 이해하면 될까요?

2022-08-04 11:15 UTC, JangHyeonJun2 commented on src/main/java/nextstep/subway/domain/Sections.java
>      public Sections() {
TDD가 조금 익숙하지 않았는데! 조금 더 해보겠습니다.

2022-08-07 17:03 UTC, boorownie commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +        });
네네 맞습니다 :)

2022-08-07 17:06 UTC, boorownie approved these changes
피드백 반영 확인했습니다!
전반적으로 테스트 가독성이 좋아진 것 같네요 :)
이어서 3단계 미션 진행해주세요~

2022-08-07 17:06 UTC, boorownie commented on src/test/java/nextstep/subway/unit/LineTest.java
> +    void addSectionBetweenSection() {
구간에 대한 단위 테스트 추가 👍

2022-08-07 17:06 UTC, boorownie commented on src/main/java/nextstep/subway/domain/Sections.java
> +        List<Section> sortSections = new ArrayList<>();
네이밍 변경 확인 👍

2022-08-07 17:06 UTC, boorownie commented on src/main/java/nextstep/subway/domain/Sections.java
>      public void add(Section newSection) {
메서드의 뎁스가 줄어들었네요 👍

2022-08-07 17:06 UTC, merged