Step00 실습 단위테스트 작성
next-step/atdd-subway-path pull request #440
Opened 2023-02-04 13:23 UTC by hiblue02

리뷰 요청드립니다!

2023-02-05 08:31 UTC, catsbi requested changes
혜영님 반갑습니다. 2주차 미션을 함께 하게 된 이한솔이라고 합니다 👍 
미션 진행 기간 동안 서로 인사이트를 많이 얻을 수 있는 시간이면 좋겠습니다 😀

첫 번째 단위 테스트 작성 미션 잘 구현해주셨습니다. 
피드백 드린 부분들이 몇 있긴한데, 피드백 반영 후 다시 요청해주시면 좋을 것 같습니다!

2023-02-05 08:31 UTC, catsbi commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +    private final StationService stationService;
👍

2023-02-05 08:31 UTC, catsbi commented on README.md
> +  - 구간 관리에 대한 책임을 Line 외 별도의 도메인 객체가 가지게 할 수 있음
Todo를 작성했다면 완료 후 체크해주면 좋을 것 같아요 👍

2023-02-05 08:31 UTC, catsbi commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        List<Station> stations = line.getAllStations();
전철역목록도 일급 컬렉션으로 해보면 어떨까요?

2023-02-05 08:31 UTC, catsbi commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        line.addSections(new Section(line, upStation, downStation, sectionRequest.getDistance()));
생성자 파라미터의 갯수가 4개가 넘어가고 동일한 타입의 파라미터가 연달아 있는 경우 휴먼 에러의 가능성이 높아지기에 빌더패턴도 고려해볼 수 있습니다.(Optional Comment)

2023-02-05 08:31 UTC, catsbi commented on src/main/java/nextstep/subway/applicaion/dto/SectionRequest.java
> +    }
DTO라도 setter는 최소화 해주는게 좋습니다. 최초 생성 이후 DTO도 의미없이 변경되는게 없는 불변에 가까워지는게 프로젝트의 안전성을 높힐 수 있습니다 👍

2023-02-05 08:31 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
> +        }
매직 리터럴을 분리해주면 차후 유지보수에서 이점을 가져갈 수 있지 않을까요?

2023-02-05 08:31 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Sections.java
> +        return Collections.unmodifiableList(stations);
불변성 확보 💯

2023-02-05 08:31 UTC, catsbi commented on src/test/java/nextstep/subway/unit/LineServiceMockTest.java
> +        Line line = lineRepository.findById(이호선).orElseThrow();
mock으로 행위 스터빙이 된 로직을 그대로 호출하는게 테스트 의미가 있을까요?

2023-02-05 08:31 UTC, catsbi commented on src/test/java/nextstep/subway/unit/LineServiceMockTest.java
> +        when(stationService.findById(역삼역)).thenReturn(new Station("역삼역"));
mock으로 스터빙하고 있는 작업들이 중복된게 보입니다. 중복 제거를 해보는게 어떨까요?

2023-02-05 08:31 UTC, catsbi commented on src/test/java/nextstep/subway/unit/LineServiceTest.java
>  public class LineServiceTest {
전체적으로 실패테스트는 없는 것 같네요 😥

2023-02-05 08:31 UTC, catsbi commented on src/test/java/nextstep/subway/unit/LineTest.java
> +import static org.assertj.core.api.Assertions.*;
import 구문은 '*' 사용을 지양하는게 좋습니다. 왜그럴까요?

2023-02-06 14:06 UTC, hiblue02 commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        List<Station> stations = line.getAllStations();
전철역 목록은 output만 있는 거라,, 일급컬렉션으로 정의하지 않아도 괜찮을 것 같습니닷 :)

2023-02-06 14:09 UTC, hiblue02 commented on src/test/java/nextstep/subway/unit/LineServiceTest.java
>  public class LineServiceTest {
LineTest에서 실패테스트를 검증하기 때문에, Service에서도 같은 내용을 검증할 필요는 없다고 생각했습니다.

2023-02-07 05:17 UTC, catsbi approved these changes
혜영님 피드백 반영 잘 해주셨네요 💯 
다 잘 작성해주셔서 바로 다음 미션으로 넘어가시죠. 머지하겠습니다 !

2023-02-07 16:17 UTC, merged