1단계 - 지하철역 인수 테스트 작성
next-step/atdd-subway-path pull request #445
Opened 2023-02-07 14:56 UTC by JungTag

안녕하세요! 이번 미션을 함께 하게 된 윤영택이라고 합니다.
부족한 점이 많지만 열심히 하겠습니다. 잘 부탁드립니다!

Q)
1. `LineServiceMockTest`의 44번째 줄에 line.findLineById 메서드를 통해 검증하라고 나오는데, 이 부분이 이해가 잘 가지 않습니다..!! 도메인 객체가 find 메서드를 가지는 경우는 처음 봐서요..ㅠ
2. 단위테스트 환경(비영속 상태)에서 비교를 위해 `Statio`n의 equals를 재정의했고, 식별 가능한 값으로 사용될 수 있는 name을 이용했는데 요렇게 해도 괜찮을까요?

2023-02-08 22:10 UTC, catsbi requested changes
안녕하세요 영택님 2주차 미션을 함께 하게 된 이한솔이라고 합니다. 

1단계 지하철 구간 추가 기능 개선 미션 잘 구현해주셨습니다. 

메서드 분리나, 적절한 표준 예외 사용 다 잘해주셨고, 테스트도 꼼꼼하게 잘 작성해주셨어요.
여기에 더 고민해보면 좋을 피드백 몇 가지 남겨드렸으니 확인 후 다시 리뷰요청 해주세요!

질문 주신 내용에 대해서는 코멘트로 남겼습니다!

2023-02-08 22:10 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
> +        return this.sections.stream()
모든 구간정보에 대해서 List를 새로 만들고 이를 flatmap으로 다시 풀어서 하나로 합쳐서 List를 만드는건, 공간복잡도가 너무 높아지는게 아닐까 생각이 듭니다. Stream API를 써서 깔끔해보이는 것도 좋지만, 좀 더 나은 방법은 없을까요?

2023-02-08 22:10 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
> +        }
- 명확한 종료 조건이 적혀있지 않은 무한 반복문은 위험해서 사용이 지양되는 부분입니다 ㅎ 
- 코드의 depth가 2를 넘어가는데 더 줄일 수 없을까요?

2023-02-08 22:10 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
>  public class Line {
구간정보가 지금 Line 엔티티에서 모두 관리되고 비즈니스 로직도 작성되고 있습니다. 일급 컬렉션을 사용해볼 수 없을까요?

2023-02-08 22:10 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Station.java
> +        if (o == null || getClass() != o.getClass()) return false;
1줄짜리 분기문도 블럭 `{}` 생략은 지양해주세요. 전체적인 가독성 저하문제도 있고
코드의 일관성도 깨집니다. IDE에 의해 자동생성된 코드도 논외의 영역은 아닙니다 🤔

2023-02-08 22:10 UTC, catsbi commented on src/test/java/nextstep/subway/unit/LineTest.java
> +        line.addSection(new Station("상행역"), new Station("중간역"), 6);
테스트 픽스쳐가 중복된걸 직접 하나하나 작성하다보면 휴먼에러가 생길 수 있을 것 같은데, 분리해서 재사용성을 높혀보는건 어떨까요?

2023-02-08 22:10 UTC, catsbi commented on src/test/java/nextstep/subway/unit/LineTest.java
> +            .hasMessage("역 사이에 기존 역 사이 길이보다 크거나 같은 구간을 등록할 수 없습니다.");
프로덕션 코드에서 해당 메세지가 변경될 경우 테스트가 깨질 문제가 있습니다. 
해당 메세지가 상수로 관리되고 있다면, 변경에도 유연할 수 있지 않을까요?

2023-02-09 13:37 UTC, JungTag commented
@catsbi 님 안녕하세요!! 너무나도 상세하게 리뷰해주신 덕에 술술 수정할 수 있었습니다. 정말정말 감사드립니다 큰 도움이 되었어요 :)

2023-02-10 12:14 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
>      public List<Station> getOrderedStations() {
지하철역 정보 역시 구간정보 일급 컬렉션에서 다루기에 여기보단 해당 도메인에서 다루는게 더 적절해보이네요 🤔

2023-02-10 12:14 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
> +    private static class EndStations {
해당 정적 중첩 클래스가 필요할까요? 
Section 도메인에 상행/하행역이 모두 있는데  노선 전체에 대한 상행역과 하행역정보를 따로 다루는건 지나친 비용이지 않을까 생각이 듭니다. 

그리고 객체명은 EndStation인데 내부 값은 상행 종점역, 하행 종점역이라는 정보를 다루기엔 의미가 그냥 마지막 지하철역으로 보이네요. 그리고 아예 별도의 객체이기 때문에 기존 Station과 어떤 연관성도 없어서 차후 유지보수 측면에서도 사실상 종속성이 생겨서 문제가 될 수 있습니다. 

객체로 분리하여 로직이나 책임의 분리를 시도한건 좋았지만, 해당 경우에는 오버엔지니어링으로 보이네요 😅

2023-02-10 12:14 UTC, catsbi commented on src/main/java/nextstep/subway/domain/LineSection.java
> +    private Section findSameUpStation(Station upStation) {
메서드가 null을 반환한다면 이 메서드를 사용하는 모든 클라이언트에서는 null check가 필수적으로 바뀌게 됩니다. 이를 더 안전하게 바꿀 수 없을까요?

2023-02-10 12:14 UTC, catsbi commented on src/main/java/nextstep/subway/domain/LineSection.java
> +public class LineSection {
일급 컬렉션은 복수의 데이터를 핸들링하는 도메인일텐데 노선 구간이라는 이름보다는 복수형의 이름을 다루는게 더 낫지 않을까요? (ex: Sections)

2023-02-10 12:14 UTC, catsbi commented on src/main/java/nextstep/subway/domain/LineSection.java
> +        return stations;
stream()을 호출해 Stream을 만드는 것 보다는 해당 sections 컬렉션이 차있는지 비어있는지만 확인하면 되지 않을까요?

2023-02-10 12:14 UTC, catsbi commented on src/main/java/nextstep/subway/domain/LineSection.java
> +    }
반환타입이 boolean인 (논리값) 메서드는 보통 접두사로, exists, is, has와 같은 네이밍을 붙혀주면 호출하는 클라이언트의 가독성이 높아질 수 있습니다 👍

2023-02-10 12:14 UTC, catsbi commented on src/test/java/nextstep/subway/unit/LineTest.java
> +    }
메서드로 픽스쳐를 만들기보다는 다음과 같이 변수를 필드초기화 혹은 beforeEach 애노테이션을 활용한 테스트 시점 초기화를 해주는건 어떨까요? 

```java
private Station 상행역;
private Station 하행역;
private Station 중앙역;

@beforeEach
public void setUp()
```

2023-02-10 12:15 UTC, catsbi approved these changes
영택님 피드백 반영 잘해주셨습니다 👍 

몇 가지 피드백이 필요한부분들이 생겨서 코멘트 남겨드렸으니 확인해주시고, 
다음 미션 진행하시면서 같이 반영해보는걸로 하죠 수고하셨습니다!

2023-02-11 07:44 UTC, merged

2023-02-11 15:07 UTC, JungTag commented on src/main/java/nextstep/subway/domain/LineSection.java
> +    }
보통 exists는 접미사로 많이 쓰지 않나요?!

2023-02-12 07:30 UTC, catsbi commented on src/main/java/nextstep/subway/domain/LineSection.java
> +    }
is, has, was, exists와 같은 키워드뿐 아니라 get, set등과 같이 행위 혹은 결과값을 유추할 수 있는  키워드를 접두사로 보통 많이 사용하는편입니다 ㅎㅎ