🚀 2단계 - 지하철 구간 제거 기능 개선
next-step/atdd-subway-path pull request #460
Opened 2023-02-10 16:04 UTC by seovalue

안녕하세요~ 2단계 미션 제출해요. 잘부탁드려요!

2023-02-11 23:22 UTC, testrace requested changes
안녕하세요 민정님 😄 
2단계 미션도 잘 구현해 주셨네요 👍 
몇 가지 코멘트 남겨두었는데 확인 후 다시 리뷰 요청 부탁드립니다!
궁금한 점이나 의견 있으시면 편하게 DM 주세요!

2023-02-11 23:22 UTC, testrace commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private static final int MIN_SECTION_SIZE_OF_LINE = 1;
클래스 변수는 상단에 작성하면 어떨까요?

```java
class  T {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    팩토리 메소드
    메소드
    기본 메소드 (equals, hashCode, toString)
}
```

2023-02-11 23:22 UTC, testrace commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
이 로직도 생성자를 활용해도 좋을 것 같아요!

2023-02-11 23:22 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +     */
개발자가 아닌 경우 400 응답이 무엇을 뜻하는지 알기 어려울 것 같아요
개발자가 아니더라도 쉽게 파악할 수 있는 인수 조건을 도출하면 어떨까요?

2023-02-11 23:22 UTC, testrace commented on src/test/java/nextstep/subway/domain/LineTest.java
> +        var stations = line.getAllStations().stream().map(Station::getName).collect(Collectors.toList());
피드백 반영 👍

2023-02-11 23:22 UTC, testrace commented on src/test/java/nextstep/subway/domain/SectionsTest.java
> +class SectionsTest {
단위 테스트를 꼼꼼하게 잘 작성해 주셨네요 👍

2023-02-12 12:37 UTC, seovalue commented on README.md
> +  - [ ] 노선에 등록되어있지 않은 역을 제거할 수 없음.
헉! 감사합니다

2023-02-12 12:41 UTC, seovalue commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
피드백 보고 반영하려 했는데, 새로운 섹션을 만들어줄때마다 exisitingSection에서 넣어주는 값이 매번 달라서 공통된 부분이라고 생각하지 않았던 것 같아요ㅎㅎ 크로스로 new Section을 해주려면 어떤 식으로 하면 깔끔하게 할 수 있을까요?

2023-02-12 12:46 UTC, seovalue commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
안녕하세요~ 이해가 잘 안되어서요. 
우선 저 부분을 Set으로 고친다고 했을 때 어떤 장점이 있는건지 궁금해요. 각 상행역과 하행역을 이어가며 처음부터 끝까지 나열하는건데, Set이 어떤 부분을 해결해줄 수 있는건지 궁금합니다.

그리고 stream 또한 마찬가지예요! 스트림이라는 건 기존에 존재하는 컬렉션을 스트림형태로 열어 원하는 대로 값을 변환한뒤 결과값을 만드는 것이라고 생각하는데, 위와 같은 경우를 어떻게 해결할 수 있는건지 궁금합니다.

용주님께서 생각하시는 예시를 남겨주시면 참고해볼게요.

2023-02-12 12:49 UTC, seovalue commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
노선 생성 요청에도 upStationId 및 downStationId 가 포함되어있는 걸 보면 노선은 반드시 1개의 구간을 가진다고 가정해도 될 것 같습니다!

2023-02-12 12:56 UTC, seovalue commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
우선은 하위호환때문에 빈 케이스도 대응 해두고, Sections 생성자에서 빈 케이스 검증도 추가할게요!

2023-02-12 13:02 UTC, seovalue commented
안녕하세요, 바쁘신데 피드백 해주셔서 감사합니다.
남겨주신 피드백 중 이해가 잘 안되는 부분은 코멘트로 질문 남겨뒀어요. 제가 코드를 짠 상태에서 편향되게 바라보다보니 잘 떠오르지 않는 것 같아요. 두 번이나 남겨주신 코멘트들이니 예시를 함께 남겨주시면 저도 이해하는데 더 편할 것 같아요. 🙏  
그리고 노선은 최소 한개의 구간을 가진다는 것도, 충분히 이해되는데 기존에 짜여있던 모든 테스트를 리팩터링하기보다는 하위호환을 위해ㅠㅠ Sections 생성자에서 empty 케이스 검증을 추가해서 한 개의 구간이 함께 생성될 때에도 검증될 수 있도록만 추가해보았습니다.

2023-02-13 07:19 UTC, testrace commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
sections 필드의 타입이 ArrayList이니 이미 순서가 보장되어 있어서 순서대로 Set에 Station 들을 Set 자료구조에 넣게 된다면 
자연스럽게 중복제거와 순서보장이 될 것 같아요
Set 을 활용했을 때의 장점은 코드를 이해하는데 비용이 줄일 수 있을 것 같아요
```java
        Set<Station> stations = new LinkedHashSet<>();
        for (Section section : sections) {
            stations.add(section.getUpStation());
            stations.add(section.getDownStation());
        }

        return new ArrayList<>(stations);
```

stream 또한 가독성을 위해 사용해도 좋을 것 같아서 의견을 드렸습니다 😃 
```java
        return sections.stream()
            .flatMap(section -> Stream.of(section.getUpStation(), section.getDownStation()))
            .distinct()
            .collect(Collectors.toList());
```

2023-02-13 08:59 UTC, testrace commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
제가 조금 착각해서 코멘트를 드린 것 같아요 😅 
이 코멘트는 넘어가주셔도 좋습니다!
(Set이나 Stream을 활용하려면 반드시 역이 순서대로 저장이 되어 있어야겠네요! Sections를 조회할 때 미리 정렬을 해두는 것도 좋을 것 같습니다)

2023-02-13 10:13 UTC, testrace approved these changes
안녕하세요 민정님 😃 
피드백 반영 잘해주셨네요 👍 
코멘트로 남겨주신 질문에 답변 남겨놓았습니다
다음 단계 진행하시면서 확인 부탁드립니다!

2023-02-13 10:14 UTC, merged

2023-02-13 11:00 UTC, seovalue commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
감사합니다!