1단계 - 지하철 구간 추가 기능 개선
next-step/atdd-subway-path pull request #465
Opened 2023-02-11 13:13 UTC by ess234

0단계, 1단계 함께 진행했습니당 :)
PR 확인 부탁드립니당 🙇‍♀️

2023-02-12 01:53 UTC, catsbi requested changes
안녕하세요. 진윤님 2주차 과정을 함께 하게 된 이한솔이라고 합니다. 
과정 진행 동안 서로 인사이트를 얻는 시간이면 좋겠습니다 👍 

1주차 미션 잘 구현해주셨는데, 피드백 필요한부분들이 있어 코멘트 남겨드렸으니, 
확인 후 다시 리뷰요청해주세요!

2023-02-12 01:53 UTC, catsbi commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +    public void addSection(AddTypeEnum addTypeEnum, Long lineId, SectionRequest sectionRequest) {
매개변수를 2개 이하로 유지할 순 없을까요?

2023-02-12 01:53 UTC, catsbi commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        line.addSection(addTypeEnum, new Section(line, upStation, downStation, sectionRequest.getDistance()));
구간 객체는 4개 이상의 매개변수를 가지면서 동일한 타입의 매개변수를 연달아 받는 생성자를 가지고 있습니다. 
이 경우 상행역, 하행역이 휴먼에러로 잘못 기입되어 잘못된 객체가 생길 문제도 있죠. 

이 경우 빌더패턴을 고려해볼 수 있을 것 같은데 어떨까요?

2023-02-12 01:53 UTC, catsbi commented on src/main/java/nextstep/subway/applicaion/LineService.java
>      private LineResponse createLineResponse(Line line) {
Response 객체의 생성책임을 Service Layer에서 가지는게 적절할까요? 좀 더 적절한 위치가 있지 않을까요?

2023-02-12 01:53 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
>  public class Line {
구간정보에 대한 모든 책임을 노선에서 담당하고 있는데, 적절한 책임 분배일까요? 
노선 엔티티에서는 노선에 대해서만 다루는게 좋지 않을까요? 

Section에 관련된 기능은 Section이 담당하도록 하는게 어떨까요? 
그리고 sections라는 컬렉션은 일급 컬렉션으로 만들어서 책임을 분리할 수 있을 것 같아요 👍

2023-02-12 01:53 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
> +            Section standardSection = this.getSections().stream().filter(a -> section.getDownStation().equals(a.getUpStation())).findFirst().orElseThrow(IllegalArgumentException::new);
Stream API는 반환타입이 Stream 이기 때문에 디미터 법칙 대상이 되지 않아 dot(.)을 개행을 하지 않아도 되지만, 
가독성부분에서 적절한 개행으로 행위를 분리하여 가독성을 높힐 수 있습니다.

2023-02-12 01:53 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
> +            this.getSections().add(this.getSections().indexOf(standardSection), section);
getter로 객체를 꺼낸 뒤 그 값을 직접 연산에 사용하는건 내부 값을 추상화 한 의미가 없어지게 합니다. 
적절한 객체에게 요청하고 응답받는 식으로 하는 OOP 패러다임을 더 활용해보면 어떨까요?

2023-02-12 01:53 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
> +        if (MIDDLE_ADD_SECTION.equals(addTypeEnum)) {
이렇게 플래그를 사용하는 로직은 플래그가 늘어남에 따라 코드 수정이 생길 수 밖에 없고 하나의 메서드의 길이가 계속해서 길어지는 문제가 있습니다. 로직을 더 추상화해서 로직을 더 간결하게 바꿀 순 없을까요?

2023-02-12 01:53 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
> +    public List<Station> getStations() {
이 메서드 역시 노선보다는 구간정보에서 가져가면 좋을 책임으로 보이네요 ㅎㅎ

2023-02-12 01:53 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Station.java
> +        if (this == o) return true;
분기문은 한 줄짜리라도 블럭`{}` 생략은 지양해주세요. 코드의 가독성 및 일관성이 깨질 수 있습니다. 

IDE에 의해 자동생성된 코드도 예외는 아닙니다

2023-02-12 01:53 UTC, catsbi commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +import static nextstep.subway.common.AddTypeEnum.*;
import  구문에 `*` 사용을 지양하는게 좋습니다. 왜일까요?

2023-02-12 01:53 UTC, catsbi commented on src/test/java/nextstep/subway/unit/LineServiceMockTest.java
> +        when(stationService.findById(any())).thenReturn(new Station("지하철역1")).thenReturn(new Station("지하철역2"));
service 테스트에서 service 스터빙을 해버리면 서비스계층의 내부로직은 수행되지 않고 바로 약속된 값만 반환을 하게 될텐데 그럼 테스트의 의미가 사라지지 않을까요?

2023-02-12 01:53 UTC, catsbi commented on src/test/java/nextstep/subway/unit/LineTest.java
> +        Line line = 지하철노선_생성_기존구간_추가("지하철역1", "지하철역3", 5);
직접 하드코딩한 매직리터럴과 매직넘버가 보이는데 이를 분리해서 재활용 가능하게 할 수 없을까요?

2023-02-12 01:53 UTC, catsbi commented on src/test/java/nextstep/subway/unit/LineTest.java
> +        Section section = createSection(line, upStationName, downStationName, distance);
보통 메서드의 나열은 신문처럼 위에서 아래로 내려가듯이 읽게 해주는게 가독성에 좋습니다. ㅎ

2023-02-12 08:18 UTC, ess234 commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        line.addSection(addTypeEnum, new Section(line, upStation, downStation, sectionRequest.getDistance()));
빌더패턴 적용 후 기존에 있던 all Argument 생성자는 유지하나요 ?? 
로직 상으론 안 쓸거라 제거하는게 맞을 것 같은데 JPA 설정 때문에 유지해야 되는건지 궁금합니당 

기존 생성자 삭제하면 아래 화면처럼 에러가 발생합니다. 🤔
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/25348139/218300339-7eb295a8-c33d-4208-ac42-bcf06734bb22.png">

2023-02-12 08:19 UTC, ess234 commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +    public void addSection(AddTypeEnum addTypeEnum, Long lineId, SectionRequest sectionRequest) {
넵 수정해보겠습니당 :)

2023-02-12 08:19 UTC, ess234 commented on src/main/java/nextstep/subway/domain/Line.java
>  public class Line {
넵 수정했습니당 :)

2023-02-12 11:28 UTC, ess234 commented on src/main/java/nextstep/subway/applicaion/LineService.java
>      private LineResponse createLineResponse(Line line) {
어떤 부분을 개선해야 되는건지 잘 모르겠는데 추가 설명 가능할까요 ?? 
응답값을 리턴하는 메서드가 아니여서요 ;; ㅠㅠ 
<img width="499" alt="image" src="https://user-images.githubusercontent.com/25348139/218308308-50520f9e-2af9-4803-9af3-5cc2449ff525.png">

2023-02-12 11:29 UTC, ess234 commented on src/main/java/nextstep/subway/domain/Line.java
> +            Section standardSection = this.getSections().stream().filter(a -> section.getDownStation().equals(a.getUpStation())).findFirst().orElseThrow(IllegalArgumentException::new);
수정했습니당

2023-02-12 12:18 UTC, ess234 commented on src/main/java/nextstep/subway/domain/Line.java
> +            this.getSections().add(this.getSections().indexOf(standardSection), section);
수정했습니당

2023-02-12 12:21 UTC, ess234 commented on src/main/java/nextstep/subway/domain/Line.java
> +        if (MIDDLE_ADD_SECTION.equals(addTypeEnum)) {
플래그 별 별도 메소드로 분리했는데 의도하신 내용이랑 맞는지 확인 부탁드립니당

2023-02-12 12:22 UTC, ess234 commented on src/main/java/nextstep/subway/domain/Line.java
> +    public List<Station> getStations() {
Sections 일급컬렉션 쪽으로 로직 이동했습니당

2023-02-12 12:23 UTC, ess234 commented on src/main/java/nextstep/subway/domain/Station.java
> +        if (this == o) return true;
자동이라 몰랐는데 수정했습니당

2023-02-12 12:30 UTC, ess234 commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +import static nextstep.subway.common.AddTypeEnum.*;
사용하지 않는 클래스까지 컴파일됨으로 컴파일 수행시간이 길어질 수 있는걸로 알고 있습니당! 
인텔리제이 설정 변경으로 자동으로 import 와일드로 변경되지 않도록 했습니다:)

2023-02-12 13:15 UTC, ess234 commented on src/test/java/nextstep/subway/unit/LineServiceMockTest.java
> +        when(stationService.findById(any())).thenReturn(new Station("지하철역1")).thenReturn(new Station("지하철역2"));
테스트는 lineservice 부분이고 내부 로직에 station 서비스가 있어서 스터빙을 했는데 .. 혹시 어떻게 해야 되는지 가이드를 받을 수 있을까요 ?? 
station 서비스를 mocking 안하면 null 에러가 나서요 

<img width="783" alt="image" src="https://user-images.githubusercontent.com/25348139/218313238-ce5bad50-7104-406c-b475-47c1ccbc0e98.png">

2023-02-12 13:15 UTC, ess234 commented on src/test/java/nextstep/subway/unit/LineTest.java
> +        Line line = 지하철노선_생성_기존구간_추가("지하철역1", "지하철역3", 5);
재활용할 수 있게 변수로 분리했습니당

2023-02-12 13:16 UTC, ess234 commented on src/test/java/nextstep/subway/unit/LineTest.java
> +        Section section = createSection(line, upStationName, downStationName, distance);
넵 최대한 내려가면서 볼 수 있게 정리하긴 했는데 말씀하신 의도에 맞게 수정했는지 확인 부탁드립니당 🙇‍♀️

2023-02-13 06:15 UTC, catsbi approved these changes
진윤님, 2단계 피드백 반영 잘 해주셨어요 👍 

여기저기 고민을 많이하신게 보이네요 ㅎㅎ 
1단계는 여기서 마무리 짓겠습니다. 다만, 피드백을 추가로 남긴게 있으니 코멘트 확인 후 2단계 에 같이 반영해서 리뷰요청해주세요!

2023-02-13 06:15 UTC, catsbi commented on src/main/java/nextstep/subway/applicaion/LineService.java
>      private LineResponse createLineResponse(Line line) {
음 답변이 좀 부족했나보군요 ㅎㅎ

제 말은 createLineResponse라는 DTO 생성의 책임을 서비스에서 가져가는게 맞는가에 대한 코멘트였습니다 ㅎ

2023-02-13 06:15 UTC, catsbi commented on src/test/java/nextstep/subway/unit/LineServiceMockTest.java
> +        when(stationService.findById(any())).thenReturn(new Station("지하철역1")).thenReturn(new Station("지하철역2"));
아! stationService였군요. 왜 LineService로 봤지ㅠㅠ 죄송합니다. 이 부분은 제가 잘못 피드백 드린 부분입니다. 😥

2023-02-13 06:15 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
> +    private Sections sections = new Sections();
필드 초기화 💯

2023-02-13 06:15 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Section.java
> +    protected Section() {
롬복을 이용한다면 @NoArgsConstructor(access = AccessLevel.PROTECTED) 도 가능합니다.
(Builder를 사용하고 계셔서 알려드립니다 ㅎ)

2023-02-13 06:15 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Sections.java
> +    @OneToMany(mappedBy = "line", cascade = CascadeType.ALL)
구간정보들은 노선 객체에 종속성을 가지고, 동일한 라이프사이클을 가집니다. 
영속성 전이 레벨을 ALL로 설정하셨는데, CascadeType.REMOVE와 orpanRemoval으로 삭제하는 것의 차이는 무엇일까요?

2023-02-13 06:15 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
반복문안에 분기문이 있습니다. depth를 더 낮출 수 없을까요?

2023-02-13 06:15 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
>      public void addSection(AddTypeEnum addTypeEnum, Section section) {
구간이 어디에 추가될지는 섹션 일급 컬렉션만 알면되지 않을까요? 노선 정보에서 구간이 앞,중간,뒤 어디에 붙을지 알 필요가 있을까요?

2023-02-13 06:15 UTC, merged

2023-02-13 06:22 UTC, ess234 commented on src/main/java/nextstep/subway/applicaion/LineService.java
>      private LineResponse createLineResponse(Line line) {
아하 코멘트 이해했습니당 2단계에 적용해서 PR 올리겠습니다.