Step2 지하철 구간 제거 기능 개선
next-step/atdd-subway-path pull request #486
Opened 2023-02-13 19:11 UTC by bactoria

승철님 안녕하세요. Step2 구현하였습니다.

리뷰 잘 부탁드립니다. 🤗

2023-02-14 12:13 UTC, pch8388 commented
<img width="695" alt="스크린샷 2023-02-14 오후 9 10 51" src="https://user-images.githubusercontent.com/17218212/218734907-9b94365e-b829-4ae5-842a-54a2cc474107.png">

인수테스트에도 예외 조건 처리를 해보시면 좋을 것 같아요 😄

2023-02-14 12:29 UTC, pch8388 requested changes
안녕하세요 준오님 🙇 
2단계도 아주 잘 수행해주셨네요 👏 
코멘트 남겨드린 부분 확인해주시고, 예외 처리와 테스트 보충 후 리뷰요청 해주세요 🔥

2023-02-14 12:29 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/Distance.java
> +        return new Distance(this.value + that.value);
👍

2023-02-14 12:29 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +        assertThat(response.jsonPath().getList("stations.id", Long.class)).containsExactly(강남역, 양재시민의숲역, 청계산입구역);
[코멘트](https://github.com/next-step/atdd-subway-path/pull/455#discussion_r1105497402) 로도 남겨드렸는데, 참고해주세요 😄

2023-02-14 12:29 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/Section.java
> +        if (this.downStation.equals(that.upStation)) {
`isSameUpStation` 과 비슷한 메서드 같은데, 개선할 방법이 없을까요? 🤔

2023-02-14 12:29 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
>      private Map<String, String> createLineCreateParams(Long upStationId, Long downStationId) {
LineSteps.java 쪽도 조금 리팩터링하면 좋을 것 같아요 😅 
파라미터를 생성해서 넘겨주는 `지하철_노선_생성_요청` 과 같은 부분도 개선할 여지가 있을 것 같습니다

2023-02-17 17:21 UTC, bactoria commented on src/main/java/nextstep/subway/ui/ControllerExceptionHandler.java
>          return ResponseEntity.unprocessableEntity().build();
예외 정보는 무조건 알려주어야 할 것 같아요. 

추가해두었습니다 🙇‍♂️ [110933c](https://github.com/next-step/atdd-subway-path/pull/486/commits/110933c1ba180d242a92e06fb01b9a67d6288589)

2023-02-17 17:29 UTC, bactoria commented on src/main/java/nextstep/subway/domain/Sections.java
> +            sections.remove(upperSection.get());
좀 더 방어적으로 구현 해 보았어요. [ced9878](https://github.com/next-step/atdd-subway-path/pull/486/commits/ced9878e869661b51acda06cfe4587affa5476e0)

`isPresent()-get()` 를 제거하고 싶지만, 

upperSection 과 lowerSection 둘 중 하나는 비어있을 수 있기에 제거하기가 어려워 보였는데요. 

혹시 조금 더 개선할 부분이 있을지 궁금합니다 🙏

2023-02-17 17:29 UTC, bactoria commented on src/test/java/nextstep/subway/domain/SectionsTest.java
> +        sections.remove(강남역);
아고,,, 요 케이스를 생각 못했네요. 추가해두었습니다. 
- 테스트: [5a4d02d](https://github.com/next-step/atdd-subway-path/pull/486/commits/5a4d02d4d628f448ecec26ee684b3a146322c2cc)
- 구현: [9388ba2](https://github.com/next-step/atdd-subway-path/pull/486/commits/9388ba2a2d7d020ebe0aff7cbe70d09acd0e5d87)

2023-02-17 17:33 UTC, bactoria commented on src/test/java/nextstep/subway/unit/LineServiceTest.java
> +        assertThat(line.getStations()).containsExactly(강남역, 양재역);
기존에는 '역' 에 대한 정보를 뽑아오는데 까지의 코드까지 읽어야 하는 것에 비해 
직관성이 높아져서 , 테스트 코드를 읽는데에 대한 부담이 많이 줄어든 것 같아요. 👏👏

2023-02-17 17:33 UTC, bactoria commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +        assertThat(response.jsonPath().getList("stations.id", Long.class)).containsExactly(강남역, 양재시민의숲역, 청계산입구역);
Step3 때는 제안 주신 방법으로 한번 테스트를 만들어 보겠습니다!

2023-02-17 17:34 UTC, bactoria commented on src/main/java/nextstep/subway/domain/Section.java
> +        if (this.downStation.equals(that.upStation)) {
재사용 가능하도록 파라미터를 Section -> Station 으로 변경하여 처리하였어요! [0538cc5](https://github.com/next-step/atdd-subway-path/pull/486/commits/0538cc514ef4d54e29297c0fdf3557acca0b6c5d)

2023-02-17 17:35 UTC, bactoria commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
>      private Map<String, String> createLineCreateParams(Long upStationId, Long downStationId) {
요 디테일 까지 생각을 못했네요. 🥹
아래에서 반영 해 보았습니다!
[90e6849](https://github.com/next-step/atdd-subway-path/pull/486/commits/90e684984db6edb5a0e4bef7c6092be0abc1b845)

2023-02-18 07:33 UTC, pch8388 approved these changes
리팩터링 꼼꼼히 잘해주셨습니다 👏 
남겨드린 코멘트 참고해주시고, 다음 단계 진행해주세요 🚀

2023-02-18 07:33 UTC, pch8388 commented on src/main/java/nextstep/subway/ui/ControllerExceptionHandler.java
> +        return ResponseEntity.unprocessableEntity().body(errorMessage);
💯

2023-02-18 07:33 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.UNPROCESSABLE_ENTITY.value());
예외조건 처리 💯 
만약 등록되지 않은 역 ID 가 넘어오면 어떻게 될까요? 😄 
아예 등록되지 않은 역 ID 가 전달되었을때 status code 가 의도한대로 응답되고 있을까요?

2023-02-18 07:33 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
```suggestion
        List<Section> list = this.sections.stream()
                .filter(it -> it.getDownStation().equals(station) || it.getUpStation().equals(station))
                .collect(Collectors.toList());

        if (list.size() == 1) {
            sections.remove(list.get(0));
            return;
        }

        sections.removeAll(list);
        sections.add(list.get(0).merge(list.get(1)));
```

이런 느낌으로 해볼수 있겠네요 😄

2023-02-18 07:33 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (!hasStation(station)) {
👍

2023-02-18 07:33 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/Section.java
> +        if (isSameUpStation(that.upStation) && !isSameDownStation(that.downStation)) {
피드백 반영 💯

2023-02-18 07:33 UTC, merged

2023-02-26 08:30 UTC, bactoria commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (alreadyExistAllStations(newUpStation, newDownStation)) {
넵 🙆‍♂️ 

기존보다 가독성이 많이 좋아진 것 같아요.

2023-02-26 09:16 UTC, bactoria commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.UNPROCESSABLE_ENTITY.value());
IllegalArgumentException 을 던지고 있어 수정을 해야 하는군요 ㅠㅠ

[452d5b1](https://github.com/next-step/atdd-subway-path/pull/554/commits/452d5b1634deef8ca0928eecbdf807654ba02c9f) 에서 반영하였습니다.