Step1 : 리뷰 부탁드립니다.
next-step/atdd-subway-path pull request #490
Opened 2023-02-14 13:55 UTC by seokjin0404

안녕하세요. 제가 1주차 미션이 너무 오래 걸려서 이번 주가 돼서야 미션을 시작했습니다.
제가 너무 오래 리뷰를 못 받는것 같아서 아직 미완성이고 구간 역 사이에 역을 추가하는 것까지 구현했는데, step0까지 리뷰 부탁 드리겠습니다.

2023-02-14 14:01 UTC, seokjin0404 commented on src/main/java/nextstep/subway/domain/Sections.java
> +            );
27번째 줄은 추가한 구간의 상행역 ~ 추가한 구간의 하행역
34번쨰 줄은 추가한 구간의 하행역 ~ 기존 구간의 하행역
까지 구간을 추가했는데요,
제 생각에는 34번째 줄에서 새롭게 나뉘어진 뒷구간을 pos에 끼워넣어서 sections 상에서 27번째 추가한 구간보다 앞에 추가됐습니다.
그래서 인수테스트에서 실패해야하는데, 이렇게 코드를 작성해야 성공해서 혹시 잘못된 부분 봐주실수 있는지 여쭙습니다.

2023-02-15 14:18 UTC, parkeeseul commented on src/main/java/nextstep/subway/domain/Sections.java
> +            );
혹시 어떠한 인수테스트에서 실패해야한다고 말씀해 주시는 걸까요?
section이 추가될 때 순서대로 저장이 되어야 한다 라는 목적의 테스트가 없기 때문에 해당 로직은 문제가 없을 것 같아요.
Section 은 순서대로 추가가 되어야 할까요? 😄

2023-02-15 14:21 UTC, parkeeseul commented on src/main/java/nextstep/subway/domain/Sections.java
> +public class Sections {
이번 미션의 요구사항에는 `도메인 레이어 테스트는 필수` 라는 사항이 있는데요
단위 테스트 작성 부탁드립니다 😄

2023-02-15 14:25 UTC, parkeeseul commented on src/test/java/nextstep/subway/unit/LineServiceMockTest.java
> +        assertThat(line.getColor()).isEqualTo(신분당선_색);
`ineService.findLineById(1L);`  는  
`when(lineRepository.findById(any())).thenReturn(Optional.of(new Line(신분당선_이름,신분당선_색)));` 로 
mocking된 결과값이 나올 것 같은데요. 검증이 되었다고 볼 수 있을까요? 🤔

2023-02-15 14:29 UTC, parkeeseul commented on src/test/java/nextstep/subway/unit/LineServiceTest.java
>      void addSection() {
addSection() 과 addSection2() 는 각각 어떠한 목적이 있는 테스트인지 파악할 수 있도록
@DisplayName() 을 통해 테스트의 설명을 적어주면 어떨까요? 😄

2023-02-18 08:51 UTC, seokjin0404 commented on src/test/java/nextstep/subway/unit/LineServiceTest.java
>      void addSection() {
작성했습니다!

2023-02-18 08:52 UTC, seokjin0404 commented on src/test/java/nextstep/subway/unit/LineServiceMockTest.java
> +        assertThat(line.getColor()).isEqualTo(신분당선_색);
line에 대한 정보가 아닌, 추가된 section의 distance를 검증하는 것으로 수정했습니다.

2023-02-18 08:57 UTC, seokjin0404 commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +    }
> 혹시 어떠한 인수테스트에서 실패해야한다고 말씀해 주시는 걸까요? section이 추가될 때 순서대로 저장이 되어야 한다 라는 목적의 테스트가 없기 때문에 해당 로직은 문제가 없을 것 같아요. Section 은 순서대로 추가가 되어야 할까요? 😄
이 부분이었는데, 말씀 주신대로 section을 추가할 때 순서대로 저장하지 않고, stations를 읽어오는 로직을 요구사항대로(?) 수정하고 나니 문제가 없어졌습니다.
> 노선 정보 응답으로 SectionRespons 를 추가해 주신 이유가 있으신가요?
이 부분에서 section의 수정된 distance를 확인하기 위해 추가했습니다. 테스트를 위해 Response를 바꾸는 것이 문제인 것일까요?

2023-02-18 08:58 UTC, seokjin0404 commented on src/main/java/nextstep/subway/domain/Line.java
> +    }
같은 일을 하니 합쳐주는 것이 좋을 것 같습니다

2023-02-19 03:00 UTC, parkeeseul requested changes
피드백 열심히 반영해 주셨네요
몇 가지 추가 코멘트 남겨두었으니 확인 부탁드립니다
즐거운 일요일 보내세요 🔥

2023-02-19 03:08 UTC, parkeeseul commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +    }
테스트 코드에서 검증을 하기 위해 response 를 변경해 주셨다고 이해했는데 맞을까요?
테스트 코드도 중요하지만 우리가 만들어야하는 프로덕트가 가장 우선시 되어야 하는데요,  테스트로 인해 실제 프로덕트의 스펙이 변경되면 안된다고 생각합니다.

2023-02-20 07:46 UTC, parkeeseul approved these changes
피드백 잘 반영해 주셨녜요! 👍 
한 가지 추가 코멘트 남겨두었으니 확인해 보시고
추가적인 수정 사항은 다음 단계와 함께 반영 부탁드립니다 😄 
다음 미션 진행해 주세요! 🔥

2023-02-20 07:46 UTC, merged