3단계 - 경로 조회 기능
next-step/atdd-subway-path pull request #507
Opened 2023-02-15 17:34 UTC by nooose

미션 진행하면서 궁금했던 점들 포함해서 리뷰 요청드립니다. 
리뷰 잘 부탁드립니다. 🙇‍♂️

2023-02-15 17:40 UTC, nooose commented on src/main/java/nextstep/subway/applicaion/Dikstra.java
> +    private final WeightedMultigraph<Station, DefaultWeightedEdge> graph = new WeightedMultigraph<>(DefaultWeightedEdge.class);
외부 라이브러리를 사용하는 구현체는 
기존 패키지 구조를 그대로 사용한다면 애플리케이션(서비스) 레이어도 괜찮을까요?

DIP 에 따라서 도메인이 인터페이스를 의존하고 있기 때문에 상관없다고 생각해서
서비스 레이어에 위치시켰습니다.

2023-02-15 17:43 UTC, nooose commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +
출발역과 도착역을 도메인이 아닌 서비스에서 검증해도 괜찮을까요?
충분히 도메인에서도 가능하지만 예외상황 시 
불필요하게 쿼리요청이 나갈까봐 먼저 예외를 발생시키도록 했습니다.
이런 경우에는 어떻게하는 것이 좋을까요??

2023-02-16 12:42 UTC, hjhello423 requested changes
안녕하세요 준혁님 😀
step3 깔끔하게 잘 진행해 주셨네요👍
코멘트 드릴 내용이 거의 없었습니다. 답변과 함께 한 가지 남겨두었는데 수정하고 마무리해 보면 어떨까요?

2023-02-16 12:42 UTC, hjhello423 commented on src/main/java/nextstep/subway/applicaion/Dikstra.java
> +    }
`List<Section>`과 `List<Station>`을 모두 인자로 받고 있네요. 🤔
section에서 station을 얻을 수 있을 것 같아요. 
이 부분만 한번 고치고 2주 차 미션을 마무리해 보면 어떨까요?

2023-02-16 12:42 UTC, hjhello423 commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    void getComplexPath() {
꼼꼼하게 테스트해 주셨네요. 💯

2023-02-16 12:42 UTC, hjhello423 commented on src/test/java/nextstep/subway/unit/domain/PathFinderTest.java
> +class PathFinderTest {
새로 추가된 도메인까지 테스트 👍

2023-02-16 12:43 UTC, hjhello423 commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +     *                          2
꼼꼼하게 만들어 주셨네요 👍👍

2023-02-16 12:45 UTC, hjhello423 commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +
'출발역과 도착역이 동일하면 안 된다.'라는 내용은 비즈니스상의 예외사항으로 생각되는데요.
저는 이런 부분을 보통 도메인에 포함시키는 쪽을 선호합니다. 😀
출발역, 도착역이 같은지 검증하는 역할은 어떤 도메인에 넘기면 좋을지 고민해 봐도 좋을 것 같아요.

2023-02-16 12:52 UTC, hjhello423 commented on src/main/java/nextstep/subway/applicaion/Dikstra.java
> +    private final WeightedMultigraph<Station, DefaultWeightedEdge> graph = new WeightedMultigraph<>(DefaultWeightedEdge.class);
이 부분은 사람마다 의견이 나뉠 것 같은데요.
우선 저는 infra 레이어에 있을 필요는 없을 것 같습니다.

DIP에 대한 질문 내용은 잘 이해가 안 갔는데요. 🥲
`Dikstra`는 이미 `WeightedMultigraph`, `DijkstraShortestPath`를 field에 선언하고 있는데 구현체에 의존하고 있지 않나요?

2023-02-16 13:09 UTC, nooose commented on src/main/java/nextstep/subway/applicaion/Dikstra.java
> +    }
그렇네요! 변경하도록 하겠습니다.

2023-02-16 13:17 UTC, nooose commented on src/main/java/nextstep/subway/applicaion/Dikstra.java
> +    private final WeightedMultigraph<Station, DefaultWeightedEdge> graph = new WeightedMultigraph<>(DefaultWeightedEdge.class);
제가 질문을 너무 애매하게 작성했네요 😅

`PathFinder(도메인)` --> `ShortestPathStrategy(도메인 인터페이스)` <-- `Dikstra(실 구현체)`
제 코드에는 이렇게 의존방향이 되어있는데요
PathFinder 라는 도메인이 Dikstra 라는 구현체에 직접적으로 의존하고 있지 않다는 내용이었습니다.

이렇게 되면 PathFinder 는 ShortestPathStrategy 라는 인터페이스 규격에 맞는 구현체를 직접적으로 의존하지 않고
사용할 수 있게 되는데 
Dikstra(실 구현체) 를 애플리케이션 레이어에 위치시켜도 괜찮은지
아니면 새로운 패키지(레이어)를 만들고 그곳에 위치시켜야하는지 이런 궁금증이 있어 질문했습니다.

2023-02-16 13:19 UTC, nooose commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +
감사합니다.

2023-02-17 08:14 UTC, hjhello423 approved these changes
안녕하세요 준혁님 😀
step3까지 마무리되면서 이제 2주 차 미션이 끝났네요.
미션 진행하면서 많은 걸 얻어 가셨길 바랍니다.
그럼 이만 머지하도록 하겠습니다! 다음 미션도 파이팅 🔥

2023-02-17 08:14 UTC, hjhello423 commented on src/main/java/nextstep/subway/applicaion/Dikstra.java
> +    public void init(List<Section> edges) {
리뷰 반영해 주셨군요. 👍

2023-02-17 08:56 UTC, merged

2023-02-17 15:20 UTC, hjhello423 commented on src/main/java/nextstep/subway/applicaion/Dikstra.java
> +    private final WeightedMultigraph<Station, DefaultWeightedEdge> graph = new WeightedMultigraph<>(DefaultWeightedEdge.class);
저라면 준혁님 처럼  application 레이어에 둘 것 같습니다 😀