3단계 리뷰 요청드립니다.
next-step/atdd-subway-path pull request #560
Opened 2023-03-02 13:00 UTC by heoseungyeon

안녕하세요 희선님! 🙇 

3단계 구현 완료하여 리뷰 요청드립니다!

이전 [리뷰 내용](https://github.com/next-step/atdd-subway-path/pull/552#discussion_r1118011336)(구간 삭제 유효성 검사)에서 '메세지를 sections에 전달해본다'를 어떻게 수행해야 할지 몰라, removeSections()에 유효성 검사 코드를 갖게 하도록만 해보았는데요,, 이 점에 대해 조금 더 힌트를 주시면 감사하곘습니다 😢

2023-03-03 11:30 UTC, heesunjeong requested changes
승연님 이번 미션 마지막 단계까지 테스트와 함께 ATDD 사이클을 지키며 구현 잘 해주셨습니다 👍 
미션을 끝내기 전에 몇가지 더 참고해보시면 좋을 것 같은 점을 코멘트로 추가했는데요! 확인 부탁드려요 :)
추가로 궁금하신 점이 생기시면 언제든지 코멘트 남겨주세요! 🔥 🔥

2023-03-09 08:14 UTC, heoseungyeon commented on src/main/java/nextstep/subway/applicaion/dto/PathResponse.java
> +	private List<Station> stations;
아 놓쳤던 부분인데 짚어주셔서 감사합니다 ㅎㅎ 수정하여 반영했습니다!

2023-03-09 08:15 UTC, heoseungyeon commented on src/main/java/nextstep/subway/domain/PathFinder.java
> +		for (Section section : line.getSections().getSections()) {
오 해당 내용 반영해보니 가독성 또한 좋아졌습니다 ! 👍

2023-03-09 10:28 UTC, heoseungyeon commented on src/main/java/nextstep/subway/domain/PathFinder.java
> +			graph);
PathFinder 클래스의 인스턴스 변수로 DijkstraShortestPath 을 추가해보았습니다! 
 그 과정에서 WeightedMultigraph 변수를 init하는 과정이 PathFinder 내부에서 관리되어지는 것이 결합도 관점에서 별로 좋지 않아보여서 WeightedMultigraph 타입 변수를 래핑하는 StationMap 객체를 만드는 시도를 해보았습니다 😄

2023-03-10 14:51 UTC, heesunjeong approved these changes
승연님 피드백 반영 잘 해주셨습니다 👍 👍 
이번 미션은 마무리하도록 하겠습니다! 고생 많으셨습니다 👏 
이 기세로 마지막 미션까지 도전해보시고 인사이트를 많이 얻어가시는 기회가 되시면 좋겠습니다! 🙂 화이팅입니다 🔥 🔥

2023-03-10 14:51 UTC, heesunjeong commented on src/main/java/nextstep/subway/applicaion/dto/PathResponse.java
> +	private List<StationResponse> stations;
👍

2023-03-10 14:51 UTC, heesunjeong commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +		if (line.getSections().isEmpty()) {
피드백 반영 잘 해주셨습니다 💯

2023-03-10 14:51 UTC, merged