🚆 1단계 - 지하철 구간 추가 기능 개선
next-step/atdd-subway-path pull request #567
Opened 2023-03-25 13:57 UTC by boradol

안녕하세요. 리뷰어님.
처음 뵙겠습니다.

기간이 지나고 나서 늦게 요청드려 죄송합니다.

그래도 완주하고 싶은 마음에 기능들을 추가하여 구현해보았습니다.
조금 마음이 급해 많이 미흡하지만, 완주까지 도와주신다면 열심히 리뷰 반영하도록 하겠습니다.

감사합니다.

2023-04-01 02:45 UTC, HyunSung-Na requested changes
안녕하세요 보라님!

1단계 미션 잘 수행해 주셨네요! 👍

몇가지 도움이 될만한 코멘트 남겼으니 확인 후 리뷰 재요청 해주시면 감사하겠습니다! 🙇

2023-04-01 02:45 UTC, HyunSung-Na commented on README.md
> +### 기능 요구사항
요구사항 문서화를 잘 해주셨네요! 👍

2023-04-01 02:45 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/applicaion/dto/StationResponse.java
> +        List<Station> stations = line.getAllStations();
StationResponse DTO 가 line 의 메서드를 알 필요가 있을까요?
`List<Station> stations` 를 파라미터 받는 건 어떨까요? 😊

2023-04-01 02:45 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/domain/Line.java
> +    private final Sections sections = new Sections();
`@Embedded` 를 잘 활용해 주셨네요! 👍

2023-04-01 02:45 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/domain/Line.java
> +        sections.add(new Section(this, upStation, downStation, distance));
dinstance 가 1 보다 작으면 어떻게 되는 걸까요? 🧐

2023-04-01 02:45 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/domain/Sections.java
> +
제일 처음 구간이나 제일 마지막 구간도 위의 함수에 해당 될거 같은데 어떻게 생각하시나요? 😊
또한 중복된 동작을 여러번 할 수도 있을거 같은데 조건에 따라 함수를 실행해 주시면 어떨까요?

2023-04-01 02:45 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/exception/DuplicatedDownStationException.java
> +public class DuplicatedDownStationException extends IllegalArgumentException {
Custom Exception 👍

2023-04-01 02:45 UTC, HyunSung-Na commented on src/test/java/nextstep/subway/unit/LineTest.java
> +    void checkDistanceForAddSection() {
예외 경우도 잘 테스트 해주셨네요! 👍
마찬가지로 도메인 테스트 뿐만아니라 인수테스트도 작성해주시면 좋을거 같습니다 ☺️

2023-04-07 14:14 UTC, boradol commented on src/main/java/nextstep/subway/domain/Line.java
> +        sections.add(new Section(this, upStation, downStation, distance));
에러처리하였습니다!

2023-04-07 16:12 UTC, boradol commented on src/main/java/nextstep/subway/domain/Sections.java
> +
음... 처음이나 제일마지막 구간의 함수는 포함시키지 못했습니다 ㅠㅠ 

조건을 주는 것은 구현해보았습니다.

2023-04-16 11:18 UTC, HyunSung-Na approved these changes
안녕하세요 보라님!

피드백 반영을 잘해주셨네요! 😊

머지하도록 하겠습니다! 다음단계도 화이팅 하세요! 🔥

2023-04-16 11:18 UTC, merged