Step1
next-step/atdd-subway-path pull request #579
Opened 2023-07-12 06:26 UTC by psy3720

안녕하세요! 1단계 - 지하철 구간 추가 기능 개선 리뷰 요청 드립니다.
단위 테스트 작성 때 주셨던 피드백도 함께 수정하였습니다!

2023-07-13 01:47 UTC, hjhello423 requested changes
안녕하세요 승용님 😀
step1 잘 진행해 주셨습니다!
예외 케이스까지 잘 테스트해 주셨네요.
몇 가지 확인해 보고 넘어가면 좋을 부분들에 코멘트를 달아두었습니다.
확인 후 다시 한번 리뷰 요청 주세요! 화이팅!!🔥🔥

2023-07-13 01:47 UTC, hjhello423 commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +            line.addSection(new Section(line, upStation, downStation, request.getDistance()));
리팩토링 굳굳굳 👍👍👍

2023-07-13 01:47 UTC, hjhello423 commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private Station downStation;
필드를 봤을 때 `Sections` 와 `Section`의 차이점이 무엇인지 파악하기 힘든 것 같아요.
`Sections`라는 이름을 봤을 때 `Section`들의 집합처럼 느껴졌어요.
리팩토링해볼 수 있지 않을까요? 🤔

2023-07-13 01:47 UTC, hjhello423 commented on src/main/java/nextstep/subway/domain/Sections.java
> +    }
Map을 만들고 Map의 참조를 인자로 던져주고 있군요 🤔

2023-07-13 01:47 UTC, hjhello423 commented on src/main/java/nextstep/subway/domain/Sections.java
> +    }
상행 역을 key, 하행 역을 value로 가지고 있는데요.
이 형태의 Map을 왜 만들었는지 의도 파악이 조금 어려워 보일 수 있을 것 같아요.
상행 역, 하행 역을 가지고 있는 구조는 이미 `Section` 엔티티가 있지 않나요?

2023-07-13 01:47 UTC, hjhello423 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
주석을 이용해 행위를 설명하고 있네요.
다른 방식으로 표현해 보면 좋을 것 같아요! (메서드로 분리)

2023-07-13 01:47 UTC, hjhello423 commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +        지하철_노선에_지하철_구간_생성_요청(신분당선, createSectionCreateParams(강남역, 교대역, 6));
시나리오가 인수 테스트에서 검증하는 내용을 잘 표현하지 못하고 있는 것 같아요. 🤔

2023-07-13 01:47 UTC, hjhello423 commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +    }
10, 11이라는 거리가 기존의 등록된 거리보다 크거나 같다는 걸 이 코드만 보고 어떻게 알 수 있을까요?
`setUp()`에서 등록해둔 강남-양재 노선의 거리를 누군가 20으로 변경할 수 있지 않을까요?

2023-07-13 01:47 UTC, hjhello423 commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +    @Test
`강남----10----양재` 구간이 등록된 상태에서
`강남----5----정자`를 등록 후 
`강남----5----미금`을 등록 요청하면 어떻게 처리되어야 할까요?
예외 처리가 추가되어야 할 것 같아요

2023-07-13 01:47 UTC, hjhello423 commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +     */
예외 케이스까지 만들어 주셨네요 👍

2023-07-13 01:47 UTC, hjhello423 commented on src/test/java/nextstep/subway/unit/LineTest.java
> +    private Station 또다른_지하철역;
이면 step을 진행하면서 `Line` 뿐 아니라 `Section`, `Sections` 같은 중요한 도메인이 도출되었는데요.
미션의 요구사항대로 인수 테스트 이후 기능 구현은 TDD로 진행했다면
`Section`과 `Sections`도 테스트 코드가 만들어졌어야 할 것 같아요. 🤔

2023-07-13 10:51 UTC, psy3720 commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private Station downStation;
넵 수정해보겠습니다!

2023-07-13 10:53 UTC, psy3720 commented on src/main/java/nextstep/subway/domain/Sections.java
> +    }
맵을 만든 의도는 변경된 요구 사항으로 인해 구간이 저장되는 순서로 역 목록을 조회할 경우 순서가 다르게 조회될 수 있어 해당 부분을 수정하였습니다!

만약 상행종점역에 해당하는 구간이 리스트에 중간에 위치할 경우 전체역을 순서대로 조회하기 위해서는 1번째 항목부터 다시 찾아야 하기 때문에 상행역을 기준으로 바로 하행역을 찾을 수 있도록 맵을 만들었어요.

의도 파악이 조금 더 쉽도록 수정 반영 해보겠습니다~~

2023-07-13 12:00 UTC, psy3720 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
넵 수정해보겠습니다~~!!

2023-07-13 12:18 UTC, psy3720 commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +    @Test
넵 수정 반영하겠습니다!

2023-07-13 12:42 UTC, psy3720 commented on src/test/java/nextstep/subway/unit/LineTest.java
> +    private Station 또다른_지하철역;
추가하도록 하겠습니다!!

2023-07-13 12:42 UTC, psy3720 commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +    @Test
추가하도록 하겠습니다!~

2023-07-13 12:43 UTC, psy3720 commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +    }
수정하도록 하겠습니다~!

2023-07-13 13:05 UTC, psy3720 commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +        지하철_노선에_지하철_구간_생성_요청(신분당선, createSectionCreateParams(강남역, 교대역, 6));
수정하겠습니다!

2023-07-14 11:59 UTC, hjhello423 approved these changes
안녕하세요 승용님 😀
많은 리팩토링이 있었네요. 단위 테스트도 잘 추가해 주셨고요 👍
머지 하도록 하겠습니다!

2023-07-14 11:59 UTC, hjhello423 commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +    private final int LINE_DISTANCE = 10;
테스트 과정에서 사용되던 거리 값을 분리시켜주셨네요. 👍

2023-07-14 11:59 UTC, hjhello423 commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +     */
테스트 케이스도 추가 👍👍

2023-07-14 11:59 UTC, hjhello423 commented on src/test/java/nextstep/subway/unit/LineSectionsTest.java
> +    private LineSections 지하철노선_구간;
구간에 대한 테스트 코드 추가도 👍

2023-07-14 11:59 UTC, merged