1단계 - 지하철 구간 추가 기능 개선
next-step/atdd-subway-path pull request #594
Opened 2023-07-16 00:23 UTC by Deserve82

1주차 1단계 기능 구현 했습니다. 요구사항을 구현하면서 노선의 상하행선을 저는 따로 노선에 저장하는 방법을 사용해서 노선 목록을 응답 할 때에 매번 모든 구간을 탐색하지 않도록 구현 했는데 추후 미션에 영향이 미칠 지 궁금합니다.

2023-07-16 12:39 UTC, testrace requested changes
안녕하세요 강호님 😃 
1단계 미션 빠르게 구현하셨네요 👍 
몇 가지 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청 부탁드려요

2023-07-16 12:39 UTC, testrace commented on README.md
> +  - [x] 역 사이 구간 추가 할 때에 길이가 기존 사이 길이보다 클 때
기능 목록 정리 👍 
기능 단위로 커밋해 보셔도 좋을 것 같아요

2023-07-16 12:39 UTC, testrace commented on src/main/java/nextstep/subway/line/domain/LineLastStations.java
> +    }
종점역 id를 line 테이블의 컬럼으로 관리하려면 많은 validation 이 필요할 것 같아요
line 의 up_last_station_id 의 값이 station 테이블에 존재하지 않다거나 sections 에 없다면 종점역 관리 기능이 의도대로 동작하지 않을 것 같아요
개인적으로 LastStations 의 책임을 분리하기 보다 SectionList에서 수행하는게 좋을 것 같은데 어떻게 생각하세요?

2023-07-16 12:39 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        지하철_노선도_등록("7호선", "bg-1234", 1L, 3L, 5);
역 ID를 숫자로 작성하기 보다 역명을 그대로 쓴다면 테스트 가독성을 높여보면 어떨까요?
```suggestion
        지하철_노선도_등록("7호선", "bg-1234", 첫번째역, 세번째역, 5);
```

2023-07-16 12:39 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        하행선_기대값_검증(line7, 3L, "세번째역");
중간역이 추가되었을 경우 중간역까지 등록되었는지 검증하면 어떨까요?
노선에 등록된 모든 역을 조회해서 `첫번째역 - 두번째역 - 세번째역` 역 목록을 검증을 하면 좋을 것 같아요

2023-07-16 12:39 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +    @DisplayName("지하철 구간을 생성한다. - 새로운 역이 상행 종점일 때에")
인수 조건에는 하행 종점인데 DisplayName에는 상행 종점이네요 😢 
용어를 통일하면 좋을 것 같아요

2023-07-16 12:39 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +    }
상행선은 노선을 뜻하는 것 같아요 (부산발 서울행)
코드는 첫번째 역을 검증하니 상행 종점역으로 용어를 변경하면 좋을 것 같은데 어떻게 생각하시나요?

2023-07-16 12:39 UTC, testrace commented on src/test/java/nextstep/subway/unit/section/SectionListTest.java
> +    }
요구사항과 일치 하지 않는 것 같아요 😢 
(a-5-b) 구간에서 (a-4-c) 구간을 추가하면 (a-1-c), (c-4-b) 구간이 되어야 하지 않을까요? 🤔 
거리뿐만 아니라 상행역 하행역까지 모두 검증해 보면 좋을 것 같아요

2023-07-18 12:16 UTC, Deserve82 commented on src/test/java/nextstep/subway/unit/section/SectionListTest.java
> +    }
꼼꼼한 확인 감사합니다 ㅠㅠ 구간 사이에 역 추가를 완전히 잘못 이해하고 있었어요.. 위에 LastStations 이랑 같이 연결되는 부분들인데, 구간이 변경되어서 저장이 된다는 것을 파악을 못했습니다.. 그래서 LastStations으로 검증이 가능하지 않나? 라는 생각을 가지고 있었던거 같아요..! 관련된 부분들 전부 삭제하고 상행 종점, 하행 종점 구하는 것도 새로 구현하였습니다. 감사합니다!

2023-07-18 12:16 UTC, Deserve82 commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +    }
이 부분도 모호한 부분이 있어서 상행 종점역, 하행 종점역으로 변경했습니다!

2023-07-18 12:17 UTC, Deserve82 commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +    @DisplayName("지하철 구간을 생성한다. - 새로운 역이 상행 종점일 때에")
오타입니다ㅠㅠ 수정했습니다!!

2023-07-18 12:18 UTC, Deserve82 commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        하행선_기대값_검증(line7, 3L, "세번째역");
아 말씀해주신대로 중간 역을 검증할 필요가 있을거 같습니다. 이 부분 다시 추가해보겠습니다!

2023-07-19 04:58 UTC, testrace approved these changes
안녕하세요 강호님 😃 
피드백 반영 잘해주셨네요 👍 
몇 가지 코멘트 남겨두었는데 확인해 주시고 다음 단계 진행해 주세요
다음 단계도 화이팅입니다 🔥

2023-07-19 04:58 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        하행_종점역_기대값_검증(line7, 세번째역, "세번째역");
지난 피드백이 반영되지 않은 것 같아요 😢 
중간 구간이 추가/변경된 경우 역 목록을 검증을 하면 어떨까요?

2023-07-19 04:58 UTC, testrace commented on src/test/java/nextstep/subway/unit/section/SectionListTest.java
> +        assertThat(sectionBC.getDistance()).isEqualTo(4);
지난 코멘트에서 구간의 거리를 잘못 말씀드렸네요 😢 
(a-5-b) 구간에서 (a-4-c) 구간을 추가하면 (a-4-c), (c-1-b) 구간이 되어야 할 것 같아요

2023-07-19 04:58 UTC, merged

2023-07-19 05:00 UTC, Deserve82 commented on src/test/java/nextstep/subway/unit/section/SectionListTest.java
> +        assertThat(sectionBC.getDistance()).isEqualTo(4);
이런 저도 반대로 생각했나보군요.. 우선은 확인했습니다~! 맞게 수정해볼게요!

2023-07-19 05:00 UTC, Deserve82 commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        하행_종점역_기대값_검증(line7, 세번째역, "세번째역");
다음 미션에 중간 구간 인수테스트도 추가해볼게요!