미션 2: 지하철 구간 제거 기능 개선
next-step/atdd-subway-path pull request #595
Opened 2023-07-16 01:56 UTC by owen-q

안녕하세요! 
지하철 구간 제거 기능 개선에 대해서 구현하였습니다 
리뷰 잘 부탁드립니다~!

2023-07-16 12:16 UTC, hiblue02 requested changes

2023-07-16 12:16 UTC, hiblue02 commented on src/test/java/nextstep/subway/unit/LineTest.java
> +                             .build();
새로운 Line을 만드는데 Static 변수를 재사용할 필요가 있을까요? :thinking:

2023-07-16 12:16 UTC, hiblue02 commented on src/test/java/nextstep/subway/unit/LineTest.java
> +                lineAB.addSection(givenAddSection);
given 절이 반복되고 있네요. @Nested를 사용해주시면 좋을 것 같아요.

2023-07-16 12:16 UTC, hiblue02 commented on src/test/java/nextstep/subway/unit/LineTest.java
> +                org.assertj.core.api.Assertions.assertThat(lineAB.equalDownStation(stationB.getId()));
1. 코드가 길어지는 걸 방지하기 위해 static import를 사용해보면 어떨까요?
2. 테스트 코드가 명확하지 않네요. isTrue()를 붙여보는 건 어떨까요?

2023-07-16 12:16 UTC, hiblue02 commented on src/test/java/nextstep/sections/SectionsTest.java
> +        class When_중간역을_제거하면 {
벌써 2단계 구간 삭제 기능까지 구현해주셨군요!

2023-07-16 12:16 UTC, hiblue02 commented on src/test/java/nextstep/sections/SectionsTest.java
> +    class Given_노선에_구간이_2개이상일때 {
인수테스트를 꼼꼼히 작성해주셨네요! :100:

2023-07-16 12:16 UTC, hiblue02 commented on src/test/java/nextstep/sections/SectionsTest.java
> +                });
테스트를 명확하게 해주기 위해서 isInstanceOf를 붙여보면 어떨까요?

2023-07-16 12:16 UTC, hiblue02 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        return getLastSection().equalsDownStation(stationId);
isLastDownStation과 기능이 같아보여요. :sweat_smile:

2023-07-16 12:16 UTC, hiblue02 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    }
밖에서 Optional.of로 감싸주지 않고, 여기서 바로 Optional을 반환해도 될 것 같아요.

2023-07-16 12:16 UTC, hiblue02 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        }
이렇게 size로 판단하기 보다는, "중간역 추가", "종점 추가"로 기능을 명확하게 해주는 게 좋지 않을까요?

2023-07-16 12:19 UTC, hiblue02 commented
1. 도메인 레이어에서 id를 이용하는 메소드가 많은데요. 객체를 이용하도록 바꿔보는게 어떨까요?

2023-07-16 12:26 UTC, hiblue02 requested changes
2단계 미션도 잘 구현해주셨네요!  💯 
코멘트 남겨두었는데, 확인 후 다시 리뷰 요청주세요. 😄

2023-07-16 12:26 UTC, hiblue02 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        sections.possibleToDeleteSection();
sections에 없거나 방향이 다른 구간에 대한 삭제가 들어오는 경우에 대한 예외 처리가 없어보여요.

2023-07-16 12:26 UTC, hiblue02 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        nextDownStation.ifPresent(station -> this.downStation = station);
if문 안에 적어주셔도 괜찮을 듯 한데, 분리해주신 이유가 있을까요? :thinking:

2023-07-20 12:36 UTC, owen-q commented
코드리뷰 감사합니다! 
리뷰 반영해보았고, 미션 안내에서 서비스 레이어에 대한 테스트는 선택이라서, mockito 를 사용한 테스트는 이번 미션에서 건너 뛰어도 괜찮을까요..? 
진도가 조금 더딘듯하여 양해 구해보고자 합니다!

2023-07-20 15:38 UTC, hiblue02 commented
앗 네! 간단하게 구간 삭제 1개만 작성 요청드린 거였는데요. 😅 
이미 구간 생성 Mock 테스트를 작성해주셔서 넘어가도 될 것 같네요. ㅎㅎ 
다음 단계도 화이팅입니다! 🔥

2023-07-20 15:39 UTC, hiblue02 reviewed
2단계 미션도 잘 구현해주셨네요!. 머지할게요. 
코멘트 남겼는데, 확인해주시고 다음 미션 진행해주세요! 👍

2023-07-20 15:39 UTC, hiblue02 commented on src/test/java/nextstep/subway/unit/LineTest.java
> +    @Nested
리뷰 반영 :+1:

2023-07-20 15:39 UTC, hiblue02 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        }
이 메소드를 호출하는, Line의 deleteSection에서 이미 종점을 삭제하는지, 중간을 삭제하는지를 판별하고 있는데요. 구조를 개선해보면 어떨까요?

2023-07-20 15:39 UTC, hiblue02 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        return Objects.equals(upStation, station);
메소드를 만들지 않고 바로 equals를 호출해줘도 되지 않을까요? 😄 
`this.upStation.equals(station)`

2023-07-20 15:39 UTC, hiblue02 commented on src/main/java/nextstep/subway/line/domain/Sections.java
>              return false;
이 검증 로직이 필요할까요? 🤔

2023-07-20 15:39 UTC, hiblue02 commented on src/test/java/nextstep/subway/unit/LineTest.java
> +                assertThat(lineAB.equalDownStation(stationC));
여기 깜빡하신 것 같아요.

2023-07-20 15:41 UTC, hiblue02 approved these changes
2단계 미션도 잘 구현해주셨네요!. 머지할게요.
코멘트 남겼는데, 확인해주시고 다음 미션 진행해주세요! 👍

2023-07-20 15:42 UTC, merged