🚀 1단계 - 지하철 구간 추가 기능 개선
next-step/atdd-subway-path pull request #599
Opened 2023-07-16 15:54 UTC by ktae23

일주일 가량 손 놨다가 다시 하려니까 힘드네요 ㅠ
역시 일단 돌아가게 구현하는건 쉬워도 역할과 책임, 그리고 가독성 등을 생각하며 작성하는건 어렵다는걸 또 느낍니다.

2단계, 3단계는 아직 시작도 안했는데 화이팅 해야겠네요!

전체 테스트를 돌렸을 때 2단계 항목인 삭제 기능 개선 부분은 테스트가 실패하지만 TODO로 남겨두었습니다.

뼈대코드에 저번주차 코드를 가져오다 보니 변경점이 많은 걸로 나오는데요.
각 도메인 클래스와 test.unit 패키지 하위 그리고 SectionAcceptanceTest를 확인해주시면 감사하겠습니다.

2023-07-17 03:57 UTC, testrace requested changes
안녕하세요 경태님 😃 
1단계 미션 잘 구현해 주셨네요 👍 
몇 가지 코멘트 남겼는데 확인해 주시고 다시 리뷰 요청 부탁드려요.

2023-07-17 03:57 UTC, testrace commented on src/main/java/nextstep/subway/domain/Station.java
> +import nextstep.subway.service.command.StationCreateCommand;
도메인 객체가 service 패키지에 의존하지 않도록 하면 어떨까요?

2023-07-17 03:57 UTC, testrace commented on src/test/java/nextstep/subway/unit/LineTest.java
> +        Assertions.assertEquals(13L, line.getDistance());
상행 종점역 추가, 중간 역 추가 등 다양하게 구간 추가 테스트를 하면 좋을 것 같아요
구간이 추가된 이후에 노선에 포함된 역 목록을 순서대로 검증하면 어떨까요?

2023-07-17 03:57 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +    @Nested
Nested 👍

2023-07-17 03:57 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        @CsvSource(value = {"10", "11", "12"})
경계값 테스트 👍 
인수 조건에 구체적인 예외 클래스명을 명시하기 보다 `구간 등록에 실패한다`라고 표현하면 어떨까요?

2023-07-17 03:57 UTC, testrace commented on src/main/java/nextstep/subway/domain/Line.java
> +    }
노선이 전체 길이를 직접 관리하기 보다 sections.sumOfDistance를 리턴하면 어떨까요?

2023-07-17 03:57 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +         */
중간 역을 추가하는 경우 노선의 전체 거리는 변경이 없으니 `거리가 추가 된다` 조건은 제거하면 어떨까요?

2023-07-17 03:57 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +         * Then 새로운 구간이 노선에 추가되고 조회 시 하행역이 변경되고 거리가 추가 된다.
```suggestion
         * Then 새로운 구간이 노선에 추가되고 조회 시 상행역이 변경되고 거리가 추가 된다.
```

2023-07-17 13:09 UTC, ktae23 commented
꼼꼼하게 읽어주시고 주신 리뷰들이 하나 하나 모두 맞는 말씀이고 제가 놓친 부분 들이어서 전부 반영했습니다!
감사합니다. : )

2023-07-18 01:04 UTC, testrace approved these changes
안녕하세요 경태님 😃 
피드백 반영 잘해주셨네요 👍 
다음 단계도 화이팅입니다 🔥

2023-07-18 01:04 UTC, testrace commented on src/main/java/nextstep/subway/domain/Station.java
> +import nextstep.subway.domain.command.StationCreateCommand;
피드백 반영 👍

2023-07-18 01:04 UTC, testrace commented on src/test/java/nextstep/subway/unit/LineTest.java
> +    class 구간_추가 {
꼼꼼한 단위 테스트 좋네요 👍

2023-07-18 01:04 UTC, merged