🚀 1단계 - 지하철 구간 추가 기능 개선
next-step/atdd-subway-path pull request #611
Opened 2023-07-19 05:02 UTC by thalals

안녕하세요 많이 늦었습니다 ! 잘부탁드리겠습니다 🙇‍♂️

1주차에 작업했던 코드를 그대로 가지고와서 이번단계에서 작업한 부분 코멘트 남겨놓겠습니다  :)

[질문]
1. SectionGroup 코드에서 추가할 section 그룹을 반복문으로 찾아 add 하는 부분이 do-while 을 피하려고하다보니 다소 난잡해진거같습니다.
조금더 명확하고 깔끔하게 코드에 의도를 들어내도록 개선하고싶은데 리팩토링의 아이디어를 얻을수있을까요 ? ㅠㅠ

2023-07-20 02:09 UTC, testrace requested changes
안녕하세요 형민님 😃 
1단계 미션 잘 구현해 주셨네요 👍 
몇 가지 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청해 주세요

2023-07-20 02:09 UTC, testrace commented on src/main/java/nextstep/subway/entity/Section.java
> +    private boolean isDownEndPointSection;
노선은 A-B, A-C 와 같은 동일한 상행역(또는 하행역)을 가지는 구간을 가질 수 없으니
SectionGroup에서 종점역이나 종점 구간을 조회할 수 있을 것 같아요
Section에서 종점역 컬럼을 가지면 매번 validate 해야하는 점이 오히려 복잡도를 증가 시킬 것 같은데요
이 컬럼들은 제거하면 어떨까요?

2023-07-20 02:09 UTC, testrace commented on src/main/java/nextstep/subway/entity/group/SectionGroup.java
> +        }
질문 주신 부분이네요
변경에 취약하더라도 모든 케이스를 고려하는 건 오버엔지니어링이 되기 쉬울 것 같아요
구간 추가 조건을 크게 나누었을 때 종점역 추가, 중간역 추가 두 가지가 있으니 분기처리를 하면 어떨까요?

개인적으로 do-while이나 while문은 코드의 의도를 드러내기 힘들다고 생각해요 😃

2023-07-20 02:09 UTC, testrace commented on src/main/java/nextstep/subway/entity/group/SectionGroup.java
> +    }
방어적 복사를 위해 불변 컬렉션을 리턴해도 좋을 것 같아요 😃 
```suggestion
    public List<Section> getSections() {
        return Collections.unmodifiableList(sections);
    }
```

2023-07-20 02:09 UTC, testrace commented on src/main/java/nextstep/subway/entity/group/factory/SectionAddActionFactory.java
> +public interface SectionAddActionFactory {
질문 주신 부분이네요!
팩토리 패턴을 사용하신 점이 인상적입니다 👍 
테스트 코드가 추가되면 더 좋을 것 같아요 😃

2023-07-20 02:09 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +    void addMiddleSection() {
프로그래밍 요구사항에 `인수 테스트 주도 개발 프로세스에 맞춰서 기능을 구현하세요`라는 항목이 있는데요
커밋 로그를 보면 기능을 먼저 구현한 후에 인수 테스트를 작성한 것 같아요
인수 조건 정의, 인수 테스트 작성 후에 TDD로 구현하는 경험을 해보시면 더 좋을 것 같아요 😃

2023-07-20 02:09 UTC, testrace commented on src/test/java/nextstep/subway/entity/group/SectionGroupTest.java
> +class SectionGroupTest {
꼼꼼한 단위 테스트 👍

2023-07-20 02:09 UTC, testrace commented on src/test/java/nextstep/subway/fixture/given/LineRequestFixture.java
> +package nextstep.subway.fixture.given;
fixture 활용 👍 
인수 테스트에서 활용되는 픽스처와 단위 테스트에서 활용되는 픽스처를 패키지로 구분하면 좋을 것 같은데 어떻게 생각하시나요?

2023-07-20 02:09 UTC, testrace commented on src/test/java/nextstep/subway/unit/LineServiceTest.java
실습 단계의 단위 테스트 작성이 누락되었네요 😢 
실습도 진행해 보시면 좋을 것 같아요

2023-07-20 05:06 UTC, thalals commented on src/test/java/nextstep/subway/unit/LineServiceTest.java
이런,, 실습내용이 있다는걸 발견하지 못했네요 🤣
같이 진행해보겠습니다..!

2023-07-20 05:07 UTC, thalals commented on src/test/java/nextstep/subway/fixture/given/LineRequestFixture.java
> +package nextstep.subway.fixture.given;
너무 좋은 의견이신거같아요
안그래도 인수테스트 픽스쳐를 처음 만들다보니 점점 지저분해지는거같아 고민중이였는데 의견 감사드립니다!!

2023-07-20 05:07 UTC, thalals commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +    void addMiddleSection() {
넵! 도전해보겠습니다:)

2023-07-20 05:07 UTC, thalals commented on src/main/java/nextstep/subway/entity/group/factory/SectionAddActionFactory.java
> +public interface SectionAddActionFactory {
감사합니다 !

2023-07-20 05:08 UTC, thalals commented on src/main/java/nextstep/subway/entity/group/SectionGroup.java
> +    }
생각지도 못했는데 이렇게되면 일급컬렉션들을 더 안정적이게 사용할 수 있겠네요 👏🏻

2023-07-21 06:42 UTC, thalals commented on src/main/java/nextstep/subway/entity/Section.java
> +    private boolean isDownEndPointSection;
직접 시도해보고나니 확실히 상태관리면에서는 복잡도가 줄었다는 느낌이 들었습니다 👏🏻
다만 SectionGroup이 일급컬렉션으로써 기능을 수행할려면 계속해서 반복문을 돌면서 종점구간을 매번 확인해야된다는 느낌이 드는데 
일급컬렉션이 관리하는 리스트의 size 가 크다면 오히려 성능저하를 일으키게되지 않을까요..??

어플리케이션 코드단에서 상태변경에대한 로직을 가져가는게  좋은 어플리케이션 설계에 가까운걸까요..?? 
리뷰님의 의견이 듣고싶습니다 ㅠㅠ

2023-07-21 07:56 UTC, thalals reviewed
리뷰 피드백 반영입니다 🙇‍♂️

2023-07-21 07:56 UTC, thalals commented on src/test/java/nextstep/subway/unit/SectionFacadeTest.java
> +public class SectionFacadeTest {
Service : Repository = 1 : 1 구조를 좋아하기 때문에 Facade 레이어를 Service 앞단에 넣어 LineServiceTest 대신 동일한 기능을 수행하는 SectionFacade를 Test 했습니다 🙌🏻

2023-07-21 14:10 UTC, testrace commented on src/test/java/nextstep/subway/unit/SectionFacadeMockTest.java
> +        Assertions.assertThat(line.getSections().getSections()).hasSize(2);
디미터 법칙을 준수하도록 개선하면 어떨까요?
```suggestion
        Assertions.assertThat(line.getSections()).hasSize(2);
```

2023-07-21 14:10 UTC, testrace commented on src/test/java/nextstep/subway/unit/group/SectionGroupTest.java
테스트에 실패하네요 😢 
커밋 전에 테스트를 수행해 보시면 좋을 것 같아요
<img width="355" alt="image" src="https://github.com/next-step/atdd-subway-path/assets/8064743/157caac5-260b-4d25-ba7b-2ad8450503d1">

2023-07-21 14:10 UTC, testrace commented on src/main/java/nextstep/subway/entity/Section.java
> +    private boolean isDownEndPointSection;
참고만 해주세요 😃 
종점역 ID를 별도로 관리한다고 해도 반복분을 통해서 검증하는 과정도 항상 필요할 것 같은데요 
지하철 노선이라는 도메인에서 구간이 많다 하더라도 성능 이슈를 일으킬 만큼 많지 않을거라 생각해요 
응답 속도에 대한 요구사항이 있는 것이 아니니 성능 이슈는 지금 걱정하지 않으셔도 괜찮을 것 같아요
상태 변경에 대한 로직은 상태를 가장 잘 알고 있는 객체가 수행을 해야 응집도가 높아지니 좋은 설계에 가까워질 수 있을 것 같아요

2023-07-21 14:11 UTC, testrace requested changes
안녕하세요 형민님 😃 
피드백 반영 잘해주셨는데 실패하는 테스트가 있네요 😢 
질문에 대한 답변도 코멘트로 남겼으니 확인해 주시고 다시 리뷰 요청해 주세요

2023-07-23 13:22 UTC, thalals commented on src/test/java/nextstep/subway/unit/SectionFacadeMockTest.java
> +        Assertions.assertThat(line.getSections().getSections()).hasSize(2);
넵! 좋은의견 감사드립니다!

2023-07-23 13:22 UTC, thalals commented on src/test/java/nextstep/subway/unit/group/SectionGroupTest.java
세상에 😅다시 체크해보겠습니다..!

2023-07-23 14:03 UTC, thalals commented on src/main/java/nextstep/subway/entity/Section.java
> +    private boolean isDownEndPointSection;
한번 더 생각해보면 또그렇군요 의견 정말 감사드립니다 !! 정말 큰 도움이 되었어요 👏

2023-07-24 03:33 UTC, testrace approved these changes
안녕하세요 형민님 😃 
피드백 빠르게 반영해 주셨네요 👍 
다음 단계도 화이팅입니다 🔥

2023-07-24 03:33 UTC, merged