🚀 1단계 - 지하철 구간 추가 기능 개선
next-step/atdd-subway-path pull request #612
Opened 2023-07-19 07:05 UTC by JerryK026

안녕하세요~ 1단계 과제 구현해 보았습니다.

이번 과제를 하면서 느낀 점들은 다음과 같습니다.
- 상태코드를 400으로 고정해서 받으니까 다른 예외인데도 불구하고 테스트 통과라고 여겨졌습니다
	- 테스트할 때는 에러 메시지도 테스트하도록 해야할 듯합니다
- 유닛테스트인데 뭔가 객체들 끼리 얽혀있어서 뭔가 시나리오 테스트처럼 되었는데 이것도 단위테스트라고 볼 수 있을지 모르겠습니다
- ❗ 처음에 추가된 기능은 세부 내용이라 관심사가 아니라 인수테스트는 따로 작성하지 않았으나, 이 테스트를 읽을 기획자나 FE 개발자 입장에서 이 호출 결과로 궁금할 건 뭘까? 라는 입장에서 다시 생각해 예외 상황에 대해서 추가로 작성했습니다
	- 협업할 때는 기능이 변경될 때 FE 분들에게 이러한 기능이 변경될 것 같은데 혹시 FE 관점에서 이 변경에 대해서 문서화 되었으면 하는 부분은 어떤 부분일까요? 하고 물어보는 게 좋을 듯 하네요?
- 서비스 레이어 테스트는 해보지 않아서 시도해 보았는데 생각보다 힘이 들었습니다. 세부 내용은 코멘트에서 다루도록 하겠습니다!
- 인수테스트와 단위테스트가 생각보다 많이 중복됨을 느낄 수 있었습니다
- 처음에는 순서를 찾는 로직이 복잡해지는 걸 스키마에 sequence라는 필드를 넣어 해결하려고 했는데, 생각해 보니 중간에 값이 추가되는 경우 그 뒤 내용들이 전부 밀려야 해서 한 노선에 구간이 많아지면 db 부하가 커질 것이라는 생각이 들었습니다. 하지만, 또 기능 구현을 하다 생각해 보니 불필요한 로직이 많이 생겨서 WAS 단에 CPU 리소스가 커지는 건 아닌가? 하는 생각이 들어 현업에서는 이런 경우 둘다 작성해 보고 부하테스트를 통해 더 효율적인 방안을 선택하겠구나 하는 생각이 들었습니다.

뭔가 주절주절 내용이 많았네요 ㅋㅋ 리뷰받고 싶은 부분은 ❗나 코멘트로 남겨두었습니다. 나머진 제 개인적인 회고이니, 이 부분만 봐주시면 감사하겠습니다!

2023-07-19 07:13 UTC, JerryK026 commented on src/test/java/nextstep/subway/section/SectionTest.java
> +        Section oleSection = aSection().withDownStation(new Station(3L, 지하철역)).build();
지금 보니 Station 생성도 중복되는 부분이 많은데 이것도 빌더로 빼도 좋을 것 같네요 👀

2023-07-19 07:13 UTC, JerryK026 commented on src/test/java/nextstep/subway/section/SectionServiceTest.java
> +//    }
서비스를 테스트하다 보니 어려운 점들이 몇개 생겨 그 부분들에 대해 적어보았습니다.
- SectionRepository를 사용해서 Section을 저장하는 게 아니라, cascade를 사용해 저장하기 때문에 SectionRepository를 모킹할 수 없다
- Section과 Line이 양방향 관계이기 때문에, Line을 최초 생성할 때 Section을 생성할 수 없고, 이후에 주입하는 형식으로 만들어야 하는데, thenReturn으로 Sections가 null인 상태로 생성한 이후, 그 이후의 동작을 제어하기 어렵다
- db 저장 상태에 의해 로직이 좌우되는 경우, Service 만으로는 테스트하기 어렵다. 이 경우는 인수테스트에서 다루어야 하나?

리뷰어님이시라면 이 부분을 어떻게 핸들링하실지 궁금합니다!

2023-07-19 07:13 UTC, JerryK026 commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +        var lineCreateResponse = 지하철_노선_생성_요청(신분당선, "bg-red-600", 지하철역, 새로운지하철역, 10);
bg-red-600도 중복적으로 등장하는데 이것도 상수화하는게 좋아 보이네요 👀

2023-07-19 07:13 UTC, JerryK026 commented on src/main/java/nextstep/subway/section/Sections.java
> +    public void add(Section section) {
Line에 Section이 Empty인 경우에 대해서 체크하지 않는데요, 현재 Line 생성시 Section도 자동으로 하나 추가된다는 걸 이미 알고 있어서 그렇습니다.

하지만 테스트하다 보니 종종 여기에 대해서 불안감이 생길 때도 있고, 해당 도메인에 익숙하지 않은 사람을 위해서 혹은 요구사항 변경에 앞서 미리 Empty에 대한 방어코드를 작성하는 것도 나쁘지 않겠다는 생각이 듦과 동시에 이건 YAGNI를 위반하는 것이라는 생각이 듭니다. 리뷰어님께서는 어떻게 생각하시나요? 🤔

2023-07-20 03:21 UTC, hjhello423 requested changes
안녕하세요 서경님 😀
요청 주신 pr에 코멘트들을 달아 두었습니다!
코멘트들을 확인해 보시고 다시 한번 리뷰 요청 주세요!

2023-07-20 03:21 UTC, hjhello423 commented on src/main/java/nextstep/subway/common/exception/GlobalExceptionHandler.java
> +    }
현재 코드로 봤을 때는 응답 타입에 `?` 대신 `BaseExceptionResponse`로 정의해도 되지 않을까요? 🤔

2023-07-20 03:21 UTC, hjhello423 commented on src/main/java/nextstep/subway/common/exception/ResourceNotFoundException.java
> +    }
이곳에서 사용되는 메시지들은 상수화 시킬 수 있을 것 같아요.

2023-07-20 03:21 UTC, hjhello423 commented on src/main/java/nextstep/subway/line/Line.java
> +    private Sections sections;
Sections 👍

2023-07-20 03:21 UTC, hjhello423 commented on src/main/java/nextstep/subway/line/LineService.java
> +        );
저는 오히려 명확하게 어떤 값들을 사용하는지 표시해 주는 쪽이 가독성이 더 좋다고 생각해요. 
```suggestion
        Station upStation = findStationById(lineRequest.getUpStationId());
        Station downStation = findStationById(lineRequest.getDownStationId());
        Section section = new Section(upStation, downStation, lineRequest.getDistance());
        
        Line line = new Line(lineRequest.getName(), lineRequest.getColor(), section);
```

2023-07-20 03:21 UTC, hjhello423 commented on src/main/java/nextstep/subway/line/LineResponse.java
> +    private List<Station> stations;
response에서 `Station` 도메인을 응답에 사용하고 있네요.
어떤 문제점들이 있을까요? 🤔

2023-07-20 03:21 UTC, hjhello423 commented on src/main/java/nextstep/subway/section/Sections.java
> +        }
`Sections#add` 메서드가 커진 것 같아요.
리팩토링할 수 있지 않을까요?

2023-07-20 03:21 UTC, hjhello423 commented on src/test/java/nextstep/subway/line/LineBuilder.java
> +public class LineBuilder {
test 코드에서만 사용하는군요.
혹시 product 코드에서 정의 안 하신 이유가 있으신가요?

2023-07-20 03:21 UTC, hjhello423 commented on src/test/java/nextstep/subway/line/LineTestStepDefinition.java
> +            .when().get("/lines/" + id)
path param을 조금 더 깔끔하게 전달할 수 있는 방법을 docs에서 찾을 수 있어요. 😀
https://github.com/rest-assured/rest-assured/wiki/Usage#path-parameters

2023-07-20 03:21 UTC, hjhello423 commented on src/test/java/nextstep/subway/unit/LineTest.java
> -    }
`Line`에 대한 테스트가 삭제되었네요?
따로 추가된 내용이 없어 보이는데 다시 추가되면 좋을 것 같아요

2023-07-20 03:21 UTC, hjhello423 commented on src/test/java/nextstep/subway/unit/LineServiceMockTest.java
> -public class LineServiceMockTest {
`LineServiceMockTest`도 제거되고 추가되지 않은 것 같아요.
실습 단계의 미션 요구 사항에 따르면 아래 2가지 사항을 모두 작성해 주셔야 합니다!
* 구간 서비스 단위 테스트 with Mock (LineServiceMockTest)
* 구간 서비스 단위 테스트 without Mock (LineServiceTest)

2023-07-20 03:21 UTC, hjhello423 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +public class LineAcceptanceTest {
1단계 미션 요구사항에는 `변경된 스펙 - 구간 추가 제약사항 변경`에 대한 내용이 있는데요.
미션 요구 사항의 내용들이 인수 테스트로 작성되어야 하지 않을까요?
해당 변경 사항에 대한 테스트가 추가되면 좋을 것 같아요. 😀

2023-07-20 03:28 UTC, hjhello423 commented on src/test/java/nextstep/subway/section/SectionServiceTest.java
> +//    }
`SectionServiceTest`에서는 Mockito를 활용하는 것이 아닌 실제 객체를 이용하는 방향으로 테스트해 주시면 됩니다. 😀

만약 Mockito를 이용하시는 방향에서 궁금한 점이 있다면 우선 `SectionService#createSection`는 아래와 같은데요.
```
 public SectionResponse createSection(final Long lineId, final SectionRequest request) {
        Line line = findLineById(lineId);
        Station upStation = findStationById(request.getUpStationId());
        Station downStation = findStationById(request.getDownStationId());

        line.addSection(upStation, downStation, request.getDistance());

        return new SectionResponse(line.getLastSection());
    }
```

그럼 `lineRepository.findById()`, `stationRepository.findById()`를 스터빙하며 되지 않을까요?

2023-07-20 03:33 UTC, hjhello423 commented on src/main/java/nextstep/subway/section/Sections.java
> +    public void add(Section section) {
비즈니스 요구사항에 따라 판단할 수 있을 것 같아요.
만약 Line이 추가될 때 Section이 없을 수 있다면 말씀하신 validation 로직은 추가되는 게 맞다고 생각됩니다.
하지만 요구사항에서 Line이 추가될 때 Section이 추가되는 게 명확하다면 팀 내 합의하에 validation 로직을 제거할 수 있을 것 같아요.
다만 비즈니스에서 Section이 empty인 경우가 생길 수 있다면 추가되는 게 맞다고 생각 들어요.

2023-07-20 03:39 UTC, hjhello423 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +public class LineAcceptanceTest {
> ❗ 처음에 추가된 기능은 세부 내용이라 관심사가 아니라 인수테스트는 따로 작성하지 않았으나, 이 테스트를 읽을 기획자나 FE 개발자 입장에서 이 호출 결과로 궁금할 건 뭘까? 라는 입장에서 다시 생각해 예외 상황에 대해서 추가로 작성했습니다
협업할 때는 기능이 변경될 때 FE 분들에게 이러한 기능이 변경될 것 같은데 혹시 FE 관점에서 이 변경에 대해서 문서화 되었으면 하는 부분은 어떤 부분일까요? 하고 물어보는 게 좋을 듯 하네요?

여기서 답변 드리겠습니다!

미션의 요구 사항이 변화했다면 해당 변경사항에 대한 테스트 코드는 추가되어야 할 것 같습니다. 다만 이해관계에 따라 인수 테스트 또는 통합 테스트, 서비스 테스트 등으로 구현하는 방법은 달라질 수 있을 것 같아요.
이번 강의는 ATDD를 다루는 만큼 인수 테스트로 작성하는 방향으로 진행해 보면 어떨까요?

문서화에 대한 부분은 최대한 많은 필요 정보를 담는 것이 필수라고 생각해요.
서경님이 아무것도 모르는 상태에서 제공된 문서만 보고도 비즈니스 흐름, API에 대한 이해가 되어야 하지 않을까요?

2023-07-20 05:19 UTC, JerryK026 commented on src/test/java/nextstep/subway/section/SectionServiceTest.java
> +//    }
@hjhello423 아~ 생각해보니 createSection에서 Section이 영속 계층에 저장되는 것은 관심사가 아니기 때문에 lineRepository와 stationRepository만 모킹해주면 되는거군요! 감사합니다 🙇

2023-07-20 05:34 UTC, JerryK026 commented on src/main/java/nextstep/subway/line/LineResponse.java
> +    private List<Station> stations;
@hjhello423 음...일단 Line의 Response인데 Station 변경사항에 의존한다는 위험이 있다고 생각해요 API라는 것은 자주 변경되면 안 되는데 의존하는 부분이 많아지면 그만큼 변경될 가능성이 높기도 하고, 애초에 다른 도메인이기도 하고요!

여기에 Station을 직접 받은 이유는 Station 정보를 반환해야 해서 그대로 노출시키면 좋겠다! 이런 생각을 했었는데 이런 설계도 조금 더 생각해 보면 좋았겠네요! 감사합니다 ㅎㅎㅎ 🙇

2023-07-20 05:43 UTC, JerryK026 commented on src/test/java/nextstep/subway/line/LineBuilder.java
> +public class LineBuilder {
개인적으로 Builder를 사용했을 때 param을 빠뜨리지 않기 위해 이 객체 내부에 대해서 알아야 하고, 변경에 약하다는 생각이 들어서입니다 :D

1. 파라미터가 누락되는 경우가 있다 : 필요한 생성자만 만들어서 사용하면, 코드를 짜는 단계에서 이 객체에 대해 필요한 것들에 대해 가이드해주기 때문에 편리하다고 생각했습니다. 빌더에 대해 순서를 지정해주는 방법은 코드도 방대해지고 손이 많이 가는 기분이라는 생각이 들었습니다. 내부 필드가 변경되면 그 순서에 대해서도 일일이 변경해 주어야 하고요.

2. 변경에 약하다 : 이것도 파라미터 누락과 비슷한 맥락인데요, 어떠한 객체에 필드가 추가되는 경우, 생성자의 경우 기존 코드들에 대해 컴파일 에러를 반영합니다. 그러나 빌더의 경우 컴파일러에서 잡아주지 않기 때문에 불편하다고 느꼈습니다. CustomBuilder의 경우 위에서 언급한 이유와 같이 불편하다고 느꼈습니다 ㅎㅎ

그러나 TestCode의 경우 depth 자체가 낮기도 하고, 관심사가 아닌 부분들은 과감하게 채워넣지 않아도 된다는 부분에서 테스트에서 적극적으로 사용하려고 하고 있습니다 :D

2023-07-20 05:53 UTC, JerryK026 commented on src/test/java/nextstep/subway/unit/LineTest.java
> -    }
앗 이건 샘플 내용 같네요 한 번 추가해보도록 하겠습니다 👍

2023-07-20 05:54 UTC, JerryK026 commented on src/test/java/nextstep/subway/unit/LineServiceMockTest.java
> -public class LineServiceMockTest {
앗 이걸 놓치고 있었네요 😅 시도해 보겠습니다!

2023-07-20 05:56 UTC, JerryK026 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +public class LineAcceptanceTest {
답변 감사합니다! 해당 내용이 도메인에서 테스트되고 있기에 테스트 중복이 많이 생기는 것 같아 인수테스트엔 작성하지 않았었습니다! 말씀 주신대로 이번 인수테스트를 작성해서 다시 올려보도록 하겠습니다 ㅎㅎㅎ

2023-07-20 14:47 UTC, JerryK026 commented
@hjhello423 안녕하세요 홍준님~ 리뷰해 주신 부분들 반영해 보았습니다! 이번에 신경 쓴 부분은 Sections의 도메인 부분들인데요, 이 부분들에서 공통된 부분들이 조금씩 나와서 어떻게 해야할까 고민을 좀 해보았습니다.

2023-07-20 14:58 UTC, JerryK026 reviewed
어떤 건 equals()와 hashCode()를 구현한 것도 있고 안 한 것도 있는데 주로 자료구조를 다룰 때만 재정의한 것 같습니다. 이건 답을 구하는게 아니라 개인적인 선호에 대해서 궁금한 건데, 리뷰어님께서는 일관성이 떨어진다고 생각하시나요?

2023-07-20 14:58 UTC, JerryK026 commented on src/main/java/nextstep/subway/section/Sections.java
> +        }
이 메서드 뿐만 아니라, getSections(), getLastSection() 메서드를 보면 다음과 같은 로직이 반복되는 것을 볼 수 있습니다.
```
        Map<Station, Section> upSectionMap = new HashMap<>();
        for (Section oldSection : sections) {
            upSectionMap.put(oldSection.getUpStation(), oldSection);
```
그런데 getStationToUpSectionMap()의 경우 반복문 최적화를 위해 이 순회를 돌리는 도중에 검증 로직을 넣어놓아서 중간에 추가된 로직 때문에 추출하기가 어려워서 차라리 이 부분을 인터페이스로 뽑아서 EmptyOperator implements Operator, ValidateOperator implements Operator 이런 식으로 구현할까도 생각했지만, 중복 수가 딱히 많지 않다고 판단해서 그냥 두었습니다.

2023-07-20 14:58 UTC, JerryK026 commented on src/main/java/nextstep/subway/section/Sections.java
> +        }
여기 이 부분도 getLastSection(), updateSectionIfInsert()도 마찬가지로 반복되나 위와 같은 이유로 분리하지 않았습니다.

2023-07-20 14:58 UTC, JerryK026 reviewed
어떤 건 equals()와 hashCode()를 구현한 것도 있고 안 한 것도 있는데 주로 자료구조를 다룰 때만 재정의한 것 같습니다. 이건 답을 구하는게 아니라 개인적인 선호에 대해서 궁금한 건데, 리뷰어님께서는 일관성이 떨어진다고 생각하시나요?

2023-07-21 02:29 UTC, hjhello423 commented on src/test/java/nextstep/subway/line/LineBuilder.java
> +public class LineBuilder {
Builder를 product 코드에서 사용한다면,
서경님이 말씀하신 '필요한 것들에 대한 가이드' 그러니까 필수 값들에 대한 validation을 builderdml `build()`를 호출할 때 처리해 줄 수 있지 않을까요?

2023-07-21 02:32 UTC, hjhello423 commented on src/test/java/nextstep/subway/unit/LineTest.java
> -    }
`Line#update` 같은 메서드들은 테스트가 필수로 만들어져야 한다고 생각 들어요!
그리고 저는 다른 객체에 위임하는 형태이더라도 중요 메서드에서는 테스트 코드를 작성하고 있어요.

2023-07-21 02:53 UTC, hjhello423 approved these changes
안녕하세요 서경님
코멘트들 하나하나 꼼꼼하게 반영해 주셨군요. 👍
이만 머지하도록 하겠습니다! 다음 step도 화이팅하세요!! 🔥

2023-07-21 02:53 UTC, hjhello423 commented on src/main/java/nextstep/subway/station/Station.java
> +    }
> 어떤 건 equals()와 hashCode()를 구현한 것도 있고 안 한 것도 있는데 주로 자료구조를 다룰 때만 재정의한 것 같습니다. 이건 답을 구하는게 아니라 개인적인 선호에 대해서 궁금한 건데, 리뷰어님께서는 일관성이 떨어진다고 생각하시나요?

여기서 답변드려요!
우선 저도 모든 객체에 equals, hashcode를 재정의 할 필요는 없다고 생각해요.
필요한 경우에만 정의하는 편입니다. 

더해서 equals와 hashcode에 대해 깊게 파고 들어가 보면 더 다양한 문제들을 만날 수 있을 거예요.
예를 들면 jpa에서 equals() 정의 시에 만날 수 있는 문제들, 대량의 트래픽을 받는 서비스에서의 hashCode() 정의 방법 등등이 있어요.
나중에 한번 찾아보시면 도움이 되실 것 같습니다! 😀

2023-07-21 02:58 UTC, hjhello423 commented on src/main/java/nextstep/subway/section/Sections.java
> +        }
흠 저도 좀 고민이 되네요.
우선 따로 피드백을 드리지는 않았지만 지금 메서드는 [객체지향 생활 체조 소개 페이지](https://edu.nextstep.camp/s/c30VOHNP/ls/8tTBk5Yp)에 보시면 1번 규칙을 만족하지 않고 있어요.
이런 부분을 먼저 리팩토링해보면 도움이 되지 않을까요?

2023-07-21 03:01 UTC, merged

2023-07-21 04:22 UTC, JerryK026 commented on src/main/java/nextstep/subway/section/Sections.java
> +        }
아~ 맞네요 생각해보니 그걸 놓치고 있었군요! 우선 그럼 공부해보는 거니까 다음 미션때는 반영해보도록 하겠습니다 감사합니다!

2023-07-21 04:24 UTC, JerryK026 commented on src/test/java/nextstep/subway/unit/LineTest.java
> -    }
@hjhello423 감사합니다! 다시 생각해 보니까 대부분 위임하는 로직이라 할지라도, 메서드의 중요성 혹은 복잡성에 따라 테스트할 수도 있겠다는 생각이 드네요! 이 부분은 제가 빠뜨렸는데 다음 미션 때 반영해보도록 하겠습니다!

2023-07-21 04:26 UTC, JerryK026 commented on src/test/java/nextstep/subway/line/LineBuilder.java
> +public class LineBuilder {
@hjhello423 오호 build()에서 validation을 해줄 수도 있군요! 저는 상태값 주입 순서 조정하는 방법 외에는 생각 못해봤었는데 그런 방법도 있네요. 그 부분도 코드가 길어져서 좀 꺼렸던 거긴 한데, 필요하다면 사용해볼 수 있을 것 같습니다. 감사합니다 :D