1단계 - 지하철 구간 추가 기능 개선
next-step/atdd-subway-path pull request #628
Opened 2023-07-22 07:35 UTC by yyy9942

안녕하세요 리뷰어님!
요구사항이 생각보다 어려워서 시간이 걸렸네요.
리뷰 잘부탁드립니다.

2023-07-23 05:34 UTC, pch8388 requested changes
안녕하세요 
2주차 미션을 함께 하게 된 권승철입니다 🙇 
새벽에 회사 작업이 있어서 리뷰가 늦어 죄송합니다 😭 
1단계 미션 잘 수행해주셨는데, 요구사항과 맞지 않는 부분이 있어요 😢 
코멘트 드린 부분들에 대해 확인해주시고 리뷰요청 해주세요 🔥

2023-07-23 05:34 UTC, pch8388 commented on src/test/java/nextstep/subway/section/LineSectionsUnitTest.java
> +package nextstep.subway.section;
다른 테스트 클래스들과 패키지 구조를 정하는 기준이 다른 것 같아요 😅 
acceptance / unit / section 형태라 코드를 읽는 사람에게 혼란을 줄 수 있을 것 같습니다

2023-07-23 05:34 UTC, pch8388 commented on src/test/java/nextstep/subway/section/LineSectionsUnitTest.java
> +class LineSectionsUnitTest {
unit 패키지에 `LineTest.java` 는 그냥 두시고 새로 클래스를 만드신 이유가 있을까요? 🤔 
어떤 기준으로 테스트 클래스를 생성하셨나요? 🤔 
(기준점이 있어서 이렇게 하신거면 `LineTest.java` 는 삭제해도 될 것 같아요 😄 )

2023-07-23 05:34 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Sections.java
> +    @JoinColumn(name = "line_id")
<img width="465" alt="스크린샷 2023-07-23 오후 1 28 07" src="https://github.com/next-step/atdd-subway-path/assets/17218212/ee997f4f-3845-44b3-9a87-7351476cacda">

`Section` 저장할때마다 `update`가 발생합니다 😢 
아래와 같이 설정하면 방지할 수 있습니다. (`Section`은 항상 `Line 에 포함되기 때문에 cascade 옵션을 줘도 될 것 같아요 😄 )
```suggestion
@OneToMany(mappedBy = "line", cascade = CascadeType.PERSIST)
```

2023-07-23 05:34 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Sections.java
> +            if (section.getDownStation().equals(matchedSection.getDownStation())) {
[객체지향생활체조](https://edu.nextstep.camp/s/ZlcCZQ2Y/ls/USFEu0qR)

> 규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.

학습을 위해 객체지향생활체조 원칙을 지켜보도록 말씀드리고 있습니다 😅

2023-07-23 05:34 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Sections.java
> +            if (section.getDownStation().equals(matchedSection.getDownStation())) {
`구간의 하행역이 동일하다`는 메서드를 `Section`이 가지도록 하면 어떨까요? 🤔

2023-07-23 05:34 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Sections.java
> +    public List<Section> addSection(Section section) {
`addSection` 메서드 아래 구현들을 전체적으로 메서드 추출을 통해 추상화 하면 어떨까요? 🤔 

> 클린코드
작게 만들어라!
... 함수는 100줄을 넘어서는 안 된다. 아니 20줄도 길다.

2023-07-23 05:34 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Sections.java
> +        System.out.println("sections>>>" + this);
`System.out.println` 은 되도록 자제해주세요 😄 
개발할때는 상관이 없지만 깜빡하고 그냥 운영에 배포되는 경우도 있더라구요 😢 
로깅 프레임워크를 사용하면 좀 더 간편하게 제어가 가능해서 개인적으로는 개발 중 간단한 로그를 찍어볼때도 로깅 프레임워크를 쓰는 편입니다

2023-07-23 05:34 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Sections.java
> +        if (cursor == null) {
sections 가 비어있는 경우라면 바로 `sections.isEmpty()`를 호출해서 봐도 될 것 같아요 😄 
`addSection`일때는 `isEmpty` 를 호출하셨었는데, 이런 부분에서도 일관성을 챙기는 게 좋다고 생각합니다(구간이 존재하지 않는 것을 확인한다는 점에서 동일한 의도의 코드라고 생각됩니다)

2023-07-23 05:34 UTC, pch8388 commented on src/main/java/nextstep/subway/section/SectionService.java
> +    private static boolean hasMinimumSection(Line line) {
사용하지 않는 메서드인것 같아요 👀

2023-07-23 05:34 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Section.java
> +  public void setUpStation(final Station upStation) {
[객체지향생활체조](https://edu.nextstep.camp/s/ZlcCZQ2Y/ls/USFEu0qR)

> 규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.

2023-07-23 05:34 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Sections.java
> +        throw new IllegalArgumentException();
메시지를 넣어주신 부분과 안넣어주신 부분이 있는데, 이런 곳들에도 어떤 사유로 예외가 발생했는 지 메시지를 추가하면 어떨까요? 💭

2023-07-23 05:34 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Sections.java
> +        final Optional<Section> matched = findByUpSection(section.getDownStation());
하행역이 일치하면서 중간에 들어가는 경우도 가능해야 합니다 😅 
<img width="407" alt="스크린샷 2023-07-23 오후 2 21 49" src="https://github.com/next-step/atdd-subway-path/assets/17218212/daeb267d-a113-4802-9a9c-31f605ec7ccf">

2023-07-23 05:34 UTC, pch8388 commented on src/test/java/nextstep/subway/SectionAcceptanceTest.java
> +        StationResponse 서현역 = StationTestHelper.createStation("서현역");
인수테스트는 한글메서드로 표현력을 높여도 좋다고 생각합니다 😄 
다른곳에 `var`를 쓰신것처럼 인수테스트에도 쓰면 어떨까요? 
개인적으로 인수테스트는 시나리오 검증에 대해서 집중해야 하기 때문에 다른 외부적인 요소는 최대한 감추는 게 좋다고 생각합니다

2023-07-23 05:34 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Sections.java
> +        // 상행역과 매치되는 역을 찾는다.
주석은 잘못써도 컴파일 타임이나 런타임에 아무런 문제가 없기 때문에 관리되지 않는 경우가 많은 것 같아요 😢 
따라서, 최대한 없애고, 복잡한 history 를 가졌거나, 계산식이 쉽게 이해할 수 없거나 할때, 추가를 해주는 것이 적절하다고 생각합니다 😅 

> 클린코드의 한 구절입니다.
C3 : 중복된 주석 코드만으로 충분한데 구구절절 설명하는 주석이 중복된 주석이다. ...(중략)... 주석은 코드만으로 다하지 못하는 설명을 부언한다.

2023-07-23 05:34 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Sections.java
> +        if (matchedDownStation.isPresent()) {
Optional - isPresent 형태를 다른 방향으로 풀어낼 수 있을 지 고민해보면 좋을 것 같아요 😄 
조건이 늘어날수록 가독성이 떨어진다고 생각합니다

2023-07-23 05:35 UTC, pch8388 commented
ATDD 사이클을 잘지키고 계신지 확인하기 위해 되도록이면 커밋을 나누어 하시는 것을 추천드리고 있습니다 😄

2023-07-23 06:02 UTC, yyy9942 commented on src/main/java/nextstep/subway/section/Sections.java
> +        final Optional<Section> matched = findByUpSection(section.getDownStation());
![image](https://github.com/next-step/atdd-subway-path/assets/46917538/a50b7781-0281-46fb-8f43-0ea0b1214294)
위 요구사항에는 없는 것으로 보이는데요, 원래 이게 가능해야하던건가요?

2023-07-23 06:06 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Sections.java
> +        final Optional<Section> matched = findByUpSection(section.getDownStation());
<img width="289" alt="스크린샷 2023-07-23 오후 3 03 16" src="https://github.com/next-step/atdd-subway-path/assets/17218212/05e94f9c-066d-4819-b62d-5b61bb66c2eb">

`기존 구간의 역을 기준` 이라고 되어있어서.. 여기서 기존구간의 역이라는 것이 상행역만을 뜻하지는 않는 거였습니다 😭 
그림에 없기도 하고 요구사항 정의가 조금 불명확했던 것 같네요 😢  혼선을 드려 죄송합니다 🙇 
그림에 대한 수정요청은 드렸습니다

2023-07-23 07:49 UTC, yyy9942 commented on src/test/java/nextstep/subway/section/LineSectionsUnitTest.java
> +class LineSectionsUnitTest {
`Sections`라는 일급 컬랙션은 `Line`이라는 객체에게 의존하고 있고, `Line` 객체는 이 `Sections`라는 객체에게 요청을 바이패스로 넘겨주는 역할을 많이 합니다.
그렇기 때문에 `Line`과 `Sections`를 따로 테스트하는건 단위테스트로 의미가 없다고 판단하여 이렇게 테스트명을 지었습니다~

LineTest는 지우겠습니다

2023-07-24 08:03 UTC, yyy9942 commented on src/main/java/nextstep/subway/section/Section.java
> +  public void setUpStation(final Station upStation) {
해당페이지 권한이 없는거같습니다 ㅠㅠ

2023-07-24 08:17 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Section.java
> +  public void setUpStation(final Station upStation) {
next step 로그인 상태에서 보시면 확인 가능하실거에요 😢

2023-07-24 08:20 UTC, yyy9942 commented on src/main/java/nextstep/subway/section/Section.java
> +  public void setUpStation(final Station upStation) {
로그인된 상태인데 아래와 같이 나옵니다
![image](https://github.com/next-step/atdd-subway-path/assets/46917538/b53b76bd-ee3a-4427-b091-d01e8813527a)

2023-07-24 08:31 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Section.java
> +  public void setUpStation(final Station upStation) {
앗 확인해보겠습니다.

2023-07-24 08:32 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Section.java
> +  public void setUpStation(final Station upStation) {
https://edu.nextstep.camp/s/c30VOHNP/ls/8tTBk5Yp

위 링크로 가시면 될 것 같습니다 😢 
이전 기수 링크를 잘못드렸네요

2023-07-24 09:56 UTC, yyy9942 commented on src/test/java/nextstep/subway/SectionAcceptanceTest.java
> +        StationResponse 서현역 = StationTestHelper.createStation("서현역");
저는 displayName으로 테스트를 명확하게 드러내고, 한글메서드명을 사용하는걸 지양하고자하는데요, 오히려 영어는 camel case로 작성할 수 있지만 한글은 snake case로 작성해야해서 가독성이 떨어지더라고요. 가독성이 떨어진다고 느껴질 때 한글로 작성해도 좋을것 같습니다.

2023-07-24 13:08 UTC, pch8388 approved these changes
리팩토링 잘해주셨습니다 👏 👏 
남겨드린 코멘트 참고해주시고, 다음 단계 진행해주세요 🚀

2023-07-24 13:08 UTC, pch8388 commented on src/test/java/nextstep/subway/SectionAcceptanceTest.java
> +        StationResponse 서현역 = StationTestHelper.createStation("서현역");
인수테스트 내에서 한글메서드 네이밍 사용을 추천드리는 이유는 다음과 같습니다 (개인적인 생각이니 참고만 해주셔도 될 것 같아요 😄 )

인수테스트는 개발자만을 위한 것은 아니기 때문에 시나리오 흐름에 대한 가독성에 초점을 맞추는 것이 좋습니다.
(따라서, then 부분도 메서드 추출하는 것을 추천드립니다.)
> 클린 애자일의 구절을 인용하면
인수테스트는 업무 분석가와 QA, 개발자가 함께 힘을 모아 작성한다.

개인적으로 항상 안내드리는 부분이라 조금 더 이야기하면, 메서드 위에 주석으로 설명한 부분이 거의 그대로 메서드 내부에 들어가면 좋다고 생각합니다. (다른 세부사항들은 다 감추고, 시나리오에 집중할 수 있도록)
주석 내용이 메서드 내부에 모두 들어가면 주석을 삭제하는 것으로 리뷰를 드리는 편입니다 😃

2023-07-24 13:08 UTC, pch8388 commented on src/main/java/nextstep/subway/line/LineService.java
> +          lineRequest.getColor()));
현재까지의 요구사항으로는 `노선`은 `구간`없이 존재할 수 없을 것 같습니다. 🤔 
`노선`에 `구간`을 추가하기 위해서는 추가하려는 `구간의 상/하행역 중 하나라도 노선에 포함`되어야 하기 때문입니다.
따라서, `노선`을 생성할때 조금 더 완전한 상태로 생성되는 것이 좋다고 생각해요 😅

2023-07-24 13:08 UTC, pch8388 commented on src/main/java/nextstep/subway/line/LineService.java
> +          sectionRepository.saveAll(line.addSection(upStation, downStation, lineRequest.getDistance()));
```suggestion
line.addSection(upStation, downStation, lineRequest.getDistance());
```
`cascade`옵션을 추가해주셔서 이렇게만 해도 저장이 됩니다 😄

2023-07-24 13:08 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Sections.java
> +    private SectionAddStrategy findAddStrategy(Section section) {
구현잘해주셨네요 👍 👍

2023-07-24 13:08 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Sections.java
> +        }
조건이 늘어날때마다 if 추가할수도 있을 것 같고, 해당 클래스가 스스로 자신이 처리할 수 있는 조건인지를 체크하도록 해도 될 것 같아요  👍

2023-07-24 13:08 UTC, pch8388 commented on src/main/java/nextstep/subway/section/Sections.java
> +        throw new IllegalArgumentException("추가할 수 있는 조건이 아닙니다");
지금은 예외에 대한 응답 메시지 처리를 하고 있지 않지만, 발생한 예외에 대한 메시지를 client 에게 전달할때를 위해 예외 메시지를 조금 더 친절하게 만들어야 할 수도 있을 것 같아요 😄 
(예외 핸들러를 추가하고, 인수테스트에서 실패 케이스에 대한 검증을 추가해봐도 좋을 것 같아요)

2023-07-24 13:08 UTC, merged