3단계 - 경로 조회 기능
next-step/atdd-subway-path pull request #647
Opened 2023-07-26 07:09 UTC by Eunhee0119

안녕하세요. 홍준님 :D
리뷰 요청드립니다! 
이번 미션은 생각보다 어려웠어요ㅠ TDD사이클도 잘 지킨것이 맞는지 의문이 듭니다 🥲

**요구사항**
출발역과 도착역을 입력하여 경로 조회

**예외 케이스**
출발역과 도착역이 동일할 경우
연결되지 않은 경로를 조회할 경우
출발역이나 도착역이 존재하지 않는 경우

2023-07-27 01:35 UTC, hjhello423 commented
outside in, inside out 방식 중 어떤 방식을 선택해서 민션을 진행해 주셨나요?
그리고 진행하면서 느낀점이나 어려웠던 점들을 정리해서 이곳에 기록해두면 나중에도 도움이 될 것 같아요. 😀

2023-07-27 01:37 UTC, hjhello423 requested changes
안녕하세요 은희님 😀
코드들이 대부분 정렬되었네요. 👍
몇 가지 코멘트를 달아두었는데요. 확인해 보시고 다시 한번 리뷰 요청 주세요!

2023-07-27 01:37 UTC, hjhello423 commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +        GraphPath<Station, DefaultWeightedEdge> shortPaths = getShortPaths(startStation, endStation);
`PathService`가 외부 라이브러리인 `GraphPath`를 의존하고 있는데요.
서비스 레이어에서 의존을 끊어보는 방향으로 수정해 보면 좋을 것 같습니다!

2023-07-27 01:37 UTC, hjhello423 commented on src/main/java/nextstep/subway/domain/PathFinder.java
> +    private final WeightedMultigraph<Station, DefaultWeightedEdge> graph = new WeightedMultigraph(DefaultWeightedEdge.class);
generic 활용👍

2023-07-27 01:37 UTC, hjhello423 commented on src/main/java/nextstep/subway/domain/PathFinder.java
> +    }
`init()`과 `DijkstraShortestPath()`에서 `DijkstraShortestPath`가 불필요하게 반복적으로 new 되고 있는 걸로 보이는데요. 
이 부분도 효율적으로 개선해 볼 수 있을 것 같아요 😀

2023-07-27 01:37 UTC, hjhello423 commented on src/main/java/nextstep/subway/handler/SubwayExceptionHandler.java
> +    public @ResponseBody ErrorResponse badRequestSectionsHandler(BadRequestSectionsException ex) {
controller에서는 `ResponseEntity`를 사용하고 이곳에서는 `@ResponseStatus`를 사용해 주셨군요. 이렇게 판단하신 이유가 있으신가요?

2023-07-27 01:37 UTC, hjhello423 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        소요산역 = 지하철역_생성_응답("소요산역");
메서드 이름이 한글로 변경되어 한눈에 들어오네요. 👍

2023-07-27 01:37 UTC, hjhello423 commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +                .getObject("", LineResponse.class);
모든 역들 사이의 거리가 10으로 고정되어 있는 데이터셋에서는 최단거리 경로를 찾는 미션 요구 사항에 대한 테스트가 어려워 보여요. 😭

2023-07-27 01:37 UTC, hjhello423 commented on src/test/java/nextstep/subway/unit/PathTest.java
> +    }
모든 역들 사이의 거리가 10으로 고정된 상태로 보이는데요.
최단 경로 탐색 테스트가 잘 이루어지고 있는 걸까요?

2023-07-27 11:53 UTC, Eunhee0119 commented on src/main/java/nextstep/subway/handler/SubwayExceptionHandler.java
> +    public @ResponseBody ErrorResponse badRequestSectionsHandler(BadRequestSectionsException ex) {
ExceptionHandler는 다른 Controller와 다르게 에러 코드가 중요하다고 생각해서 `ResponseEntity.badRequest()....` 으로 작성하는 것보다 상단에 `@ResponseStatus(HttpStatus.BAD_REQUEST)` 로 표시해주는게 더 가독성이 좋다고 생각하여 위와 같이 작성했습니다!

2023-07-27 12:01 UTC, Eunhee0119 commented
우선은 Outside In 방식으로 인수테스트를 작성하고 테스트 통과하도록 컨트롤러부터 구현하다보면 도메인까지 구현을 다 해버리게 되는 것 같아요. 도메인 단위테스트를 작성할 때는 거의 리펙토링이나 서비스에 구현한 코드를 도메인으로 옮기는 정도만 하게 되네요. 😅

2023-07-27 12:19 UTC, Eunhee0119 commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +                .getObject("", LineResponse.class);
앗, 그렇네요.🥲  추가로 구간 연결부분도 빠졌네요.. 수정하겠습니다!

2023-07-28 00:24 UTC, hjhello423 requested changes
안녕하세요 은희님 😀
리뷰 잘 반영해 주셨네요. 조금 더 개선해 보면 좋을 것 같은 내용이 보여 코멘트를 추가로 달아두었습니다!
추가로 모든 테스트 코드들이 실패하고 있어요. 애플리케이션이 동작하지 않고 있는데 에러 로그를 보고 수정해 보시면 될 것 같습니다.
그럼 확인 후 다시 한번 리뷰 요청 주세요!

2023-07-28 00:24 UTC, hjhello423 commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +        Path shortPaths = getShortPaths(startStation, endStation);
`GraphPath`에 대한 의존이 사라지고 `Path`가 도출되었군요. 👍

2023-07-28 00:24 UTC, hjhello423 commented on src/main/java/nextstep/subway/domain/PathFinder.java
> +        this.dijkstraShortestPath = init(sections);
리뷰 반영 👍

2023-07-28 00:24 UTC, hjhello423 commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +                .extract();
`PathAcceptanceTest`에서도 다른 곳들 처럼 반복되는 부분을 분리시킬 수 있을 것 같아요.

2023-07-28 00:24 UTC, hjhello423 commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +        assertThat(path.getDistance()).isEqualTo(DEFAULT_DISTANCE+SHORT_DISTANCE);
인수 테스트 또는 단위 테스트에서 여전히 최단 경로에 조회 기능에 대한 검증을 충분히 하고 있지 않은 것으로 보이는데요.
거리뿐만 아니라 역들이 순서대로 잘 조회가 되는지도 검증해 보면 좋을 것 같습니다. 😀

2023-07-28 09:25 UTC, Eunhee0119 commented
피드백 감사합니다! :D 
ㅠㅜ pr 요청할때 충돌이 생겨서 병합했는데, 그 과정에서 코드가 잘못 들어갔나봐요.
얘기해주신 부분들은 수정하여 반영했습니다!

2023-07-28 14:09 UTC, hjhello423 requested changes
안녕하세요 은희님 😀
확인해 봐야 할 부분들이 남아있어 코멘트 남겨두었습니다!
확인 후 다시 한번 리뷰 요청 주세요.

2023-07-28 14:09 UTC, hjhello423 commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +        ExtractableResponse<Response> response = 최단_경로_조회(BASE_URL + "?source=" + source + "&target=" + target);
아래처럼 호출하도록 하면 더 가독성 있을 것 같아요. 😀
```suggestion
        ExtractableResponse<Response> response = 최단_경로_조회(source, target);
```

2023-07-28 14:10 UTC, hjhello423 commented
수정해 주신 코드도 여전히 테스트 코드와 애플리케이션이 실행되지 않고 있는 걸로 보이는데요.
origin에 누락된 코드나 커밋이 있는지 확인 부탁드립니다.
해결이 잘 안되신다면 origin의 코드를 다운받아서 실행해 보면 좋을 것 같아요.
해결에 어려운 부분이 있다면 DM 주세요!

2023-07-29 04:34 UTC, Eunhee0119 commented
repository를 domain package 에서 repository package를 만들어 옮겼는데, 기존 기존 파일이 남아있어서 오류가 생겼던 것 같습니다! 수정하여 다시 커밋했습니다!!

2023-07-30 05:21 UTC, hjhello423 approved these changes
안녕하세요 은희님 😀
변경해 주신 부분 확인하였습니다!
그럼 이번 미션은 머지하고 마무리하도록 하겠습니다.
미션 진행되는 동안 고생하셨어요. 다음 미션도 화이팅하세요 🚀🚀🚀

2023-07-30 05:22 UTC, merged