🚀 3단계 - 경로 조회 기능
next-step/atdd-subway-path pull request #648
Opened 2023-07-26 08:17 UTC by thalals

3번째 리뷰도 잘 부탁드리겠습니다!

2023-07-27 01:25 UTC, testrace requested changes
안녕하세요 형민님 😃 
3단계도 잘 구현해주셨네요 👍 
몇 가지 코멘트 남겼는데 확인해 주시고 다시 리뷰요청 부탁드려요

2023-07-27 01:25 UTC, testrace commented on src/main/java/nextstep/subway/entity/group/SectionGroup.java
> +    private GraphPath<Station, Station> getGraph(Station source, Station target) {
SectionGroup은 1개 노선이 가지는 구간을 관리하는 일급 컬렉션이었는데
경로를 구하는 기능이 포함되니 책임이 모호해지고 응집도도 낮아지는 것 같아요
경로 조회 기능에 대한 책임을 수행하는 도메인 객체를 도출하면 어떨까요?

2023-07-27 01:25 UTC, testrace commented on src/main/java/nextstep/subway/entity/group/SectionGroup.java
> +        }
stream api를 활용해 보시는 것도 추천드립니다 😃

2023-07-27 01:25 UTC, testrace commented on src/main/java/nextstep/subway/facade/SectionFacade.java
> +    }
경로 조회 기능을 위한 PathController와 PathResponse는 추가되었는데 PathFacade나 PathService는 없네요
형민님은 어떤 기준으로 Controller, Facade, Service를 만드시나요?

2023-07-27 01:25 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +        //            | --- 5 --- 특급역 --- 5 --- |
거리를 포함해서 시각화를 잘해주셨네요 👍

2023-07-27 01:25 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +            최적경로_가중치_확인(경로조회_결과, 15)
`가중치`는 경로 조회 기능에 어울리지 않는 단어 같아요 😢 
구현한 기능에 맞는 표현으로 변경하면 어떨까요?

2023-07-27 01:25 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    void getPaths_notConnected() {
예외 상황 테스트 👍

2023-07-27 03:08 UTC, thalals commented on src/main/java/nextstep/subway/entity/group/SectionGroup.java
> +    private GraphPath<Station, Station> getGraph(Station source, Station target) {
안녕하세요 용주님!
안그래도 고민하던 부분이였는데 리뷰 남겨주셔서 감사합니다😂

사실은 전체 구간을 가지는 일급컬렉션을 생성해 경로조회 객체를 만들어주려했지만 SectionGroup 와 같은 멤버변수를 가지는 새로운 객체를 만들어야함이 의구심이 들어 SectionGroup에 기능을 추가했습니다.
용주님의 의견을 들어보니 같은 멤버변수를 가진다고해도 서로의 역할이 명확히 다르니 분리해서 각자 관리하는게 훨씬 유연한 설계라는 생각이 드네요 명확한 지적 감사드립니다!!👏🏻👏🏻👏🏻

2023-07-27 03:09 UTC, thalals commented on src/main/java/nextstep/subway/entity/group/SectionGroup.java
> +        }
감사합니다! 시도해보겠습니다 🫡

2023-07-27 03:10 UTC, thalals commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +            최적경로_가중치_확인(경로조회_결과, 15)
타당한 의견이신거같아요
조금 더 고민해보겠습니다😄

2023-07-27 03:26 UTC, thalals commented on src/main/java/nextstep/subway/facade/SectionFacade.java
> +    }
Service 는 도메인 기준으로 만들고
Controller 는 요구사항 기준으로 만드는 편입니다!
Facade는.. 지금까지 기분따라 만들었던거 같군요...ㅋㅋㅋㅋㅋㅋㅋㅎㅎ;;

용주님의 리뷰를 듣고 생각해보건데 Facade 도 요구사항 따라 만드는게 더 명확한 관리가 되겠다는 생각이 듭니다!

2023-07-27 05:10 UTC, thalals reviewed
꼼꼼한 리뷰 감사드립니다😁
추가적으로 궁금한 사항이 생겨 코멘트 남겨놓았습니다!

2023-07-27 05:10 UTC, thalals commented on src/main/java/nextstep/subway/entity/group/SectionGroup.java
막상 리팩토링을 하고보니까 큰차이가 없는거 같은데 Stream API 를 권장하시는 이유가 무엇인가요!?

2023-07-28 03:40 UTC, testrace requested changes
안녕하세요 형민님 😃 
피드백 반영 잘해주셨네요 👍 
조금만 다듬고 마무리하면 좋을 것 같아 코멘트 남겼습니다
확인해 주시고 다시 리뷰 요청 부탁드려요

2023-07-28 03:40 UTC, testrace commented on src/main/java/nextstep/subway/entity/group/SectionGroup.java
이 부분은 코멘트가 잘못 들어간 것 같네요 😢 
패스해주셔도 괜찮습니다 😅

2023-07-28 03:40 UTC, testrace commented on src/main/java/nextstep/subway/facade/PathFacade.java
> +        );
지난 피드백이 반영이 안된 것 같아요 😢 
SectionGroup은 Line이 가지는 구간들을 관리하는 객체이니 경로계산을 위한 Path 객체를 만들어보시면 어떨까요?
```suggestion
        final List<Section> sectionList = sectionService.findAll();
        final Path path = new Path(sectionList, start, finish);

        return new PathResponse(path.getStations(), path.getDistance());
```

```java
public class Path {
    private final WeightedMultigraph<Station, DefaultWeightedEdge> graph;
    private final GraphPath<Station, DefaultWeightedEdge> graphPath;

    public Path(List<Section> sections, Station start, Station finish) {
        ...
        graphPath = new DijkstraShortestPath<>(graph).getPath(start, finish);
    }

    public List<Station> getStations() {
    ...
    }
    
    public List<Station> getDistance() {
    ...
    }
}
```

2023-07-28 03:40 UTC, testrace commented on src/main/java/nextstep/subway/facade/PathFacade.java
> +    }
출발지와 목적지를 검증하는 로직은 도메인 로직이라고 생각되는데요
위 코멘트 처럼 Path 라는 객체가 도출된다면 책임을 위임할 수 있을 것 같아요 😃

2023-07-28 05:15 UTC, thalals commented on src/main/java/nextstep/subway/facade/PathFacade.java
> +        );
section List 에 계속 집중했었는데 생각해보니 Path 객체는 일급컬렉션일 필요가 전혀없었네요
상세한 예시 감사드립니다 !!!!!

2023-07-28 08:30 UTC, testrace approved these changes
피드백 반영 잘해주셨네요 💯 
여기서 마무리하겠습니다
남은 미션도 화이팅입니다 🔥

2023-07-28 08:30 UTC, merged