🚀 1단계 - 지하철 구간 추가 기능 개선
next-step/atdd-subway-path pull request #660
Opened 2023-07-29 04:37 UTC by SightStudio

2023-07-29 23:12 UTC, testrace requested changes
안녕하세요 😃 
1단계 미션 깔끔하게 잘 구현해 주셨네요 👍 
몇 가지 코멘트 남겼는데 확인해 주시고 다시 리뷰 요청해 주세요

2023-07-29 23:12 UTC, testrace commented on src/main/java/nextstep/subway/applicaion/dto/LineRequest.java
> +    }
DTO 보단 Section을 생성할 때 내부에서 검증하면 좋을 것 같은데 어떻게 생각하시나요?

2023-07-29 23:12 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +    }
인수 테스트가 깔끔하네요 👍 
인수 조건에 전체 길이에 대한 언급이 있으니 길이에 대한 검증도 추가하면 어떨까요?

2023-07-29 23:12 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +     * Then Then 구간은 2개로 나뉘고, 역 목록 사이에 새로운 역이 추가된다.
```suggestion
     * Then 구간은 2개로 나뉘고, 역 목록 사이에 새로운 역이 추가된다.
```

2023-07-29 23:12 UTC, testrace commented on src/test/java/nextstep/subway/unit/LineServiceTest.java
> +    @DisplayName("새로운 구간의 상,하행역이 모두 기존 노선에 있으면 노선을 등록 할 수 없다.")
예외 테스트 👍 
프로그래밍 요구사항에 도메인 단위 테스트는 필수이니 추가해 보시면 좋을 것 같아요

2023-07-29 23:12 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
LineSectionAcceptanceTest와 SectionAcceptanceTest가 공존하는데요
SectionAcceptanceTest는 사용하지 않는 것 같은데 삭제하면 어떨까요?

2023-07-30 08:09 UTC, SightStudio commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
헛 그렇네요 이름을 변경하다 하나를 그대로 납두었나보네요 후자는 삭제하도록 하겠습니다 :)

2023-07-30 08:31 UTC, SightStudio commented on src/main/java/nextstep/subway/applicaion/dto/LineRequest.java
> +    }
![image](https://github.com/next-step/atdd-subway-path/assets/50672087/c3859d4f-9eca-473b-b6b7-599f2aba51f6)

@testrace 요 코드는 기존 코드 정책대로 
구간없이 노선을 생성 할 수 있게 하기위해서 필요한 메서드라 둘다 가져가는게 나을듯합니다 ㅎㅎ
(dto에서의 구간 생성이 포함되었는지 여부와, 내부검증)

2023-07-30 10:03 UTC, SightStudio commented on src/test/java/nextstep/subway/unit/LineTest.java
> +class LineTest extends BaseUnitTest {
도메인 테스트 코드를 추가하다보니 id (pk) 에 대한 부분이 계속 작업하는데 걸려서 그런부분은 
서비스 테스트코드로 작성하였습니다. 

특히 이부분이 계속 걸리네요.

```상행 종점역은 상행역, 하행역이 같고, 거리가 0인 더미...? 형태의 데이터를 하나 더 추가한다.```

이런 부분때문에 이전단계에서 구간의 상행종점역을 노선의 컬럼으로 가지고 있었는데
두가지 방법중 상행종점역 노선을 컬럼으로 가지고 있는게 더  나을것같다는 생각이 드네요. ㅎㅎ

2023-07-30 10:03 UTC, SightStudio commented on src/test/java/nextstep/subway/unit/LineServiceTest.java
> +    @DisplayName("새로운 구간의 상,하행역이 모두 기존 노선에 있으면 노선을 등록 할 수 없다.")
넵 추가하고 의견 남겨놓았습니다 :)

2023-07-30 10:03 UTC, SightStudio commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
> +    }
넵 노선 조회 API에서 총 거리를 추가하여 검증하도록 하였습니다 ㅎㅎ 
구간별 거리는 step 3에 있어서 거기서 작업해보려합니다 :)

2023-07-30 11:54 UTC, testrace approved these changes
안녕하세요 😃 
피드백 반영 잘해주셨네요 👍 
소소하게 코멘트 남겼는데 확인해 주시고 다음 단계 진행 부탁드려요 🔥

2023-07-30 11:54 UTC, testrace commented on src/main/java/nextstep/subway/applicaion/dto/LineStationsDto.java
> +public class LineStationsDto {
기존과 다른 형식의 클래스명이네요
클래스명의 접미사를 하나로 통일해서 코드의 일관성을 유지하면 좋을 것 같은데 어떻게 생각하시나요?

2023-07-30 11:54 UTC, testrace commented on src/test/java/nextstep/subway/unit/LineTest.java
> +class LineTest extends BaseUnitTest {
상행 종점역을 찾기 위해 더미 데이터를 만들어둘 필요가 있는지 잘 모르겠습니다 😅 
더미 데이터를 활용하거나 종점역을 컬럼으로 관리하려면 오히려 더 복잡하다고 생각하는데요
stream을 활용해서 종점역을 찾는게 더 단순하지 않을까요?

2023-07-30 11:54 UTC, testrace commented on src/main/java/nextstep/subway/applicaion/dto/LineRequest.java
> +    }
노선 생성시 구간까지 생성여부를 판단하는 로직이라면 Service 내부에서 해도 괜찮을 것 같네요 😃

2023-07-30 11:54 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/LineSectionAcceptanceTest.java
>          assertThat(response.jsonPath().getList("stations.id", Long.class))
반복되는 `response.jsonPath().getList("stations.id", Long.class)` 코드는 Steps로 분리해도 좋을 것 같아요 😃

2023-07-30 11:55 UTC, merged