🚀 2단계 - 지하철 구간 제거 기능 개선
next-step/atdd-subway-path pull request #663
Opened 2023-07-29 14:30 UTC by cohys7

안녕하세요~
2단계 미션 완료 했습니다!
리뷰 부탁드립니다~
감사합니다!

2023-07-30 00:08 UTC, boorownie requested changes
2단계 요구사항 역시 잘 구현해주셨습니다!
1단계 미션 구현과 동일하게 테스트와 프로덕션 코드 모두 잘 구현해주셨어요~
몇가지 코멘트를 드리자면 Sections의 구간 추가/제거 타입에 따른 처리 부분인데
타입별로 구간 관리 로직을 수행하는게 마치 전략 패턴과 유사하게 구현되어있는걸로 보입니다.
현재는 타입과 수행 로직이 따로 분리되어있는데 이 부분을 조건과 로직이 함께 있도록 리팩터링 해보면 좋을 것 같아요! 
이 부분만 다듬어서 다음 단계로 넘어갈게요!

2023-07-30 00:08 UTC, boorownie commented on src/test/java/nextstep/subway/unit/SectionsTest.java
> +    @DisplayName("새로운 구간을 상행 종점으로 추가하려는 경우")
명시적인 테스트 의도 표현 👍

2023-07-30 00:08 UTC, boorownie commented on src/main/java/nextstep/subway/domain/Line.java
>          addType.apply(sections, new Section(this, upStation, downStation, distance));
만약 SectionAddType이나 apply하는 부분의 변경이 생겼을 때 LineService의 변경이 불가피한데요~
LineService에서 구간 추가 타입을 찾아서 수행시키는 것도 좋지만
그냥 sections.add() 호출만 하고 Sections의 add 메서드 내에서 해당 로직을 수행하면 어떨까요?

2023-07-30 00:08 UTC, boorownie commented on src/main/java/nextstep/subway/exception/ErrorType.java
> +    SECTION_DISTANCE_TOO_LONG("새로 추가하는 구간의 길이가 기존 구간의 길이보다 큽니다."),
꼼꼼한 에러 메시지 👍

2023-07-30 00:08 UTC, boorownie commented on src/test/java/nextstep/subway/unit/LineSectionServiceMockTest.java
>      void addSection() {
미션을 통해 경험한 두가지의 서비스 레이어 방법 중 어떤 방법을 더 선호하시나요?
그 이유도 함께 의견 남겨주세요~

2023-07-31 10:28 UTC, cohys7 commented on src/test/java/nextstep/subway/unit/LineSectionServiceMockTest.java
>      void addSection() {
목킹을 통해서 테스트하는 방식이 더 좋았던 것 같아요!

ID에 대한 신경을 쓰지 않아도 된다는 점은 좋았지만,
실제로 Repository를 이용하는 방식은 실제로 어떤 것이 DB에 저장되어야 하는지를 고려해서 테스트를 짜야하다보니
오히려 복잡했던 것 같아요.

또, 지금은 DB에 저장한다고 해도, 롤백하는 로직이 있어서 괜찮지만
만약 실제로 현업에서 적용한다면 어떻게 해야할지 고민이 될 것 같습니다.
(테스트를 위한 테이블을 별도로 유지해야할 것 같은데 너무 과한게 아닌가 하는 생각이 듭니다.)

목킹을 사용하면, 내부 동작에서 정해진 결과가 반환될 것이라는 걸 가정할 수 있어서 테스트 작성이 더 편리했던 것 같습니다!

2023-07-31 10:29 UTC, cohys7 commented on src/main/java/nextstep/subway/domain/Line.java
>          addType.apply(sections, new Section(this, upStation, downStation, distance));
해당부분 수정 완료했습니다~

2023-07-31 10:29 UTC, cohys7 commented
add, remove type 설정 -> 실제 추가, 삭제 동작까지 Sections 내부에서 하도록 수정하고,
각 추가, 삭제 타입별 조건과 수행 동작을 같은 클래스에 있도록 나누어 보았습니다.

그래서 Enum 에서 어떤 방식을 사용할지 찾고,
실제로 동작은 별도 클래스에서 하도록 수정해보았는데요...

Sections에서 로직을 좀 나눌 수 있다는 생각이 드는 반면
기본 List와 관련된 클래스를 랩핑하게 되는 부분이 많아 이렇게 하는게 맞나? 라는 생각도 듭니다 ㅎㅎ

리뷰 부탁드립니다~

2023-07-31 12:20 UTC, boorownie approved these changes
꽤 번거로운 피드백이었을텐데 잘 구현해주셨습니다!
전략 패턴을 이용하여 구간관리를 하다니 정말 대단하십니다 💯 
덕분에 단위 테스트 작성도 용이해지고 가독성도 좋아졌으며 확장성 또한 좋아졌습니다!
이어서 다음 단계 미션 진행해주세요~

2023-07-31 12:20 UTC, boorownie commented on src/main/java/nextstep/subway/domain/delete/SectionDeleteStrategy.java
> +public interface SectionDeleteStrategy {
오 멋지십니다 👍 
완벽하게 잘 구현해주셨습니다

2023-07-31 12:20 UTC, boorownie commented on src/main/java/nextstep/subway/domain/Sections.java
> -        throw new IllegalArgumentException();
체크하는 로직이 제거되어 깔끔해 졌네요 👍

2023-07-31 12:20 UTC, boorownie commented on src/test/java/nextstep/subway/unit/AddFirstTest.java
> +    void addFirst() {
꼼꼼한 단위 테스트 👍

2023-07-31 12:20 UTC, merged