3단계 - 경로 조회 기능 구현
next-step/atdd-subway-path pull request #683
Opened 2023-08-06 13:20 UTC by yyy9942

안녕하세요 리뷰어님, 이번 과제도 리뷰 잘 부탁드립니다.

2023-08-06 13:23 UTC, yyy9942 commented
단위테스트의 경우 `findPath` 메서드는 단위테스트 작성시 모두 mocking처리로 진행해야해서 어떻게 작성해야할지 모르겠더라고요. 어떻게 하면 좋을까요?

2023-08-06 16:15 UTC, pch8388 requested changes
질문 주신 부분과 참고하실 수 있는 코멘트들을 추가해두었습니다  😄 
확인하시고 수정 후 리뷰요청 부탁드립니다 🔥

2023-08-06 16:15 UTC, pch8388 commented on src/main/java/nextstep/subway/path/PathService.java
> +    public PathResponse findPath(final Long sourceStationId, final Long targetStationId) {
> 단위테스트의 경우 findPath 메서드는 단위테스트 작성시 모두 mocking처리로 진행해야해서 어떻게 작성해야할지 모르겠더라고요. 어떻게 하면 좋을까요?

1. mocking 해서 테스트
2. 필요한 값들 미리 저장하고 테스트 (repository 들 실제 bean 사용)

정도가 생각납니다
어떤 방법을 사용해도 테스트 하려면 사전조건이 복잡해지긴 합니다 😢 
실제로 검증하고자 하는 것에 집중할 수 있도록 메서드 추출이나 test fixture 사용 등을 통해 잘 정리해보면 좋을 것 같아요

이번 과정에서는 도메인 객체에서 로직을 처리하는 것을 추천드리고 있습니다 😄 
도메인 객체를 만들어 로직을 처리하도록 해보면 어떨까요? 🤔

2023-08-06 16:15 UTC, pch8388 commented on src/main/java/nextstep/subway/path/PathService.java
> +        GraphPath<String, DefaultWeightedEdge> path = new DijkstraShortestPath<>(createGraph())
```suggestion
        GraphPath<Station, DefaultWeightedEdge> path = new DijkstraShortestPath<>(createGraph())
```

이렇게 할수도 있어요 😄

2023-08-06 16:15 UTC, pch8388 commented on src/test/java/nextstep/subway/PathAcceptanceTest.java
> +        assertThat(pathResponse.body().as(PathResponse.class).getDistance()).isEqualTo(15L);
의도한 경로대로 왔는지 확인해보는 건 어떨까요? 😄

2023-08-06 16:15 UTC, pch8388 commented on src/main/java/nextstep/subway/path/PathService.java
> +    private WeightedMultigraph<String, DefaultWeightedEdge> createGraph() {
그래프를 생성하고, 응답할 객체를 생성하는 메서드를 잘 나누어 주셨네요 💯

2023-08-06 16:15 UTC, pch8388 commented on src/main/java/nextstep/subway/path/PathService.java
> +                .getPath(sourceStationId.toString(), targetStationId.toString());
<img width="351" alt="스크린샷 2023-08-07 오전 1 14 27" src="https://github.com/next-step/atdd-subway-path/assets/17218212/53d0ed77-2e2c-46ea-8c9f-5efc570a2dfa">

요구사항을 충족시켜 주세요 😭

2023-08-07 08:33 UTC, yyy9942 commented
요구사항 추가 반영하여 테스트 작성해보았습니다.
메서드 특성상 단위테스트로 쪼개면 private 메서드를 public으로 변경해야하고, 주요 기능은 라이브러리에 의존되어있어 크게 의미있어보이지 않아 인수테스트로 대체하여보았습니다.

2023-08-07 11:56 UTC, pch8388 commented
> 요구사항 추가 반영하여 테스트 작성해보았습니다. 메서드 특성상 단위테스트로 쪼개면 private 메서드를 public으로 변경해야하고, 주요 기능은 라이브러리에 의존되어있어 크게 의미있어보이지 않아 인수테스트로 대체하여보았습니다.

학습을 위해 단위 테스트까지 만들어보시는 것을 추천드렸었던 거였고, 인수테스트는 잘 만들어주셨습니다 👍

2023-08-07 11:57 UTC, pch8388 approved these changes
리팩터링 잘해주셨네요 😄 
남겨드린 코멘트는 참고해주시고, 이번 주차 미션은 여기서 마무리 하겠습니다
수고하셨습니다 👏

2023-08-07 11:57 UTC, pch8388 commented on src/main/java/nextstep/subway/path/PathController.java
> +    }
예외처리 핸들러 위치가 적절하지 않은 것 같아요 😢 
공통적으로 적용이 되는데, PathController 에 위치시키신 이유가 있을까요? 🤔

2023-08-07 11:57 UTC, merged

2023-08-07 12:12 UTC, yyy9942 commented on src/main/java/nextstep/subway/path/PathController.java
> +    }
글로벌하게 처리하지 않고 컨트롤러별로 처리하려고 내부정의 하였습니다~

2023-08-07 12:17 UTC, pch8388 commented on src/main/java/nextstep/subway/path/PathController.java
> +    }
의도하신대로라면 `@RestControllerAdvice` 애노테이션을 삭제해주셔야 합니다 😄