🚀 3단계 - 경로 조회 기능 개발
next-step/atdd-subway-path pull request #684
Opened 2023-08-06 14:13 UTC by SightStudio

리뷰어님 안녕하세요. 이번 리뷰도 잘 부탁드립니다. :)

작업하면서 궁금한 부분은 코멘트 추가하였습니다.

2023-08-06 14:18 UTC, SightStudio commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    if(노선_초기화_완료) {
이부분은 약간 꼼수... 비슷하게 구현했는데요.

현재 프로젝트와 같이 병렬로 테스트가 돌아가지 않는 상황에서 
해당 클래스에서 노선도를 테스트 케이스마다 생성하는건 헤비한 작업이라고 생각되어서 (테스트 시간 증가)

해당 클래스에서는 노선도를 한번만 생성하고 하위 테스트들이 이를 공유하도록 작업하였습니다. 

이런 방식을 리뷰어님은 어떻게 생각하시는지 궁금합니다.

2023-08-06 14:18 UTC, SightStudio commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +  void tearDown() {
이부분도... 꼼수긴 하지만 teardown 할 방법이 딱히 없어 제일 마지막테스트로 호출되도록 하였습니다.

2023-08-07 09:58 UTC, testrace requested changes
안녕하세요 😃 
3단계도 깔끔하게 잘 구현해 주셨네요 👍 
질문에 대한 답변과 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청 부탁드려요

2023-08-07 09:58 UTC, testrace commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +  public PathSearchResponse searchAndGetPath(PathSearchRequest request, BindingResult bindingResult) {
조회용으로만 사용하니 readOnly 설정을 추가하면 어떨까요?

2023-08-07 09:58 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    if(노선_초기화_완료) {
말씀하신대로 경로를 조회할 때의 테스트 케이스마다 노선 목록을 만들 필요 없을 것 같네요 😃 
if문을 활용해 제어어하기 보다 BeforeAll/AfterAll 애너테이션을 활용해 보시면 어떨까요?

2023-08-07 09:58 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +  }
예외 상황까지 인수 테스트로 작성해주셨네요 👍 
인수 테스트 작성 및 수행 비용은 단위 테스트보다 큰편인데요
예외 테스트나 세부 사항은 단위 테스트에서 검증하고 인수 테스트는 해피 케이스 위주로 검증하면 어떨까요?

2023-08-07 09:58 UTC, testrace commented on src/test/java/nextstep/subway/unit/PathFinderTest.java
> +  }
출발역과 도착역의 경로가 하나밖에 없는 경우 최단 거리라고 단정하긴 어려울 것 같아요 😢 
2개 이상의 경로를 만들어서 최단 경로를 검증하면 어떨까요?
미션 페이지의 예시를 참고해 보시면 좋을 것 같아요

2023-08-07 09:58 UTC, testrace commented on src/test/java/nextstep/subway/unit/PathFinderTest.java
> +  }
LineTest에서도 역과 노선 객체를 만들어 사용하고 있는데요
fixture를 만들어서 활용할 수 있을 것 같은데 어떻게 생각하시나요?

2023-08-07 17:02 UTC, SightStudio commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    if(노선_초기화_완료) {
아아.. 테스트 인스턴스의 라이프 사이클을 클래스레벨로 가져가면 
static 함수를 안써도 BeforeAll/AfterAll이 되는군요. ㅎㅎ 한참 고민하다 이제 알았네요

```@TestInstance(Lifecycle.PER_CLASS)```

2023-08-09 15:36 UTC, SightStudio commented on src/test/java/nextstep/subway/unit/PathFinderTest.java
> +  }
이제보니... 노선도를 잘못잡았다는 생각이드네요 ㅋㅋ  살고있던곳 근처로 잡았는데
경로가 하나밖에 안나오는군요 이런... 데이터를 바꿔보겠습니다 ㅠㅠ

2023-08-09 15:59 UTC, SightStudio commented on src/test/java/nextstep/subway/unit/PathFinderTest.java
> +  }
<img width="625" alt="image" src="https://github.com/next-step/atdd-subway-path/assets/50672087/9c5dcb39-be7f-4068-af7e-cf02f89dcd6a">

2023-08-09 16:01 UTC, SightStudio commented on src/test/java/nextstep/subway/unit/PathFinderTest.java
> +  }
봉천 -> 고속터미널까지 로 경로가 어려가지로 나올 수 있도록 수정하였습니다.

2023-08-09 16:02 UTC, SightStudio commented on src/test/java/nextstep/subway/unit/PathFinderTest.java
> +  }
요건... fixture를 만들어보았는데 조금 어색하네요 
요렇게 하는게 맞을지 잘 모르겠네요 ㅠㅠ

2023-08-09 16:03 UTC, SightStudio commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +  }
넵 비용생각하니 단위테스트에서 검증하는게 좋겠네요 :)

2023-08-11 00:17 UTC, testrace approved these changes
안녕하세요 동민님 😃 
피드백 반영 잘해주셨네요 👍 
이번 미션은 여기서 마무리하겠습니다
남은 미션도 화이팅입니다 🔥

2023-08-11 00:17 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +  }
👍

2023-08-11 00:17 UTC, testrace commented on src/test/java/nextstep/subway/unit/fixture/SubwayLineFixture.java
> +public class SubwayLineFixture {
픽스처를 잘 만들어 주셨네요 👍 
객체의 상태가 변함이 없다면 클래스 변수로 만들어서 바로 사용하는 것도 추천드립니다 😃

2023-08-11 00:17 UTC, merged