🚀 3단계 - 경로 조회 기능
next-step/atdd-subway-path pull request #686
Opened 2023-08-07 09:42 UTC by wonseok5893

2단계 피드백 감사합니다!
다음과 같이 진행했습니다.
- 경로 검색 기능 인수테스트 작성
- 최단거리 테스트
- 최단거리 서비스 구현
- refactor
- 예외 인수테스트 작성
- 구현 및 테스트 통과
- refactor

2023-08-07 12:39 UTC, catsbi requested changes
wonseok5893님 막판 스퍼트 열심히 해주시네요 💯 
경로탐색 관련하여 피드백 남긴부분들이 있으니 확인해주시고 다시 리뷰요청 부탁드려요!

2023-08-07 12:39 UTC, catsbi commented on src/main/java/nextstep/subway/linesection/LineSections.java
> +                return;
반복문내에 분기문이 있다보니  indent가 3이 되버렸어요. Stream API를 이용해서 분기문을 없앨 수 있지 않을까요?
```java
LineSectionRemoverHolder.getContext().stream().filter(LineSectionRemover::support) ... 
```

이후에 찾아서 수행하든 있을경우 컨슘을 하든 할 수 있지 않을까요

2023-08-07 12:39 UTC, catsbi commented on src/main/java/nextstep/subway/linesection/append/DownStationLineSectionAppender.java
> +            LineSection section = sections.getSections().get(idx);
내부값을 꺼내서(getSections), 연산을 수행(get(idx))하는건OOP패러다임인 객체간에 요청하고 응답한다와는 거리가 먼 것 같아요. 어떻게 바꿀 수 있을까요?

2023-08-07 12:39 UTC, catsbi commented on src/main/java/nextstep/subway/linesection/append/DownStationLineSectionAppender.java
> +            sections.removeSection(section);
코드의 길이가 좀 더 길어지더라도 메서도 호출부에 인수를 생성하는 로직을 넣는것보다 가독성 측면에서 유리할 수 있습니다

2023-08-07 12:39 UTC, catsbi commented on src/main/java/nextstep/subway/linesection/append/LineSectionAppenderHolder.java
> +public class LineSectionAppenderHolder {
극단적으로 다음과 같이 코드를 작성하면 어떻게 될까요? 
```java
for(int i = 0; i < Integer.MAX_VALUE; i++) {
    new LineSectionAppenderHolder()
}
```

2023-08-07 12:39 UTC, catsbi commented on src/main/java/nextstep/subway/linesection/remove/LineSectionRemover.java
> +     */
javadocs를 작성하고자 한다면 내용을 채워주면 좋을 것 같네요. 
https://catsbi.oopy.io/1b439cd5-58aa-4cb1-a715-2bfa66afc72a#bb57419c-9dcc-478c-8e54-e067d5bef112

2023-08-07 12:39 UTC, catsbi commented on src/main/java/nextstep/subway/linesection/remove/MiddleStationRemover.java
> +        return true;
코드의 가독성을 더 높혀볼 수 없을까요?

2023-08-07 12:39 UTC, catsbi commented on src/main/java/nextstep/subway/path/PathService.java
> +            throw new BadRequestException("the path is not found.");
한 줄짜리 분기문도 블럭`{}` 생략은 지양해주세요!

2023-08-07 12:39 UTC, catsbi commented on src/main/java/nextstep/subway/path/PathService.java
> +                .collect(Collectors.toList());
저는 개인적으로 코틀린이 아닌 자바에서 var나 val을 사용하는걸 크게 권장하지는 않아요. 
컴파일러가 뛰어나서 타입추론을 한다지만 개발자 입장에서 타입추론이 쉽지 않거든요.

2023-08-07 12:39 UTC, catsbi commented on src/main/java/nextstep/subway/path/ShortestPath.java
> +    }
생성자에서 필드 할당이 아닌 의미있는 비즈니스 로직을 작성하는건 권장드리지 않습니다. 비용측정이 힘들 뿐더러 메서드 시그니처를 보고 우리는 고비용이 들꺼라 유추할 수 없기 때문이죠. 협업 혹은 내가 해당 내용을 잊을 경우 어떤 사이드 이펙트가 생길 지 알 수 없습니다

2023-08-12 15:06 UTC, wonseok5893 commented on src/main/java/nextstep/subway/linesection/append/LineSectionAppenderHolder.java
> +public class LineSectionAppenderHolder {
싱글톤으로 관리하기 위해 빈으로 등록해서 사용하도록 하겠습니다ㅎㅎ

2023-08-12 15:21 UTC, wonseok5893 commented on src/main/java/nextstep/subway/linesection/append/LineSectionAppenderHolder.java
> +public class LineSectionAppenderHolder {
다시생각해보니, LineSectionAppenderHolder 빈으로 관리할 시에, 불편한 느낌이 드는 부분
1. LineSections는 도메인 관리 대상이기 때문에 해당 Appender를 도메인에 DI하는게 아니다라고 생각이 들어요.
2. 1번을 피하기 위해 빈으로 관리 + 정적으로 관리하기에 DI개념과 조금 어긋난게 아닌가 생각이 들어요.
결론 빈 관리가 아닌 싱글톤을 구현하여 사용하는 방식으로 해야할것 같습니다.

2023-08-12 15:30 UTC, wonseok5893 commented on src/main/java/nextstep/subway/linesection/remove/LineSectionRemover.java
> +     */
참고 문서 감사합니다. 
해당 부분은 다른 미션에 집중하기 위해서 미션 완료 후에 한번 반영해보도록 하겠습니다!

2023-08-12 15:35 UTC, wonseok5893 commented on src/main/java/nextstep/subway/linesection/append/DownStationLineSectionAppender.java
> +            sections.removeSection(section);
@catsbi 어떤 의미인지 정확하게 이해하지는 못했지만, 
Appender ->  LineSections 추가해야할 관련 정보를 보내고, LineSections에서 LineSection을 생성하여 추가하게끔 수정하도록하겠습니다.

2023-08-12 15:37 UTC, wonseok5893 commented on src/main/java/nextstep/subway/path/PathService.java
> +                .collect(Collectors.toList());
공감합니다ㅎㅎ

2023-08-12 15:39 UTC, wonseok5893 commented on src/main/java/nextstep/subway/path/PathService.java
> +                .collect(Collectors.toList());
메소드 단위로 테스트코드 작성시에 return 타입이 변경되는 경우, 유연하게 var or val를 사용해서 편하게 타입추론을 통해 수정을 하지 않아도 되었던 장점이 있었던 경험이 있긴하네요.

2023-08-12 15:40 UTC, wonseok5893 commented on src/main/java/nextstep/subway/path/ShortestPath.java
> +    }
의견 감사합니다! 피드백 반영해보도록 하겠습니다.

2023-08-12 16:01 UTC, wonseok5893 commented
피드백 반영했습니다. 감사합니다 ㅎㅎ

2023-08-13 13:36 UTC, catsbi approved these changes
원석님 마지막까지 피드백 반영 잘 해주셨어요. 
미션 진행하느라 고생 많으셨습니다. 피드백 남긴부분과 코멘트만 확인해주시면 좋을 것 같아요. 
이만 merge하도록 하겠습니다!

2023-08-13 13:36 UTC, catsbi commented on src/main/java/nextstep/subway/linesection/LineSections.java
> +            throw new BadRequestException("idx must be between 0 and sections size");
블럭`{}` 생략은 지양해주세요 ㅠㅠ

2023-08-13 13:36 UTC, catsbi commented on src/main/java/nextstep/subway/linesection/LineSections.java
> +    public void addToIndex(int idx, Line line, Station upStation, Station downStation, Integer distance) {
파라미터의 갯수가 2개를 넘어가네요!
이를 제가 기존에 드렸던 피드백은 메서드 호출하면서 매개변수를 작성하는 공간에 다른 메서드를 호출하는 식으로 작성하면 디버깅이 힘드니까 매개변수를 만들기 위한 메서드 호출(or 객체 생성을 위한 생성자나 정적 팩토리 호출)로직을 분리하라는 의미였습니다 ㅎㅎ 아니면 추가용 빌더객체를 구간일급컬렉션 내부적으로 호출할수도 있구요.

2023-08-13 13:36 UTC, merged