🚀 1단계 - 구간 추가 요구사항 반영
next-step/atdd-subway-path pull request #707
Opened 2024-02-06 06:29 UTC by qwe5507

안녕하세요 1단계 리뷰요청 드립니다. 

DM으로 문의드려도 친절하게 답변해주셔서 감사합니다.

매질 부탁드려요!

2024-02-06 14:01 UTC, HyunSung-Na requested changes
안녕하세요 진현님!

1단계 미션 잘 수행해주셨네요! 👍

몇가지 참고할만한 코멘트 남겼으니 확인 후 리뷰 재요청 해주시면 감사하겠습니다! 🙇‍♂️

2024-02-06 14:01 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/domain/Line.java
>          this.downStationId = downStation.getId();
``Line`` 에서도 stationId 가 있어야 될까요? 🤔

2024-02-06 14:01 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/domain/Line.java
> +        if (this.downStationId.equals(upStation.getId())) {
해당 부분은 ``Sections`` 내부로 옮기는 건 어떨까요?

2024-02-06 14:01 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/domain/Sections.java
> +                .flatMap(s -> Stream.of(s.getUpStation(), s.getDownStation()))
``Stream.of(s.getUpStation(), s.getDownStation())`` 해당 부분은 section 내의 로직으로 분리하셔도 좋을거 같아요!

2024-02-06 14:01 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/domain/Sections.java
> +    public List<Station> getStations(Long upStationId) {
``Map`` 을 이용해 주셨군요!

```
public List<Station> getStations() {
        return this.sections.stream()
                .sorted()
                .flatMap(section -> section.getStations().stream())
                .distinct()
                .collect(Collectors.toList());
    }
```
이런 방법도 있을거 같습니다 😁

2024-02-06 14:01 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/domain/Sections.java
> +        upSection.changeDistance(upSection.getDistance() - distance);
``upSection.getDistance() - distance`` 해당 거리의 값이 0보다 작거나 같으면 어떻게 될까요? 😁

2024-02-06 14:01 UTC, HyunSung-Na commented on src/test/java/nextstep/subway/acceptance/StationSteps.java
> +                .when().post("/stations")
반복되는 url 은 변수로 분리해도 좋을거 같아요!

2024-02-06 14:01 UTC, HyunSung-Na commented on src/test/java/nextstep/subway/unit/LineTest.java
> +
추가된 요구사항에 대한 도메인 테스트도 있으면 좋을거 같아요!

2024-02-06 14:01 UTC, HyunSung-Na commented on src/test/java/nextstep/subway/utils/DatabaseCleanup.java
> +//        entityManager.createNativeQuery("insert into station (id, name) values (1, '지하철역')").executeUpdate();
주석으로 남겨두실 이유가 있을까요? 🤔

2024-02-06 14:01 UTC, HyunSung-Na commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        노선을_조회하여_지하철역을_확인한다(lineId, Arrays.asList(강남역, 선릉역, 삼성역));
길이도 검증해 주시면 좋을거 같아요! ☺️

2024-02-07 13:16 UTC, qwe5507 commented on src/test/java/nextstep/subway/utils/DatabaseCleanup.java
> +//        entityManager.createNativeQuery("insert into station (id, name) values (1, '지하철역')").executeUpdate();
기초 데이터를 코드로 변경하고, 삭제하는걸 깜빡했네요;; 삭제했습니다!

2024-02-07 13:44 UTC, qwe5507 commented on src/main/java/nextstep/subway/domain/Sections.java
> +    public List<Station> getStations(Long upStationId) {
반영했습니다!

2024-02-07 13:44 UTC, qwe5507 commented on src/main/java/nextstep/subway/domain/Sections.java
> +                .flatMap(s -> Stream.of(s.getUpStation(), s.getDownStation()))
반영했습니다!

2024-02-07 16:04 UTC, qwe5507 commented on src/main/java/nextstep/subway/domain/Line.java
>          this.downStationId = downStation.getId();
Line 에서도 stationId을 제거하였습니다!
처음엔 Line이 라인의 상행/하행 종점역을 알고있어야 조회가 빠르다고 생각하여 stationId를 추가하였는데 
이로 인해 지저분한 코드가 생성되는것 같습니다.
비즈니스적으로 섹션의 순서가 보장되기 떄문에 조회시 마다 sorted하여 라인의 상행/하행 종점역을 구하게끔 변경하였습니다!

2024-02-07 16:05 UTC, qwe5507 commented on src/main/java/nextstep/subway/domain/Line.java
> +        if (this.downStationId.equals(upStation.getId())) {
반영했습니다!

2024-02-07 16:45 UTC, qwe5507 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        upSection.changeDistance(upSection.getDistance() - distance);
예외처리 추가하였습니다! 감사합니다!

2024-02-07 16:53 UTC, qwe5507 commented on src/test/java/nextstep/subway/acceptance/StationSteps.java
> +                .when().post("/stations")
반영했습니다!

2024-02-07 16:55 UTC, qwe5507 commented on src/main/java/nextstep/subway/domain/Line.java
>          this.downStationId = downStation.getId();
또 db에서 Section을 조회할때는 순서를 보장하지 않지만,
조회할때 항상 정렬하여 가져오기 때문에 Sections에 Section List를 굳이 순서에 맞게 추가하지 않아도 될거 라고 판단하여 
중간에 구간을 추가할때도 그냥 끝에 추가하게 하였습니다.
방향성이 틀리다면 피드백 부탁드립니다!

2024-02-07 17:10 UTC, qwe5507 commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        노선을_조회하여_지하철역을_확인한다(lineId, Arrays.asList(강남역, 선릉역, 삼성역));
반영했습니다 :)

2024-02-07 17:31 UTC, qwe5507 commented on src/test/java/nextstep/subway/unit/LineTest.java
> +
반영했습니다. 

Line Test가 일급 콜렉션인 Sections의 테스트도 커버한다고 생각하여 Sections의 단위 테스트는 작성하지 않았습니다. 
이런 경우 테스트가 중복되더라도 작성하는게 좋을까요?

2024-02-08 12:50 UTC, HyunSung-Na approved these changes
안녕하세요 진현님!

피드백 반영 잘해주셨네요! 👍 👍 머지 하도록 하겠습니다! 

다음 단계도 화이팅 하세요! 🚀

2024-02-08 12:50 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/domain/Section.java
> +public class Section implements Comparable<Section> {
``Comparable`` 👍

2024-02-08 12:50 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/domain/Sections.java
> +            System.out.println("여기오니?3");
기능을 구현하셨으면 지우셔도 좋을거 같아요 😁

2024-02-08 12:50 UTC, HyunSung-Na commented on src/test/java/nextstep/subway/unit/LineTest.java
> +                .isThrownBy(() -> 이호선.addSection(역삼역, 선릉역, 10));
```
 assertThatThrownBy(() -> { 이호선.addSection(역삼역, 선릉역, 10); }).isInstanceOf(Exception.class)
                .hasMessageContaining("message");
```
해당 방식으로 메시지도 검증할 수 있을거 같아요!

2024-02-08 12:50 UTC, HyunSung-Na commented on src/test/java/nextstep/subway/unit/LineTest.java
> +
현재의 경우에서는 LineTest 만으로도 충분할 것으로 생각 됩니다!
예외 상황에 대한 단위테스트를 작성해주시면 충분할 것이라고 생각합니다 😁

2024-02-08 12:50 UTC, merged

2024-02-08 13:06 UTC, qwe5507 commented on src/test/java/nextstep/subway/unit/LineTest.java
> +                .isThrownBy(() -> 이호선.addSection(역삼역, 선릉역, 10));
다음 step에 반영하여 푸쉬하겠습니다! 감사합니다 :)