2단계 - 구간 제거 요구사항 반영
next-step/atdd-subway-path pull request #786
Opened 2024-02-19 10:55 UTC by LEE-DAYOUNG-SARAH

### 기능 요구사항
- 노선에 등록된 역 제거 시 해당 역이 노선 가운데 있어도 제거할 수 있다.
- 노선에 등록된 역 제거 시 해당 역이 상행 종점역이어도 제거할 수 있다.

2024-02-19 23:19 UTC, testrace requested changes
안녕하세요 다영님 😃 
2단계 잘 구현해 주셨네요!
미션에서 TDD 사이클을 목표로 진행하라는 문구가 있는데요
TDD 사이클로 진행했음을 인지할 수 있게 커밋을 나눠서 해보시면 더 좋을 것 같아요
몇 가지 코멘트 남겨두었는데요 확인해 주시고 다시 리뷰 요청 부탁드려요

2024-02-19 23:19 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +            assertThat(구간_삭제_응답.statusCode()).isEqualTo(HttpStatus.NO_CONTENT.value());
인수 테스트는 사용자 스토리를 검증하는 것이니 
http status code 뿐만 아니라 삭제 이후의 구간 목록을 검증하면 어떨까요?

2024-02-19 23:19 UTC, testrace commented on src/main/java/nextstep/subway/entity/Sections.java
> +        }
>객체지향 생활체조
규칙 2: else 예약어를 쓰지 않는다.

else를 사용하지 않고 구현해 보시면 좋을 것 같아요

2024-02-19 23:19 UTC, testrace commented on src/test/java/nextstep/subway/unit/LineTest.java
> +    @DisplayName("유일한 구간은 삭제 시 예외가 발생한다.")
예외 상황을 꼼꼼하게 테스트해주셨네요 👍 
구간 테스트는 SectionsTest 클래스로 분리해서 관리하면 어떨까요?

2024-02-19 23:19 UTC, testrace commented on src/main/java/nextstep/subway/entity/Sections.java
> +    private void verifyRemoveSection(Station station) {
private 메서드는 호출되는 public 메서드 하위에 위치하면 어떨까요?
코드를 읽는 입장에서 private 메서드의 내용을 확인하기 위해 스크롤을 올리고 내리는 행위를 줄여줄 수 있을 것 같아요

2024-02-19 23:19 UTC, testrace commented on src/test/java/nextstep/subway/unit/LineTest.java
> +        assertThat(이호선.getSectionList()).hasSize(1);
중간 구간을 삭제하면 구간의 길이가 변경되는데요
길이 검증도 추가하면 어떨까요?

2024-02-20 11:30 UTC, LEE-DAYOUNG-SARAH commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +            assertThat(구간_삭제_응답.statusCode()).isEqualTo(HttpStatus.NO_CONTENT.value());
노선 조회하여 역 목록으로 검증하였습니다.

2024-02-20 11:31 UTC, LEE-DAYOUNG-SARAH commented on src/main/java/nextstep/subway/entity/Sections.java
> +        }
else 제거하였습니다.

2024-02-20 11:31 UTC, LEE-DAYOUNG-SARAH commented on src/test/java/nextstep/subway/unit/LineTest.java
> +    @DisplayName("유일한 구간은 삭제 시 예외가 발생한다.")
SectionsTest로 분리하였습니다.

2024-02-20 11:32 UTC, LEE-DAYOUNG-SARAH commented on src/main/java/nextstep/subway/entity/Sections.java
> +    private void verifyRemoveSection(Station station) {
public 메서드인 removeSection 하위에 private을 위치하였는데, public 메서드 자체를 최상단으로 올려야 하는 걸까요?

2024-02-20 11:34 UTC, LEE-DAYOUNG-SARAH commented on src/test/java/nextstep/subway/unit/LineTest.java
> +        assertThat(이호선.getSectionList()).hasSize(1);
구간 변경에 따른 Line의 distance를 관리하고 있지 않아, Line의 distance를 삭제하였습니다.
이로 인해 기존의 api로 거리를 검증하기 힘들어, SectionsTest에 길이 검증부분 추가하였습니다.

2024-02-20 21:03 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +            assertThat(노선의_역_목록).containsExactly(강남역_ID, 역삼역_ID);
피드백 반영 👍

2024-02-20 21:03 UTC, testrace commented on src/main/java/nextstep/subway/entity/Sections.java
> +    private void verifyRemoveSection(Station station) {
이 부분은 제가 잘못 봤나 봐요 😅 
이 코멘트는 패스해 주세요!

2024-02-20 21:09 UTC, testrace approved these changes
안녕하세요 다영님 😃 
피드백 반영 잘해주셨네요 👍 
소소하게 코멘트 남겨두었는데 확인해 주시고 다음 단계 진행해 주세요!

2024-02-20 21:09 UTC, testrace commented on src/test/java/nextstep/subway/unit/SectionsTest.java
> +        이호선.addSection(역삼_선릉_구간);
변수명은 '상행_하행_구간' 형식인데 생성자의 인자 순서는 하행, 상행 순이라 코드를 읽을 때 헷갈릴 수 있을 것 같아요
Section 생성자에서 노선, 상행역, 하행역, 거리 순으로 입력 받으면 어떨까요?

2024-02-20 21:09 UTC, testrace commented on src/test/java/nextstep/subway/unit/SectionsTest.java
> +        assertThat(강남_선릉_구간.getDistance()).isEqualTo(강남_역삼_길이 + 역삼_선릉_구간.getDistance());
Sections가 가지는 전체 구간의 거리를 검증해봐도 좋을 것 같아요

2024-02-20 21:09 UTC, testrace commented on src/main/java/nextstep/subway/entity/Sections.java
코드가 변경되면서 Sections 내부에 사용하지 않는 메서드가 생겼네요
사용하지 않는 코드는 제거해 주시면 좋을 것 같아요

2024-02-20 21:09 UTC, merged

2024-02-20 23:08 UTC, LEE-DAYOUNG-SARAH commented on src/test/java/nextstep/subway/unit/SectionsTest.java
> +        이호선.addSection(역삼_선릉_구간);
다음 미션에 반영하겠습니다!

2024-02-20 23:08 UTC, LEE-DAYOUNG-SARAH commented on src/test/java/nextstep/subway/unit/SectionsTest.java
> +        assertThat(강남_선릉_구간.getDistance()).isEqualTo(강남_역삼_길이 + 역삼_선릉_구간.getDistance());
다음 미션에 반영하겠습니다!