Step3 - 경로 조회 기능
next-step/atdd-subway-path pull request #796
Opened 2024-02-20 23:28 UTC by LEE-DAYOUNG-SARAH

### 기능 요구사항
- 출발역과 도착역을 통해 최단 거리를 조회할 수 있다.
- 출발역과 도착역이 같은 경우 에러가 발생한다.
- 출발역과 도착역이 연결이 되어 있지 않은 경우 에러가 발생한다.
- 존재하지 않은 출발역이나 도착역을 조회 할 경우 에러가 발생한다.

저번 리뷰를 반영하여 커밋을 단계별로 나누어서 진행하였습니다.
잘 부탁드립니다 :)

2024-02-21 12:08 UTC, testrace requested changes
안녕하세요 다영님 😃 
3단계도 깔끔하게 잘 구현해 주셨네요 👍 
몇 가지 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청 부탁드려요!

2024-02-21 12:08 UTC, testrace commented on src/main/java/nextstep/subway/service/PathFinder.java
> +public class PathFinder {
경로 조회 로직을 Service에서 구현하셨다가 클래스로 분리해주셨네요 👍

2024-02-21 12:08 UTC, testrace commented on src/main/java/nextstep/subway/service/PathFinder.java
> +        }
>객체지향 생활체조
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.

메서드 분리등을 활용해 위 규칙을 지켜보시면 좋을 것 같아요

2024-02-21 12:08 UTC, testrace commented on src/main/java/nextstep/subway/service/PathService.java
> +        return pathFinder.getShortestPath(sectionsList, sourceStation, targetStation);
PathFinder 생성자에 아무런 인자 없이 getShortestPath 메서드에서 구간 목록, 출발역, 도착역을 파라미터로 전달하고 있는데요
PathFinder가 상태를 관리 하지않는다면 static 메서드로 제공하는 방법도 고려해 보시면 좋을 것 같아요
```java
PathFinder.shortestPath(sections, source, target);
```

PathFinder 가 상태를 갖는다면 구간 목록을 가지고 있는 방법도 있겠네요
```java
PathFinder pathFinder = new PathFinder(sections);
pathFinder.shortestPath(source, target);
```

2024-02-21 12:08 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
상위 클래스 AcceptanceTest에 포함된 내용이니 PathAcceptanceTest에서는 제거해도 괜찮지 않을까요?

2024-02-21 12:08 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +        삼호선 = LineFixture.노선_생성_요청("3호선", "orange", 2,  교대역, 남부터미널역).as(LineResponse.class).getId();
경로 조회를 위한 노선 구성을 시각화해서 주석으로 제공하면 어떨까요?
```
    /**
     * 교대역    --- *2호선* ---   강남역
     * |                        |
     * *3호선*                   *신분당선*
     * |                        |
     * 남부터미널역  --- *3호선* ---   양재
     */
```

2024-02-21 12:08 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +        assertThat(경로_조회_응답.as(PathResponse.class).getDistance()).isEqualTo(5);
역 목록과 거리 검증 👍

2024-02-21 12:08 UTC, testrace commented on src/test/java/nextstep/subway/unit/PathServiceTest.java
> +public class PathServiceTest {
서비스 단위 테스트까지 꼼꼼하게 작성해 주셨네요 👍

2024-02-21 12:41 UTC, LEE-DAYOUNG-SARAH commented on src/main/java/nextstep/subway/service/PathFinder.java
> +        }
수정하였습니다!

2024-02-21 21:56 UTC, testrace requested changes
안녕하세요 다영님 😃 
피드백 반영 잘해주셨네요 👍 
실패하는 테스트가 있어 코멘트 남겼습니다
코멘트 확인해 주시고 다시 리뷰 요청 부탁드려요

2024-02-21 21:56 UTC, testrace commented on src/main/java/nextstep/subway/service/PathFinder.java
> +    }
상태를 가지도록 변경해주셨네요 👍

2024-02-21 21:56 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> -@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
포트 충돌로 인해서 테스트가 정상적으로 동작하지 않네요 😢 
<img width="983" alt="image" src="https://github.com/next-step/atdd-subway-path/assets/8064743/d185c2c7-67c4-4603-91d8-05a3737f4d7c">
AcceptanceTest에서 포트 설정을 랜덤으로 변경해 보시면 좋을 것 같아요
```java
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
```

2024-02-22 10:21 UTC, testrace approved these changes
안녕하세요 다영님 😃 
이번 미션은 여기에서 마무리하겠습니다
다음 미션도 화이팅입니다! 🔥

2024-02-22 10:21 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/AcceptanceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
랜덤 포트 이후 아래와 같이 RestAssured 포트 설정까지 해주시면 좋을 것 같아요!
```java
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class AcceptanceTest {

    @LocalServerPort
    private int port;

    @Autowired
    private DatabaseCleanup databaseCleanup;

    @BeforeEach
    public void setUp() {
        RestAssured.port = port;
        databaseCleanup.execute();
    }
}
```

2024-02-22 10:21 UTC, merged