1단계 - 구간 추가 요구사항 반영
next-step/atdd-subway-path pull request #801
Opened 2024-02-22 16:27 UTC by Hyeon9mak

안녕하세요 승철님!
리뷰 잘 부탁드립니다!

2024-02-23 11:09 UTC, pch8388 requested changes
1단계 잘 수행해주셨는 데, 지하철 구간의 정렬이 제대로 되지 않는 것 같아요 😢 
코멘트 확인하시고 수정 후 리뷰요청해주세요 🔥

2024-02-23 11:09 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/line/LineAcceptanceTest.java
> +            Long 건대입구역_ID = 건대입구역.jsonPath().getLong("id");
중복적으로 생성되는 것들은 BeforeEach 쪽에 넣어서 테스트 내용에 더 집중하게 만들 수 있다고 생각해요 😄 
추가로, 결국 성수역_ID 가 필요한거면, 역을 생성 후 ID 를 반환해주는 메소드로 추출하면 가독성을 더 높일수 있을걸라고 생각됩니다

2024-02-23 11:09 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/line/LineAcceptanceTest.java
>          @Test
주석은 잘고쳐 주셨는데, DisplayName 도 수정해야 하지 않을까요? 😅

2024-02-23 11:09 UTC, pch8388 commented on src/main/java/nextstep/subway/line/Sections.java
> +                .orElseThrow(() -> new IllegalArgumentException("노선에 구간이 존재하지 않습니다."))
중복되게 많이 사용하는 구문으로 보여요 👀

2024-02-23 11:09 UTC, pch8388 commented on src/main/java/nextstep/subway/line/Sections.java
> +    @OrderBy("upStation.id ASC")
<img width="524" alt="스크린샷 2024-02-23 오후 7 58 38" src="https://github.com/next-step/atdd-subway-path/assets/17218212/efe2f414-d19b-4088-9d5a-ec66d91b1efe">

<img width="247" alt="스크린샷 2024-02-23 오후 7 59 33" src="https://github.com/next-step/atdd-subway-path/assets/17218212/147ec86d-57e0-43a7-a453-0fe960b252ed">

👀

2024-02-23 11:09 UTC, pch8388 commented on src/main/java/nextstep/subway/line/Sections.java
> +            values.add(0, section);
java 에서 arraylist 에 넣는다고 해서 순서보장이 되지 않습니다 😢 
JPA 는 결국 데이터베이스와 In-memory 객체를 매핑해주는 역할을 하는데요
데이터베이스는 In-memory 객체의 array index 를 알 수 있는 방법이 없습니다.
그렇다고 JPA 에서 데이터베이스에 컬럼을 임의로 추가하면 안되겠죠

`@OrderColumn`같은 것을 이용하는 방법도 있는데, 순서가 자주 바뀐다면 update 를 자주 발생시킵니다.
지금 도메인이라면 데이터 규모가 많이 커질 우려도 적기 때문에 메모리로 데이터를 가져온 후에 쓸때마다 정렬을 시키는 방법을 쓰셔도 됩니다 😄

2024-02-24 09:37 UTC, Hyeon9mak commented on src/test/java/nextstep/subway/acceptance/line/LineAcceptanceTest.java
> +            Long 건대입구역_ID = 건대입구역.jsonPath().getLong("id");
`LineAcceptanceTest` 클래스의 경우 테스트 코드의 수가 많다보니 ,
given 절마다 주어지는 데이터가 달라질 가능성이 높아 beforeEach 로 중복을 제거하기보단
테스트 코드 한 블럭을 읽을 때 어떤 데이터가 주어지는지 given 절에 모두 드러나는게 유지보수에 더 좋다고 생각했습니다.

결국 id 가 필요한 부분에 대해서는 적극 공감하여 바로 수정해보겠습니다 👍

2024-02-24 09:46 UTC, Hyeon9mak commented on src/main/java/nextstep/subway/line/Sections.java
> +                .orElseThrow(() -> new IllegalArgumentException("노선에 구간이 존재하지 않습니다."))
굳이 상수로 분리하기보다 한 눈에 읽히는게 가독성 측면에서 더 유리하다고 생각합니다. 승철님은 어떻게 생각하시나요?

2024-02-24 09:49 UTC, Hyeon9mak commented on src/main/java/nextstep/subway/line/Sections.java
> +            values.add(0, section);
`@OrderBy("upStation.id ASC")` 가 정렬을 보장해줄 것으로 기대하고 삽입시에만 index 를 활용 할 수 있도록 List 를 사용했는데, 곰곰히 생각해보니.... `upStationId` 오름차순으로 정렬하면 이상한 결과가 나올 수 밖에 없네요 😱 
제안해주신 대로 적절히 변경해보겠습니다!

2024-02-24 15:23 UTC, Hyeon9mak commented on src/main/java/nextstep/subway/line/Sections.java
> +    @OrderBy("upStation.id ASC")
😱

2024-02-25 01:33 UTC, pch8388 commented on src/main/java/nextstep/subway/line/Sections.java
> +                .orElseThrow(() -> new IllegalArgumentException("노선에 구간이 존재하지 않습니다."))
`많이` 라고 제가 잘못표현한거 같은데 해당 로직이 `getLastStation` 과 `getLastSection` 에 동일하게 중복되었다라는 의미였습니다 😅  혼란을 드려 죄송합니다 😭 

문자열에 대해서 제 생각을 말씀드리자면, 할때마다 고민이 되긴 하는데, 보통은 중복되는 문자열을 추출해서 관리하도록 하거나(특정 클래스나 enum 같은 곳에 몰아두거나, 해당 클래스 내부에 상수선언), 아예 예외를 커스텀 예외로 만들고 해당 예외 안에서 문자열 처리하도록 하기도 합니다.

2024-02-25 04:15 UTC, pch8388 requested changes
리팩토링 잘해주셨는데, `구간추가` 기능에 아직 해결되지 않은 문제가 있어요 😢 
수정 후 리뷰요청 해주세요 🔥

2024-02-25 04:15 UTC, pch8388 commented on src/main/java/nextstep/subway/line/Sections.java
<img width="480" alt="스크린샷 2024-02-25 오후 1 10 30" src="https://github.com/next-step/atdd-subway-path/assets/17218212/f247167a-5bd7-4708-a208-ac2d2b52b7ad">
<img width="258" alt="스크린샷 2024-02-25 오후 1 10 51" src="https://github.com/next-step/atdd-subway-path/assets/17218212/9968df6c-78bd-4960-9620-57ce8f1223a1">

아직도 `구간 추가` 시에는 이미 정렬되있다고 가정하고 로직이 짜여져있는 것 같아요 😢

2024-02-25 04:15 UTC, pch8388 commented on src/main/java/nextstep/subway/line/Sections.java
>      public List<Station> getAllStations() {
이런 방법은 생각못해봤는데 신선한 접근입니다 👍 👍 
다만, 쉽게 머리에 들어오지는 않는 것 같은데, 이런곳에서는 주석을 설명으로 달아도 좋다고 생각합니다 😄 
혹은, 로직을 어떻게 하면 조금 더 간략하게 만들수 있을까도 고민해보면 좋을 것 같아요 🔥

2024-02-25 04:15 UTC, pch8388 commented on src/main/java/nextstep/subway/line/Sections.java
> +    private Station getFirstStation() {
👍

2024-02-25 04:15 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/fixture/LineFixture.java
> +    public static Long newLineAndGetId(
💯

2024-02-25 04:18 UTC, Hyeon9mak commented on src/main/java/nextstep/subway/line/Sections.java
와우 이런... `getAllStations` 뿐만 아니라 `Sections` 를 생성할 때부터 정렬을 하도록 하는 방법을 취해야겠네요 😱

2024-02-27 07:01 UTC, pch8388 approved these changes
리팩토링 잘해주셨습니다 💯 
코멘트 확인 후 다음단계 진행해주세요 🚀

2024-02-27 07:01 UTC, pch8388 commented on src/main/java/nextstep/subway/line/Section.java
> +    @ManyToOne(fetch = FetchType.EAGER)
EAGER 로 변경하신 이유가 궁금하네요

2024-02-27 07:01 UTC, pch8388 commented on src/main/java/nextstep/subway/line/Sections.java
> +    public void sortSections() {
Sections 내부에서만 쓰기 때문에 private 으로 해도 될 것 같아요 😄 

사실 처음 전달하고자 했던 의도는 `구간 추가` 시에 반드시 정렬된 채로 추가를 하지 않아도 된다는 이야기를 말씀드리고 싶었습니다 😢 
잘 생각해보면, 구간을 특정 위치에 추가해야 하고, 해당 위치를 `정확히` 찾을수만 있다면, 항상 정렬된 list 를 가지고 있지 않아도 됩니다. 그렇다면 응답을 줄때만 정렬해서 응답해도 되지 않을까요? 🤔 
정렬을 위해 values 의 데이터를 조작하는 것이 괜찮을지 고민해봐야 합니다

2024-02-27 07:01 UTC, pch8388 commented on src/main/java/nextstep/subway/line/Sections.java
> +                .filter(section -> values.stream().noneMatch(other -> section.getUpStation().isSameStation(other.getDownStation())))
`section.isSameUpStation()`은 어떨까요? 😅 (혹은 조금 더 명확한 이름)

2024-02-27 07:01 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/line/LineAcceptanceTest.java
> +            assertThat(response.jsonPath().getList("stations.id", Long.class)).containsExactly(Z, X, A, K, L, N, Y, B);
검증에 많이 노력해주신것 같네요 👍

2024-02-27 07:01 UTC, merged

2024-02-29 12:09 UTC, Hyeon9mak commented on src/main/java/nextstep/subway/line/Sections.java
> +                .filter(section -> values.stream().noneMatch(other -> section.getUpStation().isSameStation(other.getDownStation())))
디미터 법칙도 지킬 수 있겠네요! 👍

2024-02-29 12:13 UTC, Hyeon9mak commented on src/main/java/nextstep/subway/line/Sections.java
> +    public void sortSections() {
조회를 이용할 때만 정렬을 하는 것이 성능적으로도 훨씬 뛰어나겠네요 👍 
성능적인 부분 외에도 values 의 데이터를 조직하는 것에 추가적인 문제가 있는지 궁금합니다!

추가적인 문제가 없다면 사실 정렬된 list 로 역을 추가하고 / 빼는 것이
코드를 읽고 로직을 머리속으로 상기시키기에 더 자연스럽지 않을까 해서요.

2024-03-01 00:57 UTC, pch8388 commented on src/main/java/nextstep/subway/line/Sections.java
> +    public void sortSections() {
현재와 같은 구현에서는 수정하다가 정렬구현을 변경하다가 실수로 역을 빼먹거나 하게되면 정렬하는 과정에서 데이터의 변화가 발생할 수 있다는 점이 불안한 요소로 생각할 수 있습니다

추가로 코드의 의도를 얼마나 오랫동안 유지시킬수 있냐는 관점에서 고민해보면 좋을 것 같은데요 🤔 
예를 들어 `특정 노선의 시작역을 알고 싶다.`라는 요건이 생긴다면? 
해당 메소드는 데이터의 변경과 전혀 관계가 없지만, 데이터를 변경시킬 여지가 발생하는 거죠
적어두고 보니 약간 억지스럽다고 생각하실 수도 있을것 같네요 😅 
사실 이런 가정들은 작은 우려일뿐이고, `정렬`을 다른 상황에서도 일관성있게 다룰 수 있다라고 생각되면 상관없을 것 같습니다.