1단계 - 구간 추가 요구사항 반영
next-step/atdd-subway-path pull request #831
Opened 2024-07-20 14:32 UTC by dharana77

2024-07-25 06:03 UTC, pch8388 requested changes
안녕하세요 
미션을 함께 하게 된 권승철입니다 🙇 
1단계 미션 수행 해주신 부분 보았는 데, 말씀해주신 것처럼 테스트가 실패하는 부분들이 있기 때문에, 코멘트 달아 드린 것 참고해서 테스트 통과시켜 주세요 😢 
수정 후 리뷰요청 부탁드립니다 🔥

2024-07-25 06:03 UTC, pch8388 commented on build.gradle
> +sourceCompatibility = "15"
변경하신 이유가 있을까요? 🤔

2024-07-25 06:03 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/line/LineSectionAcceptanceTest.java
> +    Assertions.assertThat(result.jsonPath().getList("stations", StationResponse.class)).hasSize(5)
> 1.현재 appendLineSection() 인수테스트 수정 후 최종 line의 노선들을 가져올때 size 가 0이라는 빈 값이 추가되는데 해당 원인을 찾지 못해 질문드립니다.

이 질문은 여기에 대해 질문 주신 것 같습니다 👀 
몇가지 고쳐야할 부분들이 있는데요

<img width="297" alt="스크린샷 2024-07-25 오후 2 13 19" src="https://github.com/user-attachments/assets/6e294862-f50a-49ab-88e4-5808fdb5357c">

테스트를 돌린 응답을 캡쳐했는데요
1. 현재 응답에 stations 필드가 없습니다.
2. name / color / sections 등이 모두 비어 있습니다

--- 
문제의 원인을 찾기 위해 생각해볼 것이 있습니다 🤔 
JPA 는 DB 에 있는 데이터를 가져와서 서버의 메모리에 객체의 형태로 매핑해주는 역할을 합니다.
그렇다면, 결국 첫번째로 쿼리가 내가 원하는 대로 실행되었는지를 확인해야 합니다.
현재 기본으로 프로젝트에 세팅된 것을 기준으로 보면 쿼리를 볼 수 있습니다.

`GET /lines/1` 을 수행하는 쿼리입니다.

<img width="400" alt="스크린샷 2024-07-25 오후 2 17 20" src="https://github.com/user-attachments/assets/d6ff2422-b9d5-4215-b0de-21f5927a6863">

LAZY 로 걸어두셨기 때문에 `line` 을 id 로 조회 후 `line_section`과 `station`을 join 해서 가져오는 모습이 보이네요 👀  이부분은 문제가 없어 보입니다.

그럼 의심할 수 있는 것은 
1. JPA 가 내가 만든 객체를 제대로 매핑해주지 못한다.
2. DB 에 저장이 제대로 되지 않았다

아무래도 2번이 가능성이 좀 더 높습니다.

조금 더 거슬러 올라가서 쿼리를 살펴봤는데, 예상과는 다르게 insert 쿼리가 제대로 나갑니다.

<img width="489" alt="스크린샷 2024-07-25 오후 2 22 35" src="https://github.com/user-attachments/assets/ce5ab9f6-6047-483d-9d12-e2ca91f35f24">

여기서, 첫번째 스샷의 내용을 다시 떠올려보겠습니다. 
`Line`의 name 이나 color 도 null 로 출력되었던 부분입니다.

<img width="862" alt="스크린샷 2024-07-25 오후 2 23 56" src="https://github.com/user-attachments/assets/f2d2aab3-ac45-4b7a-896e-3bc6d0943fdf">

Line 을 new 로 생성해서 넣고 있네요 😢 

---
이렇게 길게 쓴 이유는 어떤 논리로 잘못된 부분들을 찾아내었는지 한번 보여드리고 싶었습니다 😅 
JPA 라는 것도 결국엔 메모리에 담긴 데이터를 DB 에 저장했다가 꺼내오는 작업을 하는 것이고, 이것이 어떻게 동작할 지 조금씩 추론하며 문제를 풀어나가시면 좋을 것 같습니다 👍

2024-07-25 06:03 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/line/LineSectionAcceptanceTest.java
> +//      .extract();
추후 테스트를 추가하실때도, upStation 기준 중간역 추가와 downStation 기준 중간역 추가는 서로 다른 케이스로 보고 Test method 를 나누는 것을 추천 드립니다 😄

2024-07-25 06:03 UTC, pch8388 commented on src/main/java/nextstep/subway/line/LineService.java
> +  private final StationService stationService;
> 2. 또한 다른 서비스(1번 서비스, 1번 엔티티)에서 다른 엔티티 조회(2번 엔티티)시 다른 엔티티(2번 엔티티)의 서비스를 참조해야하는지 레포지토리를 참조해야하는지 궁금하다는 생각이 들었는데요, 이 부분은 취향 차이인지 아니면 서비스 혹은 레포지토리를 참조해야 한다고 한가지가 정해져있는지 궁금합니다.

이부분에서 고민을 하셨던 것 같습니다 😄 
[참고](https://github.com/next-step/atdd-subway-map/discussions/489) 에서 예전에 나누었던 토론을 읽어보시는 것도 재밌을 것 같습니다.

제 생각을 말씀드리면 상황에 따라 다르다고 생각합니다. 두 방식 모두 장단점이 있을 수 있는데요.
Service 를 주입받는다면, Service 에서 중복적으로 처리할 예외나 유효성 검증 등의 책임이 한 곳으로 모일 수 있을 것 같구요.
```java
Service {
  public Member findMemberById(Long id) {
      return memberRepository.findMemberById(id)
                                      .orElseThrow(CustomException::new);
  }
}
```

단점은 순환참조가 발생하지 않도록 신경써야 하고 서로 참조해야 할 경우가 발생한다면 또다른 우회적인 방법을 사용해야 합니다.

Repository 를 주입받는다면, Service 를 주입받았을 때의 장점을 누리지 못하지만, 순환참조 같은 문제는 발생하지 않을 겁니다.(레이어간의 방향만 잘 지킨다면..)

2024-07-25 06:03 UTC, pch8388 commented on src/main/java/nextstep/subway/line/LineSection.java
> +  @OneToOne
`사당역`은 `2호선 / 4호선` 에 속하는 것처럼, 여러 구간에 포함될 수 있을 것 같아요 😄 
`@ManyToOne`이 조금 더 자연스럽다고 생각합니다.
추가로 `@JoinColumn`은 되도록이면 지정해주시는 것이 좋습니다

2024-07-25 06:03 UTC, pch8388 commented on src/main/java/nextstep/subway/line/LineSections.java
> +      sections.add(upSection.getId().intValue(), lineSection);
sectionId 를 인덱스로 지정해서 저장하는 이유가 있을까요? 👀

2024-07-25 06:03 UTC, pch8388 commented on src/main/java/nextstep/subway/line/LineSectionRepository.java
> +  @Query("SELECT ls FROM LineSection ls JOIN ls.line ON ls.line.id = :lineId")
직접 쿼리를 만드신 이유가 있을까요? 💭

2024-07-25 06:03 UTC, pch8388 commented on src/main/java/nextstep/subway/line/LineService.java
> +    if (lastLineSection.getDownStation().getId() != stationId || lineSection.size() <= 1) {
```suggestion
    if (!lastLineSection.getDownStation().getId().eqauls(stationId) || lineSection.size() <= 1) {
```

Wrapper type 은 `==` `!=` 보다는 equals 로 비교해주세요 
[참고](https://dami97.tistory.com/24)

2024-07-25 06:03 UTC, pch8388 commented on src/main/java/nextstep/subway/line/dto/LineResponse.java
> +  private List<LineSection> sections;
Entity 를 DTO 가 그대로 가지게 하는 것보다, 필요한 필드들로 변환해서 넣도록 구현하시는 것이 좋습니다 😅

2024-07-26 14:43 UTC, dharana77 commented on src/main/java/nextstep/subway/line/LineSectionRepository.java
> +  @Query("SELECT ls FROM LineSection ls JOIN ls.line ON ls.line.id = :lineId")
join을 사용해서 query를 만들어야 된다고 생각했었는데요, 직접 query를 사용하지 않아도 되는 방법이 있을까요? ❓

2024-07-26 14:44 UTC, dharana77 commented on src/main/java/nextstep/subway/line/LineSections.java
> +      sections.add(upSection.getId().intValue(), lineSection);
id로 대체하면 될것 같은데 처음에는 id를 사용하는 것을 생각못하고 index를 구현하고 생각난 부분이라 우선 인덱스로 진행했습니다. :) 
이부분도 수정해서 반영해보겠습니다!

2024-07-26 14:46 UTC, dharana77 commented on src/main/java/nextstep/subway/line/LineService.java
> +  private final StationService stationService;
똑같은 부분에 대해서 고민을 하셨던 다른 분들도 계시군요! :)
제가 생각해보지 못했던 부분에 대해서도 언급하고 있어서 좋은 내용을 다루고 있는 것 같습니다. 좋은 내용 감사합니다! 👍

2024-07-26 14:48 UTC, dharana77 commented on src/test/java/nextstep/subway/acceptance/line/LineSectionAcceptanceTest.java
> +    Assertions.assertThat(result.jsonPath().getList("stations", StationResponse.class)).hasSize(5)
엌.. 되게 단순한 실수였군요! 말씀해주신것처럼 어떤 논리로 접근하셨는지 보여주셔서 다른 분들이 어떤 방식으로 문제가 생겼을때 해결하려고 시도하는 지 알수있어 좋았습니다. 말씀해주신 부분을 해결하고 나니 무한 순환 문제가 있었는데 from 부분에서 get을 통해 station들을 가져오는 부분들을 수정해서 문제를 해결했습니다. 해당 과정중에 말씀하신 내용이 도움이 됐던 것 같아요 👍

2024-07-26 14:50 UTC, dharana77 commented on build.gradle
> +sourceCompatibility = "15"
이 부분은 아마 string의 .formatted()를 사용하려 시도했던 적이 있었는데 이전 리뷰에서 String.format()을 사용하도록 수정했었습니다. string.formatted를 사용하려 하니 인텔리제이에서 버전 변경 권고가 떠서 버전을 변경하는 방식으로 진행했었습니다. 🤔

2024-07-27 04:44 UTC, dharana77 commented
변경된 부분과 질문사항에 대해서 한번만 확인해주시면 감사하겠습니다!

질문 부분
1. https://github.com/next-step/atdd-subway-path/pull/831#discussion_r1693202369

부족한 부분 말씀해주시면 다음 단계에서 같이 반영해보겠습니다. :) 좋은 주말되세요! 
다음단계에서 뵙겠습니다.

2024-07-28 02:02 UTC, pch8388 approved these changes
남겨드린 코멘트 확인하셔서 2단계 수행시 반영부탁드립니다 👍 
Merge 하겠습니다

2024-07-28 02:02 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/line/LineSectionAcceptanceTest.java
> +      .isEqualTo(List.of("종합운동장", "새로운 상행역", "잠실"));
```suggestion
      .isEqualTo(List.of("종합운동장", "새로운 상행역", "잠실새내"));
```

👀

2024-07-28 02:02 UTC, pch8388 commented on src/main/java/nextstep/subway/line/LineSectionRepository.java
> +  @Query("SELECT ls FROM LineSection ls JOIN ls.line ON ls.line.id = :lineId")
Line 과 관계가 맺어져 있기 때문에 Line 을 통해서 가져올수도 있습니다 😅 
Line 의 노선을 삭제하는 기능이기 때문에 비즈니스 로직 상으로도 Line 에서 appendSection 에 대비되는 메서드를 만드는 게 자연스럽습니다

2024-07-28 02:02 UTC, pch8388 commented on src/main/java/nextstep/subway/line/LineSectionRepository.java
> +  void deleteByLineIdAndStationId(Long stationId);
삭제도 line 을 통해 하는 게 더 자연스럽다고 생각해요

2024-07-28 02:02 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/line/LineAcceptanceTest.java
> +public class LineAcceptanceTest {
<img width="490" alt="스크린샷 2024-07-28 오전 11 00 40" src="https://github.com/user-attachments/assets/863b6952-8562-4f35-aefa-0ca18777b984">

실패하는 테스트를 모두 성공시켜 주세요 😢 

실습에 나와있는 것처럼 단위테스트도 모두 채워주세요
<img width="684" alt="스크린샷 2024-07-28 오전 11 01 33" src="https://github.com/user-attachments/assets/718f0c2c-e42f-45eb-933f-944ad92508ad">

2024-07-28 02:03 UTC, merged