2단계 - 구간 제거 요구사항 반영
next-step/atdd-subway-path pull request #833
Opened 2024-07-21 14:46 UTC by sazzeo

2024-07-22 11:23 UTC, heoseungyeon requested changes
안녕하세요 지영님!
2단계 미션 잘 구현해주셨네요 🔥 
커멘트 남긴 부분 확인 해주시고 리뷰 요청 부탁드릴게요!!

2024-07-22 11:23 UTC, dia312 commented on src/main/java/nextstep/subway/exceptions/ErrorMessage.java
> +}
👍

2024-07-22 11:23 UTC, dia312 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        sections.removeStation(stationId);
Line.removeLastStation() 메서드도 이름을 변경해야 되지 않을까요?

2024-07-22 11:23 UTC, heoseungyeon commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        sections.removeStation(stationId);
Line 입장에서 구간을 삭제하는게 더 맞을 거 같은데 어때요?

2024-07-22 11:23 UTC, heoseungyeon commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        void successTest2() {
[TDD 메서드 명명 규칙](https://it-is-mine.tistory.com/3) 에 맞게 메서드명을 작성해보는 경험을 해봐도 좋을 것 같아요:)

2024-07-22 11:23 UTC, heoseungyeon commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        @Test
```suggestion
        @DisplayName("상행종점역을 삭제할 수 있다.")
        @Test
```

2024-07-22 11:23 UTC, heoseungyeon commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +
해당 인수 테스트에서 자주 사용되는 '역 순서 검증'을 메서드로 분리해보셨네요 👍

2024-07-22 11:23 UTC, heoseungyeon commented on src/test/java/nextstep/subway/utils/HttpStatusAssertion.java
> +}
상태 검증 코드 분리 👏 👏 👏

2024-07-22 11:23 UTC, heoseungyeon commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        }
존재하지 않는 stationId 일 경우, 예외 처리가 필요해 보입니다!

2024-07-22 15:09 UTC, sazzeo commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +
이부분을 좀더 범용적으로 바꿔보려다가 이 정도로 우선 만족했습니다 ㅎㅎㅎ

2024-07-22 15:19 UTC, sazzeo commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        void successTest2() {
이 부분은...Displayname이 있으니까 딱히 중요할것 같지 않아서 간단하게 지었습니다...
첨부해주신 레퍼런스 참고해서 고쳐보겠습니다...!

2024-07-22 15:35 UTC, sazzeo commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        sections.removeStation(stationId);
꼼꼼한 피드백 감사합니다!!!

2024-07-23 11:09 UTC, heoseungyeon commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        void successTest2() {
저도 지영님 말씀처럼 @DisplayName 에서 충분한 설명이 되는데 굳이?! 라는 생각이 지배적이긴 하지만

어노테이션이 아닌 메서드명이 메서드 행위를 설명할 수 있어야 한다.
메서드명을 given/when/then 에 맞게 작명할 수 있다. -> 작명도 많이 해봐야 느는것 같더라구요 🥲
위 2가지 입장에서 작성해보면 좋은 경험이 되실 것 같아 의견을 드렸습니다 :)
@Nested class 에 When 절을 내포하고 있으면 메서드명은 given, when 절로 작성하면 될 것 같은데 저는 영어로 작성해볼 것 같아요. 한글은 @DisplayName에도 있기도 하고, 한글은 언더스코어(_)로 띄어쓰기를 하게 돼서 테스트 메서드명으론 많이 길어지더라구요.

2024-07-23 12:33 UTC, sazzeo commented
리뷰주신부분 반영했습니다
빼먹은 부분이 있을 수 있습니다 ㅠ 
제가 영어실력이... ㅎㅎㅎㅎ 열심히 공부해보겠습니다

2024-07-23 12:55 UTC, heoseungyeon approved these changes
안녕하세요 지영님!
빠르게 피드백 적용해주셨네요 👍 👍 
분명히 귀찮은 부분이 있었을텐데 성실히 적용해주신 부분이 멋지십니다 💯 
이번 단계는 머지하도록 할게요, 다음 단계 진행해주세요 ⏭️

2024-07-23 12:55 UTC, dia312 commented on src/test/java/nextstep/subway/line/domain/SectionsTest.java
> +        }
예외케이스 도메인 테스트 👍

2024-07-23 12:55 UTC, heoseungyeon commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        void whenShowNotExistThanReturn400() {
💯 💯 💯

2024-07-23 12:55 UTC, merged