3단계 - 경로 조회 기능
next-step/atdd-subway-path pull request #834
Opened 2024-07-21 17:16 UTC by pilming44

처음 요구사항 문서를 봤을땐 조금 막막했는데요
오늘 모짝미 & 네트워킹 데이 하는 날이라 먼저 3단계를 끝내신 분과 페어프로그래밍을 하면서
어떤 방향으로 할지 정리가 됐어요! 그래서 집에 와서 그걸 토대로 만들어봤습니다!
(컨트롤러, 서비스 구현에서 궁금한게있어서 코멘트 달았습니다!)
미리 리뷰 감사합니다! ( _ _)

2024-07-22 11:05 UTC, catsbi requested changes
재현님 마지막 경로 조회 미션까지 잘 구현해주셨어요. 
다익스트라 라이브러리 사용하는게 좀 어려울 수 있는데 잘 만들어 주신 것 같고, 테스트도 잘 작성해주신 것 같아요. 그런데 지금 경로 탐색 도메인쪽의 재사용성을 좀 더 높혀볼 수 있을 것 같아요. 

리뷰 확인 후 다시 리뷰요청 부탁드려요!

2024-07-22 11:05 UTC, catsbi commented on src/main/java/nextstep/subway/controller/PathController.java
> +    public ResponseEntity<PathResponse> getPath(@RequestParam Station source, @RequestParam Station target) {
Controller Layer에 Entity가 그대로 노출되는건 그다지 권장드리지 않습니다.  Station은 내부 필드가 적기 떄문에 문제가 없어보이지만, 서비스레이어에서 UI 영역으로 도메인 계층 정보가 노출되었다는 것인데 불필요한 정보가 외부로 노출될수도 있고, 엔티티의 정보가 많을수록 불필요한 조회가 될 수도 있기 때문이에요.

2024-07-22 11:05 UTC, catsbi commented on src/main/java/nextstep/subway/dto/PathResponse.java
> +    private List<Station> stations = new ArrayList<>();
응답정보에 엔티티를 그대로 노출하기보단 StationResponse와 같은 외부 노출용 View 객체를 만들어서 제공하는게 낫지 않을까요?

2024-07-22 11:05 UTC, catsbi commented on src/main/java/nextstep/subway/entity/PathFinder.java
> +    public void addLine(Line line) {
addAllLIne과 같은 함수도 요구빈도가 높을 것 같은데 만들어서 제공하면 좋을 것 같네요.

2024-07-22 11:05 UTC, catsbi commented on src/main/java/nextstep/subway/entity/PathFinder.java
> +        long shortestDistance = (long) dijkstraShortestPath.getPathWeight(source, target);
개행을 통해 코드의 가독성을 좀 챙겨봐도 좋을 것 같아요! 그리고 PathFinder는 재사용성을 고려한 리팩토링을 해보면 어떨까요? 
지금은 경로 탐색마다 PathFinder 객체를 새로 생성해야하는데, 필요한 정보들만 분리하여 생성할 수 있는 ConditionBuilder가 하나 나온 뒤 빌딩&탐색 하는 방식으로 해봐도 좋을 것 같아요. 

```java
pathFinder.searchBuilder()
    .graph(new WeightedMultigraph(DefaultWeightedEdge.class))
    .stations(line.getStations())
    .sections(line.getSectionList())
    .build()
    .search();
```

이런식으로 가능할 듯 싶네요!

2024-07-22 11:05 UTC, catsbi commented on src/test/java/nextstep/subway/entity/PathFinderTest.java
> +class PathFinderTest {
테스트가 꼼꼼하게 잘 작성되어 있네요 👍

2024-07-22 11:05 UTC, catsbi commented on src/test/java/nextstep/subway/entity/PathFinderTest.java
> +    @DisplayName("출발역과 도착역이 같은 경우")
무엇을/어떤조건으로/어떤결과가 예상되는지에 대한 내용이 있으면 좋을 것 같아요. 콘솔창에 해당 내용만보고 무슨 테스트를 해서 어떤 결과가 유추되는지를 알 수 없어요. 지금은 괜찮지만 테스트가 수 백개가 넘어가면 코드를 하나하나 보면서 테스트를 파악할수는 없습니다

2024-07-22 11:05 UTC, catsbi commented on src/main/java/nextstep/subway/service/PathService.java
> +        PathFinder pathFinder = new PathFinder();
PathFinder가 매 번 소비되는 휘발성 객체보단 좀 더 재사용이 가능한 도메인으로 컴포넌트로 사용될 수도 있을 것 같네요!

2024-07-22 15:53 UTC, pilming44 commented
리뷰 내용을 반영해서 수정해봤습니다! 
이전 단계에서도 엔티티를 노출해서 수정했었는데.. 작업을 새벽에 하다보니 또 똑같은 실수를했네요.. ㅠ^ㅠ 민망합니닷
그리고 말씀해주신 PathFinder를 빌더패턴을 적용하는것과, 컴포넌트로 사용하는것 두가지의 방법 중 
빌더패턴을 직접 만들어서 사용하는건 한번도 해보지않아서 빌더패턴을 적용해서 해봤습니다!
혹시나 제가 리뷰 내용에 대해서 잘못 이해했다면 말씀해주세요!

2024-07-23 12:25 UTC, catsbi approved these changes
재현님 피드백 반영 잘 해주셨어요 👍 
아주 쪼금 고민해보면 좋을 부분들이 있어 피드백 남겨드렸는데, 다음 미션 하시면서 같이 고민해보면 좋을 것 같아 머지드리도록 하겠습니다. 미션 진행하시느라 고생많으셨어요. 남은 미셔들도 화이팅입니다!

2024-07-23 12:25 UTC, catsbi commented on src/main/java/nextstep/subway/dto/PathResponse.java
> +                .map(station -> new StationResponse(station.getId(), station.getName()))
DTO에서 Entity를 의존하는건 큰 문제가 되지 않으니 다음과 같이 리팩토링해볼수도 있을 것 같네요. 
```suggestion
                .map(StationResponse::from)
```

그럼 차후 Station과 StationResponse의 내부 필드가 추가되거나 하더라도 PathResponse까지 와서 매개변수를 수정하고 할 필요가 없어질 수 있겠죠.

2024-07-23 12:25 UTC, catsbi commented on src/main/java/nextstep/subway/entity/PathFinder.java
> +            return new PathFinder(this.routeMap);
여기도 결국 내부적으로 PathFinder를 생성해주고 있는데요. PathFinder라는 개념을 휘발성 객체가 아닌 재사용가능한 객체로 작업할 수 있다고 생각하거든요. 

즉, 이 Builder에서 만드는건 PathFInder가 아닌 Request인것이죠. PathFindRequest를 만들어서 pathFinder에게 findPath를 요청하면, 무상태 컴포넌트 pathFInder는 해당 컨디션을 받아서 검색만 수행하는것이죠. 

즉, 경로 탐색에 필요한 데이터를 빌딩하는 RequestBuilder와 , 빌드된 검색 조건을가지고 검색만 수행하는 무상태성 패스파인더,
그리고 이 패스파인더가 실제로 사용할 알고리즘을 주입받아서(ex: 다익스트라 알고리즘) 사용하는 부분 이렇게 나뉘어서 동작을 한다면,
차후 더 좋은 알고리즘이 나올 경우 주입된 PathFinder 인터페이스의 구현체만 바꿔주면 되고, 요청 정보가 바뀔경우 빌더만 바꿔주면 되겠죠. 즉 책임을 각각 더 분리해보면 좋을 것 같습니다 ㅎㅎ

그리고 빌더의 조건도 제가 임의로 작성한건데 좀 더 범용적으로 만들어서 내부적으로 호출하는식도 괜찮습니다. 
addLine이 아니라 아예 addVertext으로 만들수도 있겠죠 ㅎㅎ

2024-07-23 12:25 UTC, catsbi commented on src/main/java/nextstep/subway/service/PathService.java
> +        PathFinder pathFinder = PathFinder.searchBuild()
빌더 호출이라면 searchBuilder가 좀 더 적절해보이네요!

2024-07-23 12:25 UTC, catsbi commented on src/main/java/nextstep/subway/service/PathService.java
> +        }
두 값중 하나만 없어도 경로탐색은 수행할 수 없으니 최상단에 유효성 검증을 놓으면 더 간결해질 것 같네요. 

```suggestion
        if (pathRequest.getSource() || pathRequest.getTarget()) {
            throw new IllegalArgumentException("Invalid Path Request - source: [], target: {}");
        }
        
        Station sourceStation = getStation(...);
        Station targetStation = getStation(...);
        
        ...
```

2024-07-23 12:25 UTC, merged