3단계 - 경로 조회 기능
next-step/atdd-subway-path pull request #837
Opened 2024-07-23 22:55 UTC by ninjasul

안녕하세요, 박동엽입니다.

경로 조회 기능 요구사항 구현과 인수테스트를 작성 해 보았습니다.

감사합니다.

2024-07-24 07:42 UTC, pch8388 requested changes
3단계 전체적으로 잘수행해주셨습니다 👍 
조금 더 고쳐보면 좋을 것 같아요 😄 
코멘트 남겨드린 부분 수정 후 리뷰요청 해주세요 🔥

2024-07-24 07:42 UTC, pch8388 commented on src/main/java/nextstep/subway/application/strategy/addition/AddSectionToEmptySectionsStrategy.java
> +public class AddSectionToEmptySectionsStrategy implements SectionAdditionStrategy {
비어있는 경우도 잘 추가해주셨네요 💯 
List 로 의존성을 주입받고 있으니 어떤 전략부터 체크를 할지 순서를 추가해줘도 좋을 것 같아요 😄

2024-07-24 07:42 UTC, pch8388 commented on src/main/java/nextstep/subway/application/DefaultLineCommandService.java
> +        line.addSection(strategy, section);
피드백반영 👍

2024-07-24 07:42 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +        assertThat(statusCode).isBetween(400, 599);
예외 상황에서 반환하는 status code 가 일정하지 않아도 될까요? 🤔 
잘못된 역을 클라이언트에서 준 것인데, 500 을 반환하게 하신 이유가 있을까요?
만약 두개가 반환해야 하는 status code 가 다르다면, 둘은 다른 케이스로 봐야하지 않을까요? 💭

2024-07-24 07:42 UTC, pch8388 commented on src/test/java/nextstep/subway/application/DefaultPathFinderTest.java
> +public class DefaultPathFinderTest {
단위 테스트를 조금 더 다양한 케이스로 구현해보시는 것이 좋습니다 😄

2024-07-24 07:42 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/model/Path.java
> +    public static Path from(List<Line> lines, Station source, Station target) {
[이펙티브 자바](https://github.com/woowacourse-study/2022-effective-java/blob/main/02%EC%9E%A5/%EC%95%84%EC%9D%B4%ED%85%9C_01/%EC%83%9D%EC%84%B1%EC%9E%90_%EB%8C%80%EC%8B%A0_%EC%A0%95%EC%A0%81_%ED%8C%A9%ED%84%B0%EB%A6%AC_%EB%A9%94%EC%84%9C%EB%93%9C%EB%A5%BC_%EA%B3%A0%EB%A0%A4%ED%95%98%EB%9D%BC.md#%EC%BB%A8%EB%B2%A4%EC%85%98) 의 내용처럼 일반적으로 인자가 여러개인 경우에는 `of`라는 네이밍을 많이 씁니다 😅

2024-07-24 07:42 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/model/Path.java
> +    public List<Station> getStations() {
개인적 취향일수도 있습니다만, 클래스 내부의 소스코드 구조도 일관성 / 가독성을 고려하시는 것이 좋습니다 🤔 

```
생성자
인스턴스 생성 관련 메서드(ex - 팩토리메서드)
비즈니스 로직 메서드
getter 와 같이 조금 덜 중요한 메서드
```
의 형태로 일관되게 구성하는 것이 가독성이 가장 좋다고 생각합니다

2024-07-24 07:42 UTC, pch8388 commented on src/main/java/nextstep/subway/application/dto/SectionResponse.java
> +    public void setLineId(Long lineId) {
[객체지향 생활체조](https://edu.nextstep.camp/s/alzi01uF/ls/Duq9oJw2) 
> 규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.

게터는 어쩔수 없는 부분이 존재하긴 해도, 세터는 지양해주세요 😅 (현재 쓰고 계시지 않는 것 같기도 하구요)

2024-07-24 07:42 UTC, pch8388 commented on src/main/java/nextstep/subway/application/DefaultPathFinder.java
> +            for (Section section : line.getOrderedUnmodifiableSections()) {
[객체지향 생활체조](https://edu.nextstep.camp/s/alzi01uF/ls/Duq9oJw2)
> 규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.

들여쓰기를 줄이도록 해보세요 😄

2024-07-24 07:42 UTC, pch8388 commented on src/main/java/nextstep/subway/application/strategy/addition/AddSectionAfterUpStationStrategy.java
> +        Section existingSection = findExistingSectionForNewAddition(line.getSections(), newSection).get();
```suggestion
        Section existingSection = findExistingSectionForNewAddition(line.getSections(), newSection).orElseThrow(~~~);
```
`canApply` 를 통과한 상태라 `Optional.empty()` 라면 예외가 발생하도록 하는 게 맞을 것 같아요 🤔 
실제로도 `Optional.empty()` 상태라면 `NoSuchElementException` 가 발생하기 때문에, 사용자 정의 예외를 넣어 주는 선택이 더 좋다고 생각합니다

2024-07-24 11:45 UTC, ninjasul commented on src/main/java/nextstep/subway/domain/model/Path.java
> +    public static Path from(List<Line> lines, Station source, Station target) {
변경 해 보겠습니다.

2024-07-24 11:46 UTC, ninjasul commented on src/main/java/nextstep/subway/domain/model/Path.java
> +    public List<Station> getStations() {
변경 해 보겠습니다.

2024-07-24 11:48 UTC, ninjasul commented on src/main/java/nextstep/subway/application/dto/SectionResponse.java
> +    public void setLineId(Long lineId) {
setter는 제거 해 보겠습니다.

2024-07-24 12:05 UTC, ninjasul commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +        assertThat(statusCode).isBetween(400, 599);
두 케이스를 분리 해 보겠습니다.

2024-07-24 13:40 UTC, ninjasul commented on src/main/java/nextstep/subway/application/strategy/addition/AddSectionToEmptySectionsStrategy.java
> +public class AddSectionToEmptySectionsStrategy implements SectionAdditionStrategy {
@Order 를 추가하여 반영 해 보겠습니다.

2024-07-24 13:40 UTC, ninjasul commented on src/main/java/nextstep/subway/application/DefaultPathFinder.java
> +            for (Section section : line.getOrderedUnmodifiableSections()) {
반영 해 보겠습니다.

2024-07-24 13:47 UTC, ninjasul commented on src/test/java/nextstep/subway/application/DefaultPathFinderTest.java
> +public class DefaultPathFinderTest {
인수테스트와 유사하게 테스트 케이스들을 추가해 보겠습니다.

2024-07-25 06:22 UTC, pch8388 approved these changes
리팩토링 잘해주셨습니다 💯 
미션 수고 많으셨습니다 👏 
추가로 이야기 하고 싶으신 부분은 DM 으로 연락주시면 될 것 같습니다 😄

2024-07-25 06:22 UTC, pch8388 commented on src/main/java/nextstep/subway/application/DefaultPathFinder.java
> +        lines.forEach(this::addLineToGraph);
💯

2024-07-25 06:23 UTC, merged