1단계 - 구간 추가 요구사항 반영
next-step/atdd-subway-path pull request #839
Opened 2024-07-24 14:15 UTC by zunghyo

리뷰어님 안녕하세요!
1단계 구현이 많이 늦어졌지만 리뷰 잘 부탁드립니다!

2024-07-25 05:42 UTC, seondongpyo requested changes
효정님, 안녕하세요. 이번 미션을 함께하게 된 표선동이라고 합니다.
1단계 미션 잘 구현해주셨네요 👍 
몇 가지 코멘트 드렸는데 확인 후 다시 리뷰 요청을 부탁 드리겠습니다 🔥

2024-07-25 05:42 UTC, seondongpyo commented on src/main/java/nextstep/subway/common/exception/ExceptionResponse.java
> +    String message;
접근 제어자를 생략하신 이유가 있으실까요?

2024-07-25 05:42 UTC, seondongpyo commented on src/main/java/nextstep/subway/common/exception/SubwayExceptionType.java
> +    INTERNAL_SERVER_ERROR("500", "Server Error"),
HTTP 응답 코드와 동일한 코드를 사용하실 거라면, 기존에 잘 정의된 상수를 활용해보는 건 어떨까요?
```suggestion
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR.value()), "Server Error"),
```

2024-07-25 05:42 UTC, seondongpyo commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        line.getLineSections().addSection(lineSection);
값을 꺼내서 처리하는 대신에, 메시지를 보내서 처리해보면 어떨까요?
```suggestion
        line.addSection(lineSection);
```

2024-07-25 05:42 UTC, seondongpyo commented on src/main/java/nextstep/subway/line/domain/LineRepository.java
> +}
파일의 마지막에는 개행을 추가해보면 어떨까요?
https://velog.io/@doondoony/posix-eol

![image](https://github.com/user-attachments/assets/91b7c232-5708-4fa4-8568-5f19bdcecc4e)

2024-07-25 05:42 UTC, seondongpyo commented on src/main/java/nextstep/subway/line/domain/entity/LineSections.java
> +public class LineSections {
일급 컬렉션 활용 👍

2024-07-25 05:42 UTC, seondongpyo commented on src/main/java/nextstep/subway/line/domain/entity/LineSections.java
> +public class LineSections {
해당 클래스의 전체적인 코드 포맷팅 확인 부탁 드릴게요.

2024-07-25 05:42 UTC, seondongpyo commented on src/main/java/nextstep/subway/line/domain/entity/LineSections.java
> +        }
객체지향 생활 체조 원칙 중 `규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.` 항목을 참고해주세요.

2024-07-25 05:42 UTC, seondongpyo commented on src/test/java/nextstep/subway/acceptance/line/LineAcceptanceTest.java
> +public class LineAcceptanceTest {
`@DirtiesContext` 대신에, 기존에 정의되어 있는 `AcceptanceTest` 클래스를 활용해보는 건 어떨까요?

2024-07-25 05:42 UTC, seondongpyo commented on src/test/java/nextstep/subway/acceptance/line/LineAcceptanceTest.java
> +    private static Map<String, Long> stationIds = new HashMap<>();
`static` 키워드를 붙여주신 이유가 있으실까요?

2024-07-25 05:42 UTC, seondongpyo commented on src/test/java/nextstep/subway/acceptance/line/LineAcceptanceTest.java
> +        stationIds.put("강남역", 지하철역_생성_후_id_추출("강남역"));
Nit: 자주 사용하는 역 이름이라면, 매번 하드 코딩하는 대신에 상수로 선언하여 재사용해 볼 수 있을 것 같습니다.

2024-07-25 05:42 UTC, seondongpyo commented on src/test/java/nextstep/subway/acceptance/line/LineSectionAcceptanceTest.java
> +    private static final Map<String, Long> stationIds = new HashMap<>();
상수 선언을 의도하신 거라면, 관례에 맞게 이름을 대문자로 작성해보면 어떨까요?
```suggestion
    private static final Map<String, Long> STATION_IDS = new HashMap<>();
```

2024-07-25 05:42 UTC, seondongpyo commented on src/test/java/nextstep/subway/acceptance/line/LineSectionAcceptanceTest.java
> +        ExtractableResponse<Response> 지하철구간_생성_응답 = 지하철구간_생성(신분당선_id, 지하철역_id("신사역"), 지하철역_id("논현역"), 10L);
여기서 새롭게 추가하려는 지하철 구간은 이미 추가된 구간과 동일한 구간이 아닐까요?

2024-07-25 05:42 UTC, seondongpyo commented on src/test/java/nextstep/subway/acceptance/line/LineSectionAcceptanceTest.java
> +        stationIds.put("역삼역", 지하철역_생성_후_id_추출("역삼역"));
각각의 테스트 케이스에서 매번 특정 지하철역의 id를 가져올 때마다 역 이름을 전달해야 하는데,
각각의 지하철역 id를 멤버 변수로 선언하고 이를 재사용하는 방식은 어떨까요?

```java
public class LineSectionAcceptanceTest {
    private Long 신사역_id;
    private Long 논현역_id;
    private Long 신논현역_id;
    private Long 강남역_id;
    private Long 역삼역_id;

    @BeforeEach
    public void setUp() {
        신사역_id = 지하철역_생성_후_id_추출("신사역");
        논현역_id = 지하철역_생성_후_id_추출("논현역");
        신논현역_id = 지하철역_생성_후_id_추출("신논현역");
        강남역_id = 지하철역_생성_후_id_추출("강남역");
        역삼역_id = 지하철역_생성_후_id_추출("역삼역");
    }
    
    /**
     * Given 지하철 노선이 주어지고
     * When 하행 종착역에 새로운 구간을 등록하면
     * Then 구간이 등록된다.
     */
    @DisplayName("하행 종착역에 새로운 구간을 생성한다.")
    @Test
    void createSection1() {
        //given
        Long 신분당선_id = 지하철노선_생성_후_ID_반환("신분당선", "bg-red-600", 신사역_id, 논현역_id, 10L);

        // when
        ExtractableResponse<Response> 지하철구간_생성_응답 = 지하철구간_생성(신분당선_id, 논현역_id, 신논현역_id, 10L);

        // then
        assertThat(지하철구간_생성_응답.statusCode()).isEqualTo(HttpStatus.CREATED.value());
    }
}
```

2024-07-25 22:22 UTC, zunghyo commented on src/main/java/nextstep/subway/common/exception/ExceptionResponse.java
> +    String message;
의도적으로 생략한건 아니고 실수입니다. 찾아주셔서 감사합니다 😂

2024-07-25 22:34 UTC, zunghyo commented on src/main/java/nextstep/subway/common/exception/SubwayExceptionType.java
> +    INTERNAL_SERVER_ERROR("500", "Server Error"),
좋은 의견 감사합니다! 기존에 정의된 상수를 사용하면 가독성도 좋아지고, 의미를 좀 더 정확하게 전달할 수 있을 것 같습니다 👍🏼

2024-07-25 22:43 UTC, zunghyo commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        line.getLineSections().addSection(lineSection);
값 객체에 직접 접근하는 대신 메시지를 보내도록 수정하겠습니다!

2024-07-25 22:51 UTC, zunghyo commented on src/main/java/nextstep/subway/line/domain/LineRepository.java
> +}
생각지도 못 했던 부분이네요. 알려주셔서 감사합니다 😊

2024-07-26 08:41 UTC, zunghyo commented on src/main/java/nextstep/subway/line/domain/entity/LineSections.java
> +        }
넵! 객체지향 생활 체조 원칙 적용해서 가독성 개선하겠습니다.

2024-07-26 09:20 UTC, zunghyo commented on src/test/java/nextstep/subway/acceptance/line/LineSectionAcceptanceTest.java
> +        ExtractableResponse<Response> 지하철구간_생성_응답 = 지하철구간_생성(신분당선_id, 지하철역_id("신사역"), 지하철역_id("논현역"), 10L);
앗 테스트코드가 실패했었군요. 새로운 구간이 상행 종착역에 추가되도록 개선하겠습니다.

2024-07-27 03:44 UTC, zunghyo commented on src/test/java/nextstep/subway/acceptance/line/LineSectionAcceptanceTest.java
> +        stationIds.put("역삼역", 지하철역_생성_후_id_추출("역삼역"));
너무 좋은 방법인 것 같습니다 👍🏼👍🏼👍🏼
저도 코드가 지저분하다고 생각하고 있었는데 이번 미션 수행하면서
깔끔하게 정리하도록 하겠습니다!

2024-07-27 03:52 UTC, zunghyo commented on src/test/java/nextstep/subway/acceptance/line/LineSectionAcceptanceTest.java
> +    private static final Map<String, Long> stationIds = new HashMap<>();
음...재사용하려던 목적으로 작성했는데 지금 보니 접근지정자도 private이고 Map을 사용하는 것 자체가 비효율적인 것 같습니다. 이 부분은 전체적으로 개선하도록 하겠습니다!

2024-07-27 03:57 UTC, zunghyo commented on src/test/java/nextstep/subway/acceptance/line/LineAcceptanceTest.java
> +    private static Map<String, Long> stationIds = new HashMap<>();
LineSectionAcceptanceTest의 stationIds을 재사용하려고 했었는데 
구현하다보니 HashMap을 새로 생성해서 사용해 버린 것 같습니다 😰
혼란스럽지 않게 다음부턴 더 꼼꼼하게 확인하고 커밋하도록 하겠습니다!

2024-07-27 04:06 UTC, closed without merging