3단계 - 경로 조회 기능
next-step/atdd-subway-path pull request #852
Opened 2024-07-30 13:56 UTC by zunghyo

선동님 안녕하세요!
지난번에 요청하셨던 코드 포멧팅 전체 파일에 적용했습니다.
이번 미션을 통해서 커밋 전에 포멧팅하는 습관을 길러야겠습니다 😊
이번 코드 리뷰도 잘 부탁드립니다!

2024-07-31 04:14 UTC, seondongpyo requested changes
마지막 단계도 잘 구현해주셨네요 👍 
몇 가지 코멘트 드렸는데 확인 후 다시 리뷰 요청을 부탁 드리겠습니다 🔥

2024-07-31 04:14 UTC, seondongpyo commented on src/main/java/nextstep/subway/line/application/LineService.java
> +            lineRequest.getDistance());
Nit: 개인적으로는 모든 파라미터를 줄바꿈으로 처리하는 게 가독성이 더 낫지 않을까란 의견 드려봅니다.
```suggestion
        LineSection lineSection = new LineSection(
            line,
            stationRepository.findByIdOrThrow(lineRequest.getUpStationId()),
            stationRepository.findByIdOrThrow(lineRequest.getDownStationId()),
            lineRequest.getDistance()
        );
```

2024-07-31 04:14 UTC, seondongpyo commented on src/main/java/nextstep/subway/path/application/PathService.java
> +    @Transactional
`@Transactional`을 해당 메서드 레벨에 추가해주신 이유가 있으실까요?

2024-07-31 04:14 UTC, seondongpyo commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        }
해당 검증은 `PathFinder` 내부에서 처리해보는 건 어떨까요? 서비스 레이어를 거치지 않고 `PathFinder`의 `find()`를 직접 호출하는 경우 출발역과 도착역이 같다면 의도치 않은 결과가 나올 것 같네요.

2024-07-31 04:14 UTC, seondongpyo commented on src/main/java/nextstep/subway/path/application/ShortestPathFinder.java
> +public class ShortestPathFinder implements PathFinder {
단위 테스트를 작성해보는 건 어떨까요?

2024-07-31 04:14 UTC, seondongpyo commented on src/main/java/nextstep/subway/path/application/ShortestPathFinder.java
> +    private WeightedMultigraph<Station, DefaultWeightedEdge> graph = new WeightedMultigraph<>(
재할당될 경우가 없다면 `final` 키워드를 추가하여 불변으로 만들어보면 어떨까요?

2024-07-31 04:14 UTC, seondongpyo commented on src/test/java/nextstep/subway/acceptance/path/PathAcceptanceTest.java
> +public class PathAcceptanceTest {
이전에 말씀 드렸던 `AcceptanceTest`를 적용해보는 건 어떨까요? https://github.com/next-step/atdd-subway-path/pull/839#discussion_r1690828397

2024-07-31 04:14 UTC, seondongpyo commented on src/test/java/nextstep/subway/unit/LineSectionsTest.java
> +    class DeleteSection {
상행종점역 또는 하행종점역을 삭제하는 테스트도 추가해보면 어떨까요?

2024-07-31 04:14 UTC, seondongpyo commented on src/test/java/nextstep/subway/unit/PathServiceMockTest.java
> +    Long targetId = 2L;
해당 클래스 내부에서만 사용하는 변수라면 접근 제어자를 `private`으로 선언해보면 어떨까요?

2024-07-31 04:14 UTC, seondongpyo commented on src/test/java/nextstep/subway/unit/PathServiceMockTest.java
> +        when(pathFinder.find(lines, source, target)).thenReturn(expectedPathResponse);
현재의 조건만 보자면 교대역부터 양재역까지는 연결된 구간이라고 볼 수 있을까요?
서로 지하철 노선도 다르고 교대역부터 양재역 사이의 지하철 역들이 구간으로 이어져 있지 않은데,
과연 이 테스트가 정말 최단 경로를 반환하는지를 검증한다고 볼 수 있을지 고민해보시면 좋을 것 같아요.

2024-07-31 22:30 UTC, zunghyo commented on src/main/java/nextstep/subway/path/application/PathService.java
> +    @Transactional
다른 코드를 복사해서 사용하다가 실수로 지우지 않았습니다. 주의하겠습니다!

2024-08-03 03:19 UTC, zunghyo commented on src/test/java/nextstep/subway/unit/PathServiceMockTest.java
> +        when(pathFinder.find(lines, source, target)).thenReturn(expectedPathResponse);
음 구간이 연결되지 않았고, 최단 거리에 대한 검증이라고 보긴 어려울 것 같네요.
다시 구현해 보겠습니다!

2024-08-05 03:34 UTC, seondongpyo approved these changes
피드백 잘 반영해주셨네요 👍 
이번 단계는 여기서 merge 하도록 하겠습니다.
그동안 미션 진행하시느라 고생 많으셨고, 다음 미션도 힘내시길 응원하겠습니다 🔥

2024-08-05 03:34 UTC, seondongpyo commented on src/test/java/nextstep/subway/unit/ShortestPathFinderTest.java
> +class ShortestPathFinderTest {
👍

2024-08-05 03:34 UTC, seondongpyo commented on src/test/java/nextstep/subway/acceptance/path/PathAcceptanceTest.java
> +public class PathAcceptanceTest extends AcceptanceTest {
`AcceptanceTest` 클래스를 상속 받아서 공통 로직을 잘 처리해주셨네요 👍

2024-08-05 03:34 UTC, merged