🚀 3단계 - 경로 조회 기능
next-step/atdd-subway-path pull request #859
Opened 2024-08-03 18:25 UTC by jiyoung928

열심히 구현해보고는 있는데 속도가 안나네요ㅠㅠ 늦었지만 차근차근 미션 수행 해보겠습니다..!
이번 코드리뷰도 잘 부탁드립니다!

2024-08-04 13:59 UTC, Flamme1004K requested changes
안녕하세요!

3단계 미션 고생하셨습니다! 몇 가지 코멘트를 남겼으니 확인 후 리뷰 요청 부탁드립니다.

감사합니다!

2024-08-04 13:59 UTC, Flamme1004K commented on src/main/java/nextstep/subway/domain/path/SectionEdge.java
> +public class SectionEdge extends DefaultWeightedEdge {
jgrapht를 상속하지 않고, 도메인과 라이브러리의 결합하지 않도록 domain 코드를 작성해 보시겠어요?

2024-08-04 13:59 UTC, Flamme1004K commented on src/main/java/nextstep/subway/service/path/PathService.java
> +        Map<Long, Station> stationMap = getStationMap(stationIds);
하나의 최단경로를 가지고 올 수 있는 클래스를 하나 만들어 보시겠어요? 이 안에 lines와, source에 대한 역과, target에 대한 역을 주고 최단 경로를 가지고 오는 로직이 있을 것 같네요.

추가로, 언제든지 라이브러리를 변경할 수 있는 구조로 만들어보세요.

2024-08-04 13:59 UTC, Flamme1004K commented on src/main/java/nextstep/subway/service/path/ShortestPathFinder.java
> +    private final WeightedMultigraph<Long, DefaultWeightedEdge> graph;
graph를 전역으로 설정 해놓으면 어떻게 될까요?

2024-08-04 13:59 UTC, Flamme1004K commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +     */
친절하시네요 👍👍

2024-08-04 13:59 UTC, Flamme1004K commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +        });
두개 시나리오 말고, 각각 시나리오가 있으면 좋을 것 같아요! 분리해 볼까요?

2024-08-04 13:59 UTC, Flamme1004K commented on src/test/java/nextstep/subway/unit/path/PathServiceTest.java
> +public class PathServiceTest {
서비스 테스트 👍👍

2024-08-04 13:59 UTC, Flamme1004K commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    }
인수 테스트 👍👍

2024-08-06 07:39 UTC, jiyoung928 commented on src/main/java/nextstep/subway/domain/path/SectionEdge.java
> +public class SectionEdge extends DefaultWeightedEdge {
@Flamme1004K jgrapht 를 상속하면서 도메인과 라이브러리간 결합이 생긴다는걸 이번에 깨달았네요 😓  결합을 없애는 방법을 고민하다가 Factory 패턴으로 바꿔서 적용해봤습니다!

2024-08-06 07:46 UTC, jiyoung928 commented on src/main/java/nextstep/subway/service/path/PathService.java
> +        Map<Long, Station> stationMap = getStationMap(stationIds);
@Flamme1004K 기존 ShortestPathFiner class find 함수에 리턴 type으로 PathResponse 로 변경해서 최단경로를 가져오도록 수정해봤습니다. 
Factory 패턴으로 변경해서 서비스단에서는 Factory 호출 부분만 변경하고 라이브러리 변경시 Factory class와  ShortestPathFiner class 만 변경하면 될것 같은데 리뷰어님은 어떻게 생각하시는지 궁금합니다!

2024-08-06 09:52 UTC, jiyoung928 commented on src/main/java/nextstep/subway/service/path/ShortestPathFinder.java
> +    private final WeightedMultigraph<Long, DefaultWeightedEdge> graph;
@Flamme1004K 음..여러 쓰레드가 하나의 공유변수를 동시에 변경&접근하는 문제가 발생할 수 있어서 왠만하면 전역변수를 사용하지 않는 편이긴 한데 graph를 전역으로 해놓으면 factory class에서 공유할 수 있어서 오히려 효율적일까요...?

2024-08-06 14:43 UTC, Flamme1004K commented on src/main/java/nextstep/subway/service/path/PathService.java
> +        Map<Long, Station> stationMap = getStationMap(stationIds);
여러가지 방법이 있는데요! 
* 팩토리를 이용한 방법
* 정책 클래스로 만드는 방법
* 스프링 빈으로 만드는 방법
등등 여러가지 방법이 존재합니다.

이 중에 지영님이 선택한 것은 팩토리로 하는 방법을 만드신 것 같네요! 저는 이 방법도 매우 선언하지만, 이런 경우에는 외부에 대한 부분을 숨기기 위해 interface로 한번 감싸주는 것도 좋아 보입니다.

2024-08-06 14:45 UTC, Flamme1004K commented on src/main/java/nextstep/subway/service/path/ShortestPathFinder.java
> +    private final WeightedMultigraph<Long, DefaultWeightedEdge> graph;
> 여러 쓰레드가 하나의 공유변수를 동시에 변경&접근하는 문제가 발생할 수 있어서 왠만하면 전역변수를 사용하지 않는 편

에 대한 부분에 저도 공감하고 있어서 이 부분에 대해 질문을 드린 부분도 있었어요. 전역으로 계속 변경되는 부분인데, component로 전역으로 해놓는다면 빈과 상관없이 여러 쓰레드가 공유할 수 있기에 사이드 임팩트가 생길 수 있어서 질문을 드린 거였습니다.

2024-08-06 14:50 UTC, Flamme1004K approved these changes
안녕하세요! 

3단계 피드백 반영 잘 해주셨습니다. 이만 머지하도록 하겠습니다.

앞으로 남은 미션 응원하겠습니다!

화이팅입니다!

2024-08-06 14:50 UTC, Flamme1004K commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
>              assertThat(도착역없음.statusCode()).isEqualTo(HttpStatus.BAD_REQUEST.value());
피드백 반영 👍

2024-08-06 14:50 UTC, merged

2024-08-06 14:50 UTC, Flamme1004K commented on src/main/java/nextstep/subway/domain/path/SectionEdge.java
> +public class SectionEdge extends DefaultWeightedEdge {
잘하셨어요! 👍👍 만족합니다