🚀 1단계 - 구간 추가 요구사항 반영
next-step/atdd-subway-path pull request #861
Opened 2024-08-05 09:34 UTC by m5s3

안녕하세요 리뷰어님
잘부탁드립니다!

---

질문이 있습니다.
Mock을 처음 사용을 해보았습니다.
혹시 이런 방향으로 사용하는게 맞나요?

2024-08-05 12:57 UTC, catsbi requested changes
명수님 반갑습니다. 미션을 함께 하게 된 이한솔이라고 합니다. 잘부탁드려요 👍 

1단계 미션 잘 구현해주셨는데, 요구사항부분이 제대로 안된 부분들이 보여 코멘트 남겨드렸어요. 확인 후 리뷰요청 다시 부탁드려요!. 

그리고 Mock 테스트는 작성된 곳이 없는 것 같습니다 ㅠㅠ

2024-08-05 12:57 UTC, catsbi commented on src/main/java/subway/Line/application/LineService.java
> +        return new LineResponse(line.getId(), line.getName(), line.getColor(), line.getDistance(), createSectionsResponse(line.getSections()));
동일한 타입의 매개변수가 연달아 이어서 작성되고 있어요. 이럴 경우 휴먼에러로 순서가 뒤바뀔 경우, 컴파일단계에서 에러를 검증할 수 없고 런타임시에 문제가될 수 있습니다. 

예를 들면 이 노선의 이름은 빨간색인데 색깔은 신분당선일수가 있는 것이죠. 
빌더 패턴을 고려해볼 수 있습니다.

2024-08-05 12:57 UTC, catsbi commented on src/main/java/subway/Line/application/LineService.java
> +                .map(line -> new LineResponse(line.getId(), line.getName(), line.getColor(), line.getDistance(), createSectionsResponse(line.getSections())))
위에서 언급한 빌더패턴 혹은 정적 팰토리 함수를 이용하면 다음과 같이 작성될 수 있을 것 같네요. 
```suggestion
                .map(LineResponse::from)
```

2024-08-05 12:57 UTC, catsbi commented on src/main/java/subway/Line/application/LineService.java
> +        return new LineResponse(line.getId(), line.getName(), line.getColor(), line.getDistance(), createSectionsResponse(line.getSections()));
```suggestion
        return lineRepository.findById(lineId)
                .map(LineResponse::from)
                .orElseThrow(() -> new IllegalArgumentException("해당 지하철 노선은 존재하지 않습니다. id=" + lineId));
```

이렇게도 줄일 수 있을 것 같네요.

2024-08-05 12:57 UTC, catsbi commented on src/main/java/subway/Line/application/LineService.java
> +    private Map<Long, Station> toMap(List<Station> stations) {
사용되지 않는 함수라면 제거해주세요!

2024-08-05 12:57 UTC, catsbi commented on src/main/java/subway/Line/application/LineService.java
> +        }
도메인 관점에서 볼때 요청 정보를 가지고 null check및 업데이트 여부는 도메인 자체가 직접 평가해도 되지 않을까요?

2024-08-05 12:57 UTC, catsbi commented on src/main/java/subway/Line/domain/Section.java
> +    private Long downStationId;
노선정보는 직접참조인데 지하철 역 정보는 간접참조인 이유가 있을까요?

2024-08-05 12:57 UTC, catsbi commented on src/main/java/subway/Line/presentation/LineController.java
> +    @PostMapping("/lines")
lines resources는 공통이기에 class레벨로 올릴 수 있을 것 같네요

2024-08-05 12:57 UTC, catsbi commented on src/main/java/subway/Line/domain/Sections.java
> +    public void addSection(Section section) {
구간정보 추가가 그냥 add만 해서는 안되지 않을까요 🤔 

이전 구간과 이후 구간정보를 찾아서 분리한 다음 새로 추가될 구간과 연결해주는 작업도 되야하고, 아예 별도의 구간정보로 유효한 구간인지 유효성 검사도 해야 되지 않을까요?

2024-08-05 12:57 UTC, catsbi commented on src/main/java/subway/global/exception/BadRequestException.java
> +    private final String message;
Envelop Pattern 객체로 보입니다. BadRequestException으로 이름짓기보다는 더 적절한 이름을 짓는게 낫지 않을까 싶네요. 그리고 badRequest인지는 보통 응답 정보에 4xx로 알 수 있으니까요

2024-08-06 00:49 UTC, m5s3 commented on src/main/java/subway/Line/domain/Section.java
> +    private Long downStationId;
직접 참조로 수정을 해야 되는데.. 시간에 촉박해서 수정하지 못했었습니다..
수정사항 반영했습니다!

2024-08-06 00:50 UTC, m5s3 commented
이한솔 리뷰어님 정말정말 죄송합니다.. ㅠㅠ
제가 원격 레포지터리에 푸시를 덜 한채로 리뷰 요청을 했었습니다.. 정말정말 죄송합니다..

2024-08-06 11:07 UTC, catsbi approved these changes
명수님, 커밋 누락된 부분과 피드백 반영된 것 확인해보니, 잘 구현되어있네요 ㅎㅎ 
몇 가지 피드백 남겨드렸지만, 크지 않아 머지드리니 다음 단계 진행하시며 같이 고민해보시죠.1단계 머지하도록 하겠습니다!

2024-08-06 11:07 UTC, catsbi commented on src/main/java/subway/Line/application/LineService.java
> +                .orElseThrow(() -> new CustomException(NOT_FOUND_STATION));
중복되는 로직이 보이는데, 함수화 할 수 있지 않을까요?!

2024-08-06 11:07 UTC, catsbi commented on src/main/java/subway/Line/domain/Sections.java
> +        if(!optionalAfterSection.isPresent()) {
isEmpty()를 사용해도 될 것 같네요!

2024-08-06 11:07 UTC, catsbi commented on src/main/java/subway/Line/domain/Sections.java
> +        });
forEach를 사용하기보단 nonMatch나 anyMatch등을 활용하면 어떨까요?

2024-08-06 11:07 UTC, merged